### ISSUE TITLE
Pagination Component - First, Last, Position 

### ISSUE THREAD

**Issue by Daryl-Powley** [GovAlta/ui-components#1042]
Request: 
The current Pagination component has "Previous" and "Next".  Additional functions like first page, last page, number of items per page, position 1-10 of 35.  

The suggestions are a commonly known and used both inside and outside the GoA in various representations.  And these features are needed for our future work to display and move through reporting content.   

I have seen an example of this in Children Services, in the licensing, however it is written in Vue.  I have attached an example.  

Thank you,
Daryl 

> Include links to any examples, research or code to support your proposal, if available.
![Pagination Navigation Example](https://user-images.githubusercontent.com/102547115/221063249-e1f620af-216f-4239-bae6-1d04ea9975a7.png)

**Comment by ArakTaiRoth** [comment]
@Daryl-Powley I've created a story for this that you can see here, https://goa-dio.atlassian.net/browse/DDIDS-1265. To help us with prioritization are you able to elaborate why you're looking for this?

**Comment by Daryl-Powley** [comment]
Hi Dustin,

For Children's Services were are currently in the process or redesigning what I will can an online report for now that displays multiple rows of data.  The current implementation has the concept of displaying a page of information and being able to move to the next page, previous page, first page ...  This report currently has short comings, hence the new design.

We can implement the concepts using our own widgets for now, but probably within the next month the new report we be completed and we would like to use a standard widget before we go to SIT and UAT.

If this answers the question great, if not please let me know.

Thanks
Daryl.


Daryl Powley | Senior Consultant | CGI | Suite 800 10303 Jasper Avenue, Edmonton AB T5J 3N6  | P: 780-409-2169





Classification: Protected A

**Comment by ArakTaiRoth** [comment]
Closing the issue, as a resolution for the issue has been documented here, https://ui-components.alberta.ca/?path=/docs/components-pagination--items-per-page
