### ISSUE TITLE
Button icon names for react components do not match style guide 

### ISSUE THREAD

**Issue by saquigley** [GovAlta/ui-components#1046]
I'm not sure if this is a bug exactly.. However, button components reference icon names that are not the same as the design system iconography. 

In the Design System, the name is shown as: 
![image](https://user-images.githubusercontent.com/114440222/221697566-140dd2bc-777c-43b3-bc05-77b4d4fdd84b.png)

However, when referencing an icon in the button components, you must leave out the goa- prefix 

Example:  `<GoAIconButton icon="add-circle"  size="large" />`

**Comment by ArakTaiRoth** [comment]
@saquigley Our designer is looking at the design documentation, and will update this as necessary. @twjeffery just as a heads up.

**Comment by twjeffery** [comment]
I've updated the names of the icons in the design library to align with the icons available in development. There were a few others I caught as well (eg. arrow-back instead of arrow-right). But they should match now. Let me know if you notice anything else.
