### ISSUE TITLE
Update UI components in React library so that they comply with the design system documentation in Adobe XD.

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#107]
This is a resulting issue from issue #111, a design review of the React component library to ensure design compliance to the design system.

### React Library - Storybook 
[https://ui-components.alpha.alberta.ca/?path=/docs/react_react-basic-elements-button--variants](url)

### DIO - Adobe XD design system 
[https://xd.adobe.com/view/6d476aef-2324-4c9a-b42b-d28dfd0eb426-3814/screen/5e3c6a13-19c6-4b4f-a659-b81322beefb6/](url)

### Tracking Components across Design and Development
[https://docs.google.com/spreadsheets/d/1B3P0pP8SWTYsNN9xtVefBJmcd0RK54kS2sh5LzLnmiw/edit#gid=1161341563](url)

**Comment by Spark450** [comment]
Component compliance will be covered off through design reviews on web components.
