### ISSUE TITLE
we needed a GoAdropdown component in our story book with a input typehead

### ISSUE THREAD

**Issue by Akhilgsd** [GovAlta/ui-components#1084]
# What is being submitted?

In our new registration form feature, we needed a dropdown component with a type head so that we can type and get the right input from dropdown. it must need component because we have many dropdown options.

# Why are you submitting?

I am submitting this because we don't have that component in our storybook.

**Comment by Spark450** [comment]
Thanks for reaching out @Akhilgsd 

We have an issue [created to track this work] moved up to the top of the backlog. (https://goa-dio.atlassian.net/browse/DDIDS-1210?atlOrigin=eyJpIjoiYzQ0ZGVmYjU3ZTY4NGVmMmE3ZjFkYmU3ZDU2ZWFkZGIiLCJwIjoiaiJ9)

The design system team has created some [usage documentation](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Components-%7C-D3?node-id=8360%3A264334&t=x7K7u0TneGG5q4Tg-1) to help DDD product team designers and developers on the design system team create the UI component.

If you had a few moments to review our documentation, then discuss your needs and requirements that would help us build a usable and useful component.

When you have a moment, get in touch with [me on slack](https://goa-dio.slack.com/archives/DQH6L9QTB), we would love to hear more about your team's context.

**Comment by ArakTaiRoth** [comment]
@Akhilgsd Closing this issue, we have a story to create a Combobox with this feature in the future. If you want to get in touch with the team to discuss this story, please do.
