### ISSUE TITLE
unable to find the goa-table-sort-header in our library. there is no import for this component. 

### ISSUE THREAD

**Issue by Akhilgsd** [GovAlta/ui-components#1114]
![image](https://user-images.githubusercontent.com/122409529/235909441-89b1a866-9104-4b4f-a8e3-de86f224a855.png)

As per new business rules we need to implement sortable feature. we have our own GOA sortable component in our storybook but i don't see goa-table-sort-header in our library. there is no import for this component.  I used the React code in our story book.

![image](https://user-images.githubusercontent.com/122409529/235910665-cbdc4e08-1c1c-4c38-a5fd-c1d2770817e4.png)

Storybook URL-    https://ui-components.alberta.ca/?path=/docs/components-table--sortable

**Comment by vanessatran-ddi** [comment]
Hi @Akhilgsd 
There is a fix for React table sorting header in our current sprint and the fix will be released soon by this week. 
For your information, you can check the below alpha react piece of code: 
[React Demo App For Table Sort](https://github.com/GovAlta/ui-components/blob/alpha/apps/react-demo/src/routes/table.tsx#L2)

The `GoATableSortHeader` is imported from `@abgov/react-components`

I will keep you updated here once the new release is published.

**Comment by Akhilgsd** [comment]
Thank you
