### ISSUE TITLE
UI component - Combo box

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#113]
### Description
Create the combo box component for the react framework

### Design
[Adobe XD](https://xd.adobe.com/view/6d476aef-2324-4c9a-b42b-d28dfd0eb426-3814/screen/6b730443-fe89-4472-83b0-ba913c2fbf0f/)

### Acceptance Criteria
- [ ] Component built to the specification of the design
- [ ] Component documentation built to the specification of the design
- [ ] Build as a web component
- [ ] Code pushed to Storybook
[https://ui-components.alpha.alberta.ca/?path=/story/component-library-basic-elements-button-link--links](url)

## Completion Status

- [x] Web Component
- [ ] React
- [ ] Angular
- [ ] Vue

**Comment by Spark450** [comment]
Moved back to in progress, converting to web component.

**Comment by Spark450** [comment]
In web components "combo box" is just a property of the drop down.
