### ISSUE TITLE
UI component - Pagination

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#119]
### Description
Create the component for the react framework.

### Design
[Figma design](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/DIO-DS---Components?node-id=622%3A13964)

### Acceptance Criteria

- [ ] Component built to the specification of the design
- [ ] Component documentation built to the specification of the design
- [ ] Code pushed to Storybook
[https://ui-components.alpha.alberta.ca/?path=/story/component-library-basic-elements-button-link--links](url)

## Completion Status

- [ ] Web Component
- [ ] React
- [ ] Angular

**Comment by Spark450** [comment]
Get in touch with @ambroseyau for updates and enhancements to designs and documentation.
