### ISSUE TITLE
Remove "GoASpinner" from the ui-components library

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1190]
## Acceptance criteria:

* `GoASpinner` is a component that is a relic from a bygone era. It used to be supported, it is no longer supported and hasn't been for quite some time. It has been replaced by `GoACircularProgress`. Remove this from the current library.

**Comment by chrisolsen** [comment]
This component should *not* be removed, just deprecated. It is just a wrapper to the goa-spinner component, which is still used, as the CircularProgress component is just a wrapper for it.

**Comment by ArakTaiRoth** [comment]
Closing as there isn't anything we need to do here. Spinner is used for the CircularProgress so can't be removed or deprecated.
