### ISSUE TITLE
Character counter property for text area 

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1204]
# Acceptance criteria
[Figma design](https://www.figma.com/file/VFI5k6W7HdePpmVTO8IDku/%E2%9D%96-%7C-DS-Documentation?type=design&node-id=153%3A254865&mode=design&t=YUaVAdqRHEPBRnMW-1)
* Counter will sit inside of the text area
* Counter text color: Text/Default
* The counter will be added as a property to the text area 
  * Required: No
  * 2 variants
    * One counts the number of characters remaining
      * The counter will turn *color.interactive.error* when 1st number exceeds second number
    * The other counts the number of words typed
      * No error state on this, there is no limit
* Wording used for the character counter messaging in Figma is important, use that wording
---
Dec 5:
- Add character count and word count for both the limit and the validation + message at the bottom of the input for the user.   So that teams will be able to validate their content based on what makes sense for their content and service context

**Comment by twjeffery** [comment]
@chrisolsen

Add character count and word count for both the limit and the validation + message at the bottom of the input for the user. 

So that teams will be able to validate their content based on what makes sense for their content and service context.
