### ISSUE TITLE
Documentation: Change Text Field back to Input

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1213]
## Acceptance criteria

1. Change Text Field link to be Input link on Components page
2. Change heading on component page as well
3. Ping @twjeffery to make the same change at this time in the Figma component library.

**Comment by chrisolsen** [comment]
A wrapping component should be made to prevent this from being a breaking change.

**Comment by Spark450** [comment]
Ignore Chris's comment above, it pretained to the previous story content.
