### ISSUE TITLE
Design System Website - "Button Component" page

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1235]
## Acceptance Criteria:

* **NOTE:** "component sandbox" is **NOT** in scope for this story. There will be a separate story to tackle that functionality
* Examples in Services tab should not be included
* Right side navigation is not included
* Installation instructions below the sandbox is not included
* All content is Button specific content, but content style will be the same between all components, so create with re-usability in mind
* Make a generic `components.tsx` page that can be used to copy over to other component pages.

[Figma Design](https://www.figma.com/file/qWGWDvULAAZuVaDpXCRzqP/DS-Resource-Website?type=design&node-id=3418-668878&mode=design&t=AO0B9TMkIngk5Klf-4)

**Comment by chrisolsen** [comment]
https://deploy-preview-2--abgov-ui-component-docs.netlify.app/components/button

**Comment by ArakTaiRoth** [comment]
Closing as this has been completed
