### ISSUE TITLE
Keyboard behaviour on dropdown

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1237]
## Issue

When using the Dropdown with the keyboard, it is not behaving as expected. Dropdown options cannot be selected using the keyboard.

## Acceptance Criteria:

* Generally, we want the behaviour to be the same as the [native dropdown](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select)
* To make a selection "enter" key pressed, a dropdown item that is focused will be selected, dropdown closes
  * "space" does not make a selection or close dropdown

**Comment by ArakTaiRoth** [comment]
Ignore this story until #1181 is complete

**Comment by mtycholaz** [comment]
This is important for website accessibility.
