### ISSUE TITLE
[Feature Request]: Use @container queries

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1245]
### Is your feature request related to a problem? Please describe

Container queries were finally made available in svelte 3.58.0. 

### Describe the solution you'd like

Most of the existing @media queries should be replaced with @container queries

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_container_queries

## Acceptance criteria

- Create an example on the form stepper component page to show how the vertical orientation can be specced for wide screens
- Create a stand alone documentation page under the "Utilities" section that outlines what @container queries are, how they can be used, and gives some examples
- Work with @twjeffery to determine what @media queries need to be changed

**Comment by ArakTaiRoth** [comment]
Blocked until all current testing and in review stories are pushed to Alpha

**Comment by chrisolsen** [comment]
It is actually blocked because Jest fails unit tests with @container queries. Jest needs to be replaced with vitest
