### ISSUE TITLE
Date picker

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1264]
## Acceptance Criteria:
- Implement date picker as in [Figma design documentation](https://www.figma.com/file/dcR7GrX9kBvnLxA71m2ia8/Component---Date-picker?type=design&node-id=2295%3A53257&mode=design&t=db97sQqDODSxf6bj-1)
- Calendar shows 1 month at a time
- Single select date (not date range)
- Quick date selection button to be added to Storybook examples but not included in the component

**Note:** Green tag Ready for Dev on Figma indicates what to develop for
**Note:** Keep in mind that a date range will eventually need to work, just not for this iteration

**Comment by Spark450** [comment]
Hey @chrisolsen I was wondering if it would make sense and be feasible to include some reference or examples that pair up our date picker component with the ADSP calendar service?

**Comment by chrisolsen** [comment]
@Spark450 Making an example like that available would be a good idea 👍
