### ISSUE TITLE
[Bug]: Modal tab order for action buttons

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1275]
### Describe the bug

When the modal with actions is used and the user is tabbing through the action buttons the Secondary button is Focused First, then the Primary button. 

### To Reproduce

- To to the [Storybook documentation page for the modal](https://ui-components.alberta.ca/?path=/docs/components-modal--basic#with-actions) 
- open the "modal with actions" example
- Hit the tab key and watch the focus ring cycle

### Additional context

The desired behaviour is that the primary button is focused first, then the secondary button.

The focus should follow the hierarchy of the buttons in the modal

1. Primary
2. Secondary
3. Tertiary

**Comment by chrisolsen** [comment]
This is really controlled by the placement order of the buttons. If secondary is to the left of the primary, it will be focused first. ex https://mui.com/material-ui/react-dialog/

**Comment by Spark450** [comment]
Thanks for bringing this forward @chrisolsen as you said [it looks like we should keep our tab order aligned with the visual order](https://www.a11y-collective.com/glossary/tab-order/) on the buttons on the page.

I think this brings forward a question about the visual order of our buttons in the dialog @twjeffery Lets discuss if this is something that we want to consider changing in future. 

I will close this issue.
