### ISSUE TITLE
[Bug]: Small padding adjustment | padding-left on text area and text input inconsistent

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1276]
### Describe the bug

Can see on storybook. Padding left inside text input is 8px, padding left inside text area is 12px. 

This means that when stacking those fields vertically, they are misaligned. 

<img width="1353" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/6f64032f-c267-404b-83a7-7303b8f57fbe">

As per the design spec, the padding should be 12px on both.

### To Reproduce

Stack the text input and text area and put text in each input, you will see the different spacing.

Easy example to see here, in Basic form:
https://abgov-ui-react.netlify.app/

## Acceptance Criteria:
1. Left padding inside text box should be 12px

**Comment by ArakTaiRoth** [comment]
Merged
