### ISSUE TITLE
[Bug]: Trap focus not working in modal

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1277]
### Describe the bug

Focus does not stay "trapped" inside the modal when tabbing through the interactive elements.

### To Reproduce

- Go to the [Storybook documentation page for the modal](https://ui-components.alberta.ca/?path=/docs/components-modal--basic#with-actions) 
- open the "modal with actions" example
- Hit the tab key and watch the focus ring cycle

### Additional context

- When modal is open the focus should stay trapped inside the modal
- Investigate screen reader behaviour to ensure that it aligns with the standards outlined [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal)

**Comment by chrisolsen** [comment]
This *seems* to be a storybook issue

**Comment by ArakTaiRoth** [comment]
Can only replicate on storybook, not on an actual app. Closing the story.
