### ISSUE TITLE
[Bug]: Dropdown Items block is detached from the actual Dropdown (React)

### ISSUE THREAD

**Issue by pavel-goa** [GovAlta/ui-components#1289]
### Describe the bug

In some cases the dropdown items are detached from the dropdown.
This happens on React side. 

<img width="675" alt="image" src="https://github.com/GovAlta/ui-components/assets/120219423/1e004e66-2758-4506-858e-63d51a49bf9a">

### Not working:
```
  const handleReasonSelect = (_: string, value: string | string[]) => {
    setRejectReasonCode(value as string);
  };

...

<GoADropdown
  name={adjustmentItemId}
  value={rejectReasonCode}
  onChange={handleReasonSelect}
>
  {rejectReasons.map((reason) => (
    <GoADropdownItem
      key={reason.value}
      value={reason.value}
      label={reason.descriptionEnglish}
    />
  ))}
</GoADropdown>
```

### Works as expected:
```
  const handleChange = (_, username) => {
    setSelectedAssessor(username);
  };

...

<GoAFormItem label={null}>
  <GoADropdown
    name="Service"
    value={[selectedAssessor]}
    placeholder="Assign To"
    onChange={(_, value) => handleChange(_, value)}
    multiselect={false}
    width="180px"
  >
    {assessors.map((assessor) => (
      <GoADropdownItem
        key={assessor.value}
        value={assessor.value}
        label={assessor.description}
      />
    ))}
  </GoADropdown>
</GoAFormItem>
```

### To Reproduce

Not sure how to reproduce it

### What browsers are you seeing the problem on?

Chrome

### Additional context

The working version is wrapped in `GoAFormItem`

**Comment by mamadoutouregoa** [comment]
We are experiencing the same issue with angular (angular 14)
![angular_dropdown_issue](https://github.com/GovAlta/ui-components/assets/104030558/5af190f9-8644-4a33-882f-db2a60811a6f)

**Comment by mamadoutouregoa** [comment]
@chrisolsen  and @tzuge  Does this 1.0.0-alpha.212 version fix also the angular part ? I know that this bug was originally discovered in React, but we had it also in angular as per my comment above (see attached screeshot)

**Comment by mamadoutouregoa** [comment]
@tzuge I installed 1.13.0-alpha.1, but still the same issue
