### ISSUE TITLE
Change hero banner background to grey when no background image is supplied

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1295]
- Talk to Tom about the color to set.
- Existing gradient is not visible when grey background is shown

**Comment by twjeffery** [comment]
@amar-ABgov We will need to be able to change the colour of the text and margin if there is no background image.

Design for reference here: https://www.figma.com/file/qWGWDvULAAZuVaDpXCRzqP/DS-Resource-Website?type=design&node-id=3354-690506&mode=design&t=7xWLDWKcc2MZXC4w-4

**Comment by ArakTaiRoth** [comment]
> @amar-ABgov We will need to be able to change the colour of the text and margin if there is no background image.
> 
> Design for reference here: https://www.figma.com/file/qWGWDvULAAZuVaDpXCRzqP/DS-Resource-Website?type=design&node-id=3354-690506&mode=design&t=7xWLDWKcc2MZXC4w-4

@twjeffery Would it make more sense to just allow them to change the colour of the text and margin always? Instead of just when there is no background image?

**Comment by twjeffery** [comment]
> > @amar-ABgov We will need to be able to change the colour of the text and margin if there is no background image.
> > Design for reference here: https://www.figma.com/file/qWGWDvULAAZuVaDpXCRzqP/DS-Resource-Website?type=design&node-id=3354-690506&mode=design&t=7xWLDWKcc2MZXC4w-4
> 
> @twjeffery Would it make more sense to just allow them to change the colour of the text and margin always? Instead of just when there is no background image?

It's a good question, I'm ok either way. If that makes more sense let's do that.

We know if there is an image, it should be gradient overlay, white text, and a margin that gives space for the image above. 
If there is no image then there is no gradient overlay, an adjusted margin, and a user can choose the background colour and text colour.
