### ISSUE TITLE
[Feature Request]: Ability to change the size of the modal

### ISSUE THREAD

**Issue by StevenAleong** [GovAlta/ui-components#1297]
### Is your feature request related to a problem? Please describe

We want to use the modal in an admin console that lets users add new data that has a text area editor. The current size is rather tight.

### Describe the solution you'd like

Either the ability to enter in a min-width for the modal while still being responsive or if there are options available built directly in the configuration properties such as [small, default, large, extra-large] or something along those lines.

Maybe another neat feature would be to allow the modal to be maximized to the entire browser width/height.

### Provide evidence this is a needed component

If you use the modal as a form, the width is small and tight

### Describe alternatives you've considered

To be consistent with the general design of GoA components, no other options were considered.

### Do you have anything already created for this that we can use?

no

### Are you currently using this proposal inside your own service

None

### Are you able to assist to bring the feature to reality?

yes

**Comment by chrisolsen** [comment]
Hey @StevenAleong ,

The modal component does have a `width` property that can be set, but isn't currently documented. It accept a string value so you can use your unit of choice ex. `70ch`,  `80%`, etc

**Comment by ArakTaiRoth** [comment]
Closing as this property already exists, just isn't documented. Added a story to remedy that #1298
