### ISSUE TITLE
[Bug:] In react 4.12.0, useNavigate() does not seems to be available or included

### ISSUE THREAD

**Issue by binoy-goa** [GovAlta/ui-components#1301]
In react 4.12.0, useNavigate() does not seems to be available or included to incorporate in GoAAppHeader. When a button is clicked, it seems to prevent it from navigating.

For now as a workaround an alternative solution is found to use Link  and useLocation() instead.

**Comment by ArakTaiRoth** [comment]
@binoyk23 One of the things React states about using hooks, which `useNavigate` is a hook, is this: `Do not call Hooks in event handlers.`. Hooks like `useNavigate` don't work inside event handlers. This is why it's not working, and there's nothing we can do about it, this is specific to React. If you think this is wrong, please supply more information such as the exact code you're using that's not working.

**Comment by ArakTaiRoth** [comment]
@binoy-goa Closing as this has been discussed in Slack.

Idea is that `useNavigate` actually does work. Just not in your specific case, as there is more complicated code surrounding it that is causing it to break. This is not an issue with our library.
