### ISSUE TITLE
[Bug]: Dropdown input styling and focus issues

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1307]
### Icon
Icon should flip when dropdown is open and closed.
- when dropdown menu open: arrow up
- when dropdown menu closed: arrow down

### Additional context

Talk to @twjeffery for more detail and discussion if needed.

**Comment by Spark450** [comment]
@vanessatran-ddi & @chrisolsen will this be fixed as part of the work to combine the combobox and dropdown?

**Comment by vanessatran-ddi** [comment]
> @vanessatran-ddi & @chrisolsen will this be fixed as part of the work to combine the combobox and dropdown?

@Spark450 Yes correct.

**Comment by Spark450** [comment]
@vanessatran-ddi Would it make sense to link this issue to this PR https://github.com/GovAlta/ui-components/pull/1309

so it can close both issues?

**Comment by vanessatran-ddi** [comment]
> @vanessatran-ddi Would it make sense to link this issue to this PR #1309
> 
> so it can close both issues?

Yes I think it's a good idea.
