### ISSUE TITLE
Design System Website - All components page

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1324]
## Acceptance Criteria:

- Page will be responsive and follow the breakpoint guidelines as outlined in the Figma designs
- Categories act as "anchor links" on the all components page and will jump the user to that section of the page

This page already exists. Maybe needs some touch ups and review and test.

The Back to Top links aren't in the design, but we are keeping them as is.

[Figma designs](https://www.figma.com/file/qWGWDvULAAZuVaDpXCRzqP/DS-Resource-Website?type=design&node-id=3383%3A593932&mode=design&t=s9k8yLJULykQFHBp-1)

**Comment by ArakTaiRoth** [comment]
Closing
