### ISSUE TITLE
Design System Website - Button page

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1325]
## Acceptance Criteria:

- Page will be responsive and follow the breakpoint guidelines as outlined in the Figma designs
- Framework selector (React/Angular) to be persistent (stored in cookies) so that on subsequent visits, the site remembers the users preference
- No Design Guidelines page or tab for this first iteration\
- No Open in New Window or Codepen links will be included
- The anchor links will have no icon beside them for now

[Figma design](https://www.figma.com/file/qWGWDvULAAZuVaDpXCRzqP/DS-Resource-Website?type=design&node-id=3418%3A668878&mode=design&t=s9k8yLJULykQFHBp-1)

**Comment by ArakTaiRoth** [comment]
Closing as this has been done
