### ISSUE TITLE
[Bug]: Table sort no longer working

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1327]
### Describe the bug

The `_sort` or `onSort` functionality is no longer firing.

### To Reproduce

This can be seen in our [Storybook](https://ui-components.alberta.ca/?path=/docs/components-table--sortable). Or on either of our Angular or React demo apps.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Additional context

I changed the code in `Table.svelte` to the last version of the [file](https://github.com/GovAlta/ui-components/blob/5a11b616f953fe8905a42a8b69655bac3d0cea0a/libs/web-components/src/components/table/Table.svelte), and table sorting worked. So this problem was introduced in this [commit](https://github.com/GovAlta/ui-components/commit/9a1054f6e76e81ad328927ae30a5d33f648fffba)

**Comment by mamadoutouregoa** [comment]
By the way the pagination no longer works as well
