### ISSUE TITLE
Adjust min and max widths Popover

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1335]
# Info
Currently how min-width, max-width, and width are handled on the Popover element is confusing and handled poorly, with multiple implementations of width and max-width.

## Acceptance Criteria:
1. Add a minimum width to Popover of 10rem (160px)
2. Currently there are 2 places where max-width is defined for the Popover, and 3 places where width is defined. Fix this.
3. Make sure that min and max width work correctly (as in the popover will expand to max width properly)
4. Make sure the Popover in AppHeader can expand to a max of 320px.

## More Info
Currently `width` and `max-width` are defined here, inline style in `popover-content`:
![image](https://github.com/GovAlta/ui-components/assets/1081991/a385f6ec-ed5f-4c6d-b9a6-caba577d72e7)
But you'll notice, `width` is defined twice here in the style for popover-content, and `max-width` is defined a second time as well:
![image](https://github.com/GovAlta/ui-components/assets/1081991/af69527b-83a1-4242-b754-611c7cf848c0)
Now, obviously these aren't all used. In actual practice, the inline styles are used, and if not defined (`width`), then `width: max-content` is used. It's just confusing and needless to have all these definitions for the same styles.

There's also a problem with the AppHeader and the Popover used for the menu in the AppHeader. We set a static width for that menu's popover, and because it's set, the popover isn't able to expand to it's max-width if people put in slightly longer content. This means the actual width of the menu is a static 256px, not the 320px max-width set in the Popover.

**Comment by Spark450** [comment]
@ArakTaiRoth Can you provide some example where max-width is not working and where max-width and width are both defined?

**Comment by ArakTaiRoth** [comment]
Not relevant any longer
