### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#134]
Since the definition of toolbar varies widely across different design systems, please refer to the Alpha section of the design system for some more context.

**Questions to consider**

Are there significant UI differences between Mobile/tablet/desktop?

Does toolbar = sticky header, or is a toolbar a subset of a sticky header?

What content goes in a toolbar, and what content goes in a site header?

Buttons?

Icon buttons?

Hamburger menu?

Ellipsis menu?

Page/section title?

Navigation controls?

If navigation controls live here, any guidance on deciding between navigation controls here vs at the bottom of a page?

Can you have a toolbar within a specific component as well? 

eg. bold/italic/underline controls in a comment component?

Is this out of scope?

Out of scope

What should not be included in this task?What should be captured as a separate subsequent task?

ConsiderationsHave other designers built similar components?Do examples currently exist in the DIO design system?Do examples currently exist in the GOA design system?

<img width="1000" alt="Screen Shot 2021-04-14 at 12 46 13 PM" src="https://user-images.githubusercontent.com/51723535/138497079-3f0f6191-65fb-4ce4-bb74-dfe76212572f.png">

**Comment by ferrarino5** [comment]
Test
