### ISSUE TITLE
Design system website: Component page(s)

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1356]
## Acceptance Criteria:

- Pages be created according to [this layout](https://www.figma.com/file/qWGWDvULAAZuVaDpXCRzqP/DS-Resource-Website?type=design&node-id=4743-161759&mode=dev)
- "Code examples" and "Design guidelines" tabs will be included but no content will be added to any of the "design guidelines tabs"
- A least one "code example" will be included per component page, work with @twjeffery on the specifics of each example
- Pages to be included:
  - Accordion
  - Badge
  - Block
  - Button (Completed by earlier story)
  - Callout
  - Checkbox
  - Chip
  - Combobox
  - Container
  - Details
  - Divider
  - Dropdown
  - File uploader
  - Footer
  - Form item
  - Gride
  - Hero banner
  - Icons
  - List
  - Microsite header
  - Modal
  - Notification banner
  - Pagination
  - Progress indicator
  - Radio
  - Skeleton loader
  - Spacer
  - Site header
  - Stepper
  - Table
  - Text area
  - Text field
  - Tooltip

**Comment by ArakTaiRoth** [comment]
Closing this story as it is covered by multiple smaller stories now.
