### ISSUE TITLE
Spike: Investigate Mobile App Development

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1371]
## Acceptance Criteria:
1. How can we use our components within Ionic (Capacitor)
    * Can we use our components directly? (Using Angular?)
2. A quick app showcasing our components being used within Ionic (developed using Angular)
    * Use the following components:
      * Button
      * Input (Form Item)
      * Icon
      * Container
3. Test zoom in and out functionality

**Comment by ArakTaiRoth** [comment]
@chrisolsen Can you include a link to the developed app and repo?

**Comment by chrisolsen** [comment]
https://github.com/chrisolsen/go-a-prototyp

**Comment by ArakTaiRoth** [comment]
Closing, documentation provided
