### ISSUE TITLE
[Bug]: When there are so many menu items on goa-app-headers, it makes the menu be unresponsive

### ISSUE THREAD

**Issue by vanessatran-ddi** [GovAlta/ui-components#1377]
### Describe the bug

![image](https://github.com/GovAlta/ui-components/assets/120135417/01924843-8de6-4af5-8de7-efb73aab82ec)
Demo link: https://deploy-preview-8--abgov-ui-component-docs.netlify.app/

The context: 

When the `goa-app-header` has so many menu items, then the breakpoint doesn't break correctly, and the menu's length is too long when we resize the browser. 

### Provide Code

```
 <GoAAppHeader heading="Design system" maxContentWidth="1500px">
                        <Link to="/get-started">Get started</Link>
                        <Link to="/patterns">Patterns and templates</Link>
                        <Link to="/components">Components</Link>
                        <Link to="/design-tokens">Styles</Link>
                        <Link to="/content">Content</Link>
                        <Link to="/support">Support</Link>
                        <Link to="/report-a-bug" className="interactive">Report a bug<span className="report-bug-icon"><GoAIcon type="open"/></span></Link>
                    </GoAAppHeader>
```

### To Reproduce

When the window's width is less than 1071px.

## Acceptance Criteria:
1. AppHeader collapses when links hit the Heading automatically

**Comment by chrisolsen** [comment]
I think the only way to do this is to have a property that allows the user to set the menu to use the dropdown at screen widths where all the links would be shown. Having this be automated would cause confusing to developers when the menu is rendered in an unexpected state. Unless others feel different? @Spark450 @ArakTaiRoth
