### ISSUE TITLE
Bug: SideMenu URL Handling

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1384]
# Info
Currently we have this line in `SideMenu.svelte` 
```javascript
const current = url.endsWith(child.getAttribute("href"));
```
This line determines if a link is marked as current. The problem with this is it only finds the current link if the url ends with that link. But if you have an attributes in the url after the link, it breaks. This line needs to be changed to be more nuanced and allow for properties in the URL.

## Acceptance Criteria:
1. URLs with the link name in them should activate the current class in the SideMenu. Even if that URL has a property such as `?name=foo` after the URL.

**Comment by heatherobjois** [comment]
It should also work if there is a # in the URL. Our Angular Keycloak implementation always puts #state= after the URL and it breaks in this case as well.

**Comment by heatherobjois** [comment]
One other thing: we have a screen where you can view lists of staff members at child care programs.
![image](https://github.com/GovAlta/ui-components/assets/91573399/96433798-9d13-451d-8e84-24254cf88b31)
 
The program is selected using a dropdown, and then the URL changes to have the Program ID in it. Once the program is selected, the highlighting on the left nav goes away.
![image](https://github.com/GovAlta/ui-components/assets/91573399/59c24e4a-6b7b-494e-9daf-10306bce7892)

It would be ideal if the left nav highlighting could handle this scenario as well.
