### ISSUE TITLE
[Bug]: AppHeader Menu isn't active

### ISSUE THREAD

**Issue by vanessatran-ddi** [GovAlta/ui-components#1386]
# Info

https://deploy-preview-10--abgov-ui-component-docs.netlify.app/get-started/developers/browsers

![image](https://github.com/GovAlta/ui-components/assets/120135417/7d36ac66-a78b-43e5-9c95-d1fd0faf1acf)

Step to produce:
Step 1: Click Get Started
Step 2: Click Overview on Sidebar Menu 

Expected: The AppHeader Menu Get Started should be highlighted.

Added @twjeffery

## Reasoning
This is likely being caused by the same issue as what's affecting story #1384 . As in, likely we're just checking the end of the URL for a match to the link, and because the end doesn't match any longer, it doesn't show up as being active.

## More Info
This is maybe slightly more complicated than originally thought. If you just click the Get Started link, the active link doesn't automatically get shown, it only gets shown if you refresh the page. This has also been tested with this basic code:
```javascript
<goa-app-header url="https://alberta.ca" heading="Judicial Scheduling">
  <a href="/calendar">
      <span>Calendar</span>
  </a>
  <a>
      <span>Work List</span>
  </a>
  <a href="#">
      <span>Time-Off</span>
  </a>
</goa-app-header>
```
And when you go to `/calendar`, nothing is marked as an active link. The active link also doesn't work in our Storybook, but that might be just a Storybook issue.

**Comment by heatherobjois** [comment]
Another issue with the active app header menu item to report. If you are on a page and the app header menu is highlighted successfully, and you navigate using Angular routing (e.g. does not trigger a full page refresh), the menu item stays highlighted even though it shouldn't. It only seems to work if you refresh the page you are on, or if you use the back button to get to the page.
