### ISSUE TITLE
[Bug]: Unable to "turn on" the "Trailing Icon" element in the goa-Text-Field component.

### ISSUE THREAD

**Issue by jim-muirhead** [GovAlta/ui-components#1388]
### Describe the bug

<img width="237" alt="image" src="https://github.com/GovAlta/ui-components/assets/107221573/abb37e49-0d94-461c-8f69-d0d73f9e3045">

For the goa-Text-Field component, there is no toggle switch in the Figma right sidebar similar to the "Leading icon" toggle switch to turn the "Trailing icon button" element on/make visible.

### To Reproduce

Select a goa-Text-Field component instance on a Figma page, then view the right sidebar.

**Comment by ArakTaiRoth** [comment]
Closing as this is not a development story, but for Figma instead. Already notified @twjeffery about this.
