### ISSUE TITLE
Container documentation isn't clear on title usage

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1392]
# Info
Currently our container documentation isn't clear on how to use the slots. You have to scroll down and find the specific text that says it should be used with `accent="thick"`. This should be in the properties table as well for easy and clear messaging.

# Acceptance Criteria
1. Container documentation is updated to include a message in the description for `title` and `actions`, that states that they are to be used with `accent="thick"`.

**Comment by ArakTaiRoth** [comment]
Closing as the PR was merged before it was assigned to this story
