### ISSUE TITLE
Form Stepper: events firing twice

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1395]
# Info
When using the form stepper and clicking on elements in the stepper itself to change pages (instead of clicking the buttons), the attached event is fired twice.

# Replication Steps
1. Spin up the angular demo
2. Go to the Form Stepper page
3. Update the page to show console logs when events are fired
4. See the problem

## Acceptance Criteria:
1. When clicking the Form Stepper visual components, attached events should only be fired once

**Comment by chrisolsen** [comment]
https://jam.dev/c/25fa8133-feb0-437f-a0fd-9a71a34a5da9

**Comment by ArakTaiRoth** [comment]
Closing, as this has been completed in a previous PR
