### ISSUE TITLE
Bug: AppHeader Menu Currently outside the AppHeader

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1401]
# Info:
The AppHeader menu is currently outside the AppHeader, in lines underneath it, one line per link.

This was introduced at some point in time between our last release and now, this is currently a problem in Alpha, and not in Production.

![image (1)](https://github.com/GovAlta/ui-components/assets/1081991/905a231e-e504-4a87-8c9c-f33bd67ff46b)

It also doesn't look entirely proper in mobile view either:

![image](https://github.com/GovAlta/ui-components/assets/1081991/7e9f28a9-4381-4f65-b945-c817c2d534cc)

## Replication Steps:
Spin up either the Angular Demo, React Demo, or Storybook and you can see this problem immediately with no changes necessary.

## More Info
The most likely culprit is this [PR](https://github.com/GovAlta/ui-components/pull/1374) and more specifically this [file](https://github.com/GovAlta/ui-components/pull/1374/files#diff-04a9aa408326529374398551308ea801391b68091e9bcb9f3000a6ebb5333d72) or this [file](https://github.com/GovAlta/ui-components/pull/1374/files#diff-a9d9eb19ac2cc689fd44c1a7aaccc08cd9781e0a2eb10fdb13371c92cd68ff0f) that has caused the issue.

**Comment by chrisolsen** [comment]
The issue is neither of the files mentioned, but is the postcss function is not being run for the final build.
