### ISSUE TITLE
Deploy a Front-end Prototype for case study

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1402]
## Background
To deploy the front-end prototype built by the PNP team, along with an informative landing page, so that we can have a linkable prototype that demonstrates the efficiencies gained by using our design system and provides contextual information to the viewers.

## Acceptance Criteria:

- Source Code: Retrieve the source code for the prototype built by the PNP team from the Housing Ministry.
- Landing Page: Create a landing page that provides context about the prototype and mentions the caveats around "wrapping" the components, along with a recommendation to avoid this practice for better reactive forms compatibility.
  - Note: the landing page needs some "design work" before it can work worked on. The Figma link will be attached to this issue.
- Deployment: Deploy the prototype and landing page to the staging environment.
- Link Generation: Create a permanent, shareable link to the deployed prototype and landing page.
- Notes

**Note**
The PNP team had "wrapped" the design system components due to limitations in the earlier version. Future teams are advised not to follow this practice as it interferes with reactive forms.

**Comment by ArakTaiRoth** [comment]
Blocked until we're moved into EMU

**Comment by ArakTaiRoth** [comment]
Removing, as we're no longer interested in moving to the EMU
