### ISSUE TITLE
Update CSS for typography

### ISSUE THREAD

**Issue by vanessatran-ddi** [GovAlta/ui-components#1403]
Context: 
The design https://www.figma.com/file/qWGWDvULAAZuVaDpXCRzqP/DS-Resource-Website?type=design&node-id=3521-610541&mode=design&t=nviy1HXXrXg0cGaJ-0

gives us some ideas that our current CSS typography should match to 90% of use cases. This ticket is going to address the below: 
1. p: is(:last-child): margin-bottom: 0 
(Our current p always has margin-bottom: 16px, in most cases it isn't good)
2. format style for dd, dt

Example:
(Dt, Dd)
![image](https://github.com/GovAlta/ui-components/assets/120135417/67c96ffe-ddfe-4201-8407-8209f7b93aa6)

**Comment by ArakTaiRoth** [comment]
Blocked until we decide what's going on with this story, https://goa-dio.atlassian.net/browse/DDIDS-1399

**Comment by ArakTaiRoth** [comment]
Closing this story as it isn't relevant any longer
