### ISSUE TITLE
[Bug]: GoAInputDate z-index issue

### ISSUE THREAD

**Issue by solittlework** [GovAlta/ui-components#1406]
### Describe the bug

Parts elements, especially of the inputs in GoAInputDate will be on the top of the GoAModal, as follows. 

![image](https://github.com/GovAlta/ui-components/assets/8821979/931b053d-d8b3-4efb-a565-1e3085c30cd0)

### To Reproduce

Open an GoaModal on the top of a GoAInputDate component.

### Additional context

The initial investigation shows the elements of the GoAInputDate above of the GoAModal all includes a "z-index:1" style. Removing the "z-index:1" will resolve the issue. And, based on the reporter's observation, the removing of the "z-index:1" style will not affect the usage of the GoAInputDate. This issue might occur in other other date and time related components.

**Comment by ArakTaiRoth** [comment]
@solittlework I'm unable to replicate the issue with the information you've posted here. Using our latest versions of `@abgov/react-components: "^4.14.0`, and `@abgov/web-components: "^1.14.0"`. This is what I've created:
![image](https://github.com/GovAlta/ui-components/assets/1081991/b797a431-3e20-4dbe-82e2-a83fda9bbbaa)
And what the modal looks like when it's popped up:
![image](https://github.com/GovAlta/ui-components/assets/1081991/c587b061-c9d6-44dd-ba96-8cc1a155fd17)

If you think I've done something in error, please try to replicate using our [React Template](https://github.com/GovAlta/ui-components-react-template) and give me the code to recreate the issue.

**Comment by solittlework** [comment]
@ArakTaiRoth, thank you for your testing. There might be two potential issues. 1) the version issue. 2) component layering issue. In this case, I am going to close this task at this moment.
