### ISSUE TITLE
Sandbox property should support Slot for Sandbox renderer (lower priority)

### ISSUE THREAD

**Issue by vanessatran-ddi** [GovAlta/ui-components#1421]
## Acceptance Criteria:
- Right now if we want to make sandbox interactive for "slot", we don't have the way to do so. Right now we only support string, boolean, number, list.
- There are many components have slot properties such as `Tabs`, `Accordion`...

### Screenshots:
![image](https://github.com/GovAlta/ui-components/assets/120135417/aa768ccb-b204-453a-aef7-4c2aa0eaff31)

Right now I don't pass the "slot" property to the Sandbox, as a result, Accordion has headingcontent with a badge, but there's no where under Code snippet showing `headingcontent`.

**Comment by ArakTaiRoth** [comment]
Closing this story as it's no longer wanted
