### ISSUE TITLE
Design system website - Feedback and Alerts components

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1424]
## Acceptance Criteria:

**Consider the following for MVP** 

- only the "development" documentation will be created
- As much as possible ui-components will be used in their current state. Gaps will be noted and separate user stories will be created to handle refinements to components.

Create pages for the following components: 

- [x] Badge
- [x] Callout
- [x] Modal
- [x] Chip
- [x] Notification banner
- [x] Progress Indicator
- [x] Temporary notification
- [ ] Tooltip

**Comment by ArakTaiRoth** [comment]
Closing as this has been completed
