### ISSUE TITLE
[Bug]: Investigate: Error property not being removed Dropdown

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1445]
# Info
With the below code and the below Stackblitz you can see this issue.
1. Click Save button to trigger form validation and mark the dropdown and input with errors
2. Fill out the input, notice it removes the Form Item error, and the error border around the input
3. Select something in the dropdown, notice the Form Item error disappears, but the red error border doesn't.

After some testing, this is not an issue with changing the boolean value itself. If you copy the error checking for the input form control into the dropdown form control, it will work. This is an issue with the form control being assigned to the dropdown and checking its value in the error property.

[StackBlitz](https://stackblitz.com/edit/stackblitz-starters-db5tom?file=src%2Fapp%2Fhome%2Fhome.component.ts)

Code to Replicate:
```javascript
<goa-form-item
        label="Color"
        requirement="required"
	[error]="colorFormCtrl.hasError('required') && colorFormCtrl.touched ? 'You must select a color.' : null"
>
     <goa-dropdown
           goaValue
           name="colors"
           [formControl]="colorFormCtrl"
           [error]="colorFormCtrl.hasError('required') && colorFormCtrl.touched"
           [value]="colorFormCtrl.value"
     >
          <goa-dropdown-item
               *ngFor="let color of colors"
               [value]="color"
              [label]="color"
         >
        </goa-dropdown-item>
     </goa-dropdown>
</goa-form-item>

<goa-form-item
	label="Description"
	requirement="required"
	[error]="form.controls['descriptionFormCtrl'].invalid && form.controls['descriptionFormCtrl'].touched ? 'You must enter other description.' : null"
>
	<goa-input
		name="otherDescription"
		goaValue
		width="398px"
		[formControl]="descriptionFormCtrl"
		[error]="form.controls['descriptionFormCtrl'].invalid && form.controls['descriptionFormCtrl'].touched"
	></goa-input>
</goa-form-item>

<goa-block gap="m">
  <goa-button (_click)="onCancel()" type="secondary">Cancel</goa-button>
  <goa-button (_click)="onSubmit()" type="primary">Save</goa-button>
</goa-block>
```

```javascript
import { Component, OnInit } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  FormControl,
  Validators,
} from '@angular/forms';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent {
  form: FormGroup;
  colors: string[] = ['red', 'green', 'blue'];
  colorFormCtrl = new FormControl('');
  descriptionFormCtrl = new FormControl('');

  constructor() {
    this.form = new FormGroup({
      colorFormCtrl: this.colorFormCtrl,
      descriptionFormCtrl: this.descriptionFormCtrl,
    });
  }

  onSubmit() {
    this.colorFormCtrl.setValidators([Validators.required]);
    this.colorFormCtrl.updateValueAndValidity();

    this.descriptionFormCtrl.setValidators([Validators.required]);
    this.descriptionFormCtrl.updateValueAndValidity();

    this.form.markAllAsTouched();

    if (this.form.valid) {
    }
  }

  onCancel() {}
}
```

## Acceptance Criteria:
Unsure on the exact acceptance criteria and what's required from this story, as it's not clear what the issue is and even if it's something we can do something about. Bottom line, we should be able to remove the error from a dropdown field in this manner.

**Comment by chrisolsen** [comment]
Pretty sure the issue is with the `colorFormCtrl.touched` which we have seen before.

**Comment by ArakTaiRoth** [comment]
Closing as this can no longer be replicated. Even with an older version of angular-components (2.5.0) and of web-components (1.18.1), so perhaps this was fixed on a later update from when this was created.
