### ISSUE TITLE
Icon: Pencil variant missing outlined version

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1454]
## Acceptance Criteria:
Pencil icon only has filled variant. 
Add outlined variant.

<img width="926" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/36ae6876-e33c-44cf-814f-9b79a17c5723">

Ask @twjeffery for svg file, he doesn't know how to upload it here.

**Comment by Spark450** [comment]
Also reported by FSD Jeremy Payne

**Comment by twjeffery** [comment]
Also reported by UX designer Antarpreet Kaur and her team.
