### ISSUE TITLE
Input: Date type defaults to today's date in Safari

### ISSUE THREAD

**Issue by achantz** [GovAlta/ui-components#1455]
### Describe the bug

In Safari, the input component of type date, datetime-locale or time all render with today's date and/or time. 

<img width="380" alt="image" src="https://github.com/GovAlta/ui-components/assets/28713495/be48333d-a633-4a58-a096-44f001ae0a71">

In the imge above the input is bound to a form control with an initial value of null.

Safari Version: 17.1 (19616.2.9.11.7)
MacOS Version: 14 (Sonoma)

Problem does not seem to occur in Chrome. Have not tested FireFox or Edge.

### Provide Code

Angular: "@angular/core": "~16.1.0",
Web Components: "@abgov/web-components": "^1.14.0",
Angular Web Components: "@abgov/angular-components": "^2.5.0",
Angular standalone component.

In Template
```
<goa-input
    goaValue
    name="birthDate"
    data-cy="birthDate"
    type="date"
    [min]="minDate"
    [max]="maxDate"
    placeholder=""
    [formControl]="formGroup.controls.birthDate"
    [value]="formGroup.controls.birthDate"
  >
  </goa-input>
```

In implementation
```
public formGroup = new FormGroup<PreScreenType>({
    isApplyingOnBehalf: new FormControl(null, { validators: [Validators.required] }),
    isInAlberta: new FormControl(null, { validators: [Validators.required] }),
    immigrationStatus: new FormControl(null, { validators: [Validators.required] }),
    birthDate: new FormControl(null, { validators: [Validators.required] }),
  });
```

### To Reproduce

1. Create Angular 16 application
2. Import ReactiveForms module into component
3. Create FormGroup or FormControl to bind input to
4. Add input to page (as shown in code above)
5. Bind input
6. Set initial value to either (null, '', or undefined) in Form Control implementation (makes no difference in this case and results in the same thing)
7. Serve application
8. Browse to app in Safari 

### What browsers are you seeing the problem on?

Safari

**Comment by ArakTaiRoth** [comment]
@ArakTaiRoth investigate if this is an issue with the native HTML component

**Comment by ArakTaiRoth** [comment]
@achantz Just letting you know we're closing this story. This is the default functionality of the default `input type="date"` component in HTML, so our component isn't doing anything different and it likely can't be fixed.

**Comment by achantz** [comment]
Hi Dustin,

Thanks for looking into this.

– Angelo
