### ISSUE TITLE
Hyperlink icon button

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#146]
# What is being submitted?
e.g. Edit button, Close button, remove/delete 

For functions that don’t warrant a primary/secondary/tertiary button. 

Can’t be a standalone icon (accessibility), so it should come with a label

# Why are you submitting?
- What evidence do you have that it’s needed by multiple services across government?
- What evidence do you have that it meets the needs of the users of those services?
- Have you checked that it doesn’t already exist in the DIO Design System?

# Examples, links, and research
**Considerations**

-Can this type of button be used on different colour backgrounds (other than white)? If so recommendations for contrast ratio check. 

-What are the recommended margins for this component?

-When should you use this type of button instead of a “regular” button

**Examples**

Close

Edit

Remove

Delete

Contact info: phone number, email address (could be a different story)

**States**

default

hover

Focused

pressed?

# Anything else
Related to [button component](https://github.com/GovAlta/ui-components/projects/4#card-76433764)
- Add any other context or screenshots about the feature request here
![Screen Shot 2021-03-24 at 1 50 21 PM](https://user-images.githubusercontent.com/51723535/138522904-99861d7f-5814-44e8-afd4-cc929ea877a9.png)
![Screen Shot 2021-03-24 at 3 50 36 PM](https://user-images.githubusercontent.com/51723535/138522906-9357c578-c32b-466f-a1d7-90772ee64ad3.png)
<img width="720" alt="Screen Shot 2021-03-25 at 9 33 46 AM" src="https://user-images.githubusercontent.com/51723535/138522908-ab8af2e1-6243-46ee-b0f0-107e594611ab.png">
<img width="720" alt="Screen Shot 2021-03-25 at 9 34 37 AM" src="https://user-images.githubusercontent.com/51723535/138522909-58e416ec-d8d9-4f09-b9d1-db6d808886b0.png">
<img width="721" alt="Screen Shot 2021-03-25 at 9 34 53 AM" src="https://user-images.githubusercontent.com/51723535/138522911-f0c84759-757e-4247-923c-34bc66bff477.png">
.

**Comment by chris24mar10** [comment]
Here to help!
