### ISSUE TITLE
[Feature Request]: Ability for the site header to be sticky

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1473]
### Is your feature request related to a problem? Please describe

Sometimes teams want to have the site header sticky (stick to the top of the page) so that they don't have to scroll all the way up to get back to main menu items. 

### Describe the solution you'd like

Provide a recommended solution for the site header to stick to the top of the page, and/or a recommendation for a better design solution.

eg. if the need is to not have to scroll back up, a back to top button could be a better solution that allows a larger and more focused working space on the page content without always showing the site header.

### Provide evidence this is a needed component

Multiple teams across the DDD are using a sticky site header in their services, such as: 
- Housing and homelessness
- SCSS case management
- SCSS Intake management
- Justice Surrogate digital 

### Describe alternatives you've considered

- Back to top button
- Alternative designs of the site header where only menu items are sticky, not entire header (taking up less of the screen when sticky)

### Do you have anything already created for this that we can use?

no

### Are you currently using this proposal inside your own service

None

### Are you able to assist to bring the feature to reality?

no

### Additional context

Issue created when Jeremy Payne inquired about how to make the site header (and footer) sticky using the design system components.

**Comment by ArakTaiRoth** [comment]
This can be tracked in this [story](https://goa-dio.atlassian.net/browse/DDIDS-1450)
