### ISSUE TITLE
Sandbox - FileUploader: The function Upload File doesn't work when we change `variant` or `maxFileSize` inside the Sandbox properties

### ISSUE THREAD

**Issue by vanessatran-ddi** [GovAlta/ui-components#1479]
## Acceptance Criteria:

When we first load the page, we can Choose File and upload as many files as we can. We also can delete/remove a file. 
However, when we change the variant to `button` for example, and click to upload a file again, we cannot see anything different. 

I think the issue is related to #1469 but I am not pretty sure. The below is the video recording:

https://github.com/GovAlta/ui-components/assets/120135417/4fbf2110-3b22-4830-bb58-290a44b550a3

**Comment by chrisolsen** [comment]
Everything seems to work as I would expect.


https://www.loom.com/share/572fec5dd3d34499b381db94f8f83cf8?sid=f0c6006f-4175-426e-91c2-ee0d20a70da0
