### ISSUE TITLE
File uploader

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#148]
# What is being submitted?
For "MVP" do “basic” document uploader

# Why are you submitting?
This component does not currently exist in the GOA design system. There are a number of teams that have versions of a document uploader designed and built. Please get in touch with ACO, IES, and the Justice Filing project to gain an understanding of what has been built/designed so far.

# Examples, links, and research

**Interaction** Behavior / Flow**

- Show default state
  - Option to select from file viewer (e.g. Finder)
  - Option to drag and drop
- Show hover state
- Show loading state
- By default, named as the file that the camera or user assigned 
- Snackbar
  - Success state
  - Error state
- Optional: add metadata 
- Naming: (options) 
  - Assign default name
  - Persist existing file name 
  - Rename
- Preview capability (e.g. default to open new tab to view in browser) 
  - Chrome vs safari vs firefox… 

**Context to define**
- Field label
- Instructions / file type or size restrictions
  - File limit
  - File type
- Button label “Drag and drop or click to upload
- Icons (standard Material icons) 
- File Table (to show uploaded files) or Card component 
  - Potential columns/metadata:
    - Doc type (category)
      - Image vs. doc. Vs pdf vs. video 
- File name 
- Date
- Size
- Name of user
- Link (to preview)  

 

**States**
- Default
- Hover state (or when something is dragged onto, but not yet dropped)
- Something to replace the wobble  
- Loading
- Uploaded file
- Success state or other indication
- Uploads table (document names, file types 
- Error message

**Functionality needed**
- Preview file
- Deleting
- Files uploaded into a table 
- From a mobile device
- Identify example documents (e.g. insurance)
- Restrict the name of the file (overwritten file name) 

**Considerations**
- Click to upload-Drag & drop to upload
- multiple file uploads at once
- upload of a predefined file type (out of scope)
- view/download uploaded file
- remove an uploaded file
- error state during upload
- disabled state
- validation error state where upload is required
- pending state for files where multiple are uploaded
- uploading progress
- processing state for files
- file type
- file size

**To do: (Mar 15)**

- How might we associate metadata (e.g. file description or other info) to a file after it’s been uploaded: (card view is for when the uploading is taking place)

  - Card component for an uploaded file. (includes additional functions and metadata if required)

  - This is for immediate feedback on an uploaded file.

    - “How do I know this is done/successful?” - Actual user

  - Card view: needs desktop and mobile (mobile would have more vertical stacking) 

  - Include an icon to show the file type – this is helpful for users to differentiate especially when there are multiple files being uploaded, and it helps prevent error. 

-Title of file vs. dynamic name of the file.

- Compact view of uploaded files (like a table), to be used during a review summary use case (for use anytime the uploaded files are being viewed by a reviewer) 

**Edit / Remove** 

- Edit functionality would be optional. This would be important if the upload includes other metadata. 

- Use Icons with labels

- Consider a simple uploader (minimal files required, minimal metadata), and a more complex uploader (multiple files and more metadata required)

  - Simple – better for mobile

  - Complex - ok for expert users, e.g. internal staff or long application processes 

**Examples**

https://component.gallery/components/file-upload/

# Anything else
- Add any other context or screenshots about the feature request here.

![Childrens Service-document uploader](https://user-images.githubusercontent.com/51723535/138527742-870b4dac-3c45-4633-bf36-a9120924cf81.png)
<img width="290" alt="Screen Shot 2021-03-05 at 10 11 31 AM" src="https://user-images.githubusercontent.com/51723535/138527743-ca590c13-bea8-42e1-9a0e-e2e898b1af8d.png">

**Comment by kyna-ceschini** [comment]
Working on this one
