### ISSUE TITLE
Sandbox: Code Snippet : Angular code cannot have a shorten />

### ISSUE THREAD

**Issue by vanessatran-ddi** [GovAlta/ui-components#1488]
## Acceptance Criteria:
If we copied the code like this: 
`<goa-chip content="Chip Text" error="true"/>`

Angular will have an error: 
![image](https://github.com/GovAlta/ui-components/assets/120135417/32f3d921-b5ab-4897-ad50-c0c71f33f36d)

**Comment by ArakTaiRoth** [comment]
Closing
