### ISSUE TITLE
Sandbox - Modal page - once open the modal, cannot scroll down the page

### ISSUE THREAD

**Issue by vanessatran-ddi** [GovAlta/ui-components#1489]
## Acceptance Criteria:
https://deploy-preview-46--abgov-ui-component-docs.netlify.app/components/modal
Step to reproduce: 
1. Scroll up and down using the mouse or keyboard, it is scrollable
2. Open the Modal inside the sandbox
3. Close the modal
4. Cannot scroll up and down the page anymore until we refresh. 

Seems that it is some issue with Sandbox. 
cc @chrisolsen

**Comment by ArakTaiRoth** [comment]
Closing
