### ISSUE TITLE
Sandbox: Add <slot> as one Sandbox property (very low priority)

### ISSUE THREAD

**Issue by vanessatran-ddi** [GovAlta/ui-components#1490]
# Info:
Right now we can't have slots in our Sandbox properties
![image](https://github.com/GovAlta/ui-components/assets/120135417/b6bfae2f-a5a0-433b-952a-230f19c92e4b)

## Acceptance Criteria

- Add text-based slot for the input component 
  -   leadingContent
  -   trailingContent

- Add text-based slot for the container component
  - title

**Comment by ArakTaiRoth** [comment]
@Spark450 Review what slots should be able to be updated

**Comment by Spark450** [comment]
@ArakTaiRoth I have added the only other text slot that I think would apply. Lets discuss in the next grooming session.

**Comment by Spark450** [comment]
Leading and trailing content have been removed from sandbox.
