### ISSUE TITLE
Dropdown inside Tab key binding Issues

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1494]
# Info
When a dropdown is inside a tab group the ability to select the dropdown item no longer works. View video below for a reference.

## More Info
This can't be replicated using a base input, dropdown, inside a base tab component. This might be something specific to the Sandbox, and needs to be investigated further as to what exactly is the cause.

## Acceptance Criteria
1. Indicate to QA how this can be tested
2. Tabbing and arrow keys should work for a Dropdown when it's inside a tab component

[Peek 2023-12-04 08-49.webm](https://github.com/GovAlta/ui-components/assets/41582/7f2579fc-0130-4652-b607-720878e6030b)

**Comment by ArakTaiRoth** [comment]
Closing as a duplicate of #1476
