### ISSUE TITLE
Dropdown menu doesn't work when set to a % value

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1496]
# Info

This was previously marked as fixed, it is not.

When you use a percentage for the width, the dropdown width doesn't actually get determined by the parent container

## Acceptance Criteria

1. If you offer percentage of width it should be based off of the parent container

**Comment by ArakTaiRoth** [comment]
Just adding a comment here for transparency. I spoke to Amar about this and when I went to show him the issue, I was unable to replicate the issue. So this might actually be fixed and was opened erroneously. Amar is going to investigate a little further, but I said if he can't replicate then move to Blocked and I will look at when I'm back in the office next week.
