### ISSUE TITLE
Layout grids

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#151]
# What is being submitted?
- A a responsive layout in a 1 column variant

# Why are you submitting?
- There are no existing guidelines in this area. These guidelines will help ensure that layouts will consider and be designed to the given standard.

# Examples, links, and research
A grid creates visual consistency between layouts while allowing flexibility across a wide variety of designs. https://material-ui.com/components/grid/

**Questions to consider**

- Does a grid include side navigation, or does the grid exist within the page content area only?

- Any best practices for switching between mobile/tablet/desktop?

- Do we want to recommend specific grid layouts, or do we want to leave that up to the team and instead suggest different ways to work with a grid once it is defined by the team?

- When is it ok to “break” the grid? 

- Do we want to define padding between grid columns?

- Do we need to explore any max-width breakpoints?

# Anything else
- Add any other context or screenshots about the feature request here.

**Comment by chris24mar10** [comment]
Here to help!

**Comment by Spark450** [comment]
- As per the discussion with the Front end design guild more complex page layouts are not a "need" at this time. The scope has been adjusted to include a single-column layout (Desktop, Tablet, Mobile) that includes a baseline grid to assist in the vertical spacing of page elements.

**Comment by Saul-png** [comment]
Here is the first draft : 

https://www.figma.com/file/iCcynUIy2FtgaVd8ryS3ju/%5BDS-151%5D-Layouts-grids?node-id=501%3A46
