### ISSUE TITLE
New Component: Dedicated GoA Time Field/Picker & Combined Date/Time Picker

### ISSUE THREAD

**Issue by jim-muirhead** [GovAlta/ui-components#1513]
### Is your feature request related to a problem? Please describe

We have several forms on the APC service that required the entry of a date and time for a particular event or deadline. Currently we store both the date & time as a single datapoint in our database as per our Dev team's preference. The browser native versions of a combined Date & Time input control vary widely between OS and Browser versions, making it difficult to create the best UX across all OS and Browser combinations. We'd like to adopt the new Date Picker control, but would have to change a bunch of data-related stuff to use separate Date Picker and Time Picker controls. And, of course, even if we used separate Date Picker and Time Picker controls, we wouldn't be able to have a consistent experience across these two separate controls without a GoA Time Picker that is similar to the Date Picker. Ideally we would also have a combined GoA Date & Time Picker control.

### Describe the solution you'd like

You can review a design we've worked up for a standalone Time Field/Picker control and a combined Date/Time Picker control that puts the existing GoA Date Picker together with our suggested Time Field/Picker control. Here are links to the designs in Figma:

- Time Input Field & Picker - Desktop
https://www.figma.com/file/ITHqvarhTtYal257Z4JzCB/Share-with-DS-Team?type=design&node-id=1012-62117&mode=design&t=1AszRejZWZEfynoL-4

- Time Input Field & Picker - Mobile
https://www.figma.com/file/ITHqvarhTtYal257Z4JzCB/Share-with-DS-Team?type=design&node-id=1058-224346&mode=design&t=1AszRejZWZEfynoL-4

- Date & Time Picker - Desktop
https://www.figma.com/file/ITHqvarhTtYal257Z4JzCB/Share-with-DS-Team?type=design&node-id=1068-23316&mode=design&t=1AszRejZWZEfynoL-4

- Date & Time Picker - Mobile
https://www.figma.com/file/ITHqvarhTtYal257Z4JzCB/Share-with-DS-Team?type=design&node-id=1071-58118&mode=design&t=1AszRejZWZEfynoL-4

### Provide evidence this is a needed component

During our recent Early Adopters testing program, we received feedback on both the difficulty in using some of the browser-native Time input fields.

### Describe alternatives you've considered

We are currently using the <goa-input type="date"> control which uses whatever the native browser date picker is.

![image](https://github.com/GovAlta/ui-components/assets/107221573/71eff9ed-2e06-4b37-ad7f-87541210fd0d)

### Do you have anything already created for this that we can use?

yes

### Are you currently using this proposal inside your own service

no

### Are you able to assist to bring the feature to reality?

yes

**Comment by ArakTaiRoth** [comment]
@Spark450 Create a story in Design

**Comment by Spark450** [comment]
@jim-muirhead We now have our design issues tracked in a different GitHub repo. This issue needs additional design and discovery work before we can start building a solution. I have linked the [new design issue](https://github.com/GovAlta/ui-components-design/issues/69) that we will use to track this work moving forward. I have linked this issue so we can gather the additional context present here.
