### ISSUE TITLE
Chip: Tap/Click Targets

### ISSUE THREAD

**Issue by jim-muirhead** [GovAlta/ui-components#1516]
### Is your feature request related to a problem? Please describe

As a convenience, especially on mobile, we’d like to use a tap/click on a filter chip to trigger the display of the configuration panel for that particular type of filter, saving a couple of taps/clicks for the user and a clear, direct relationship between the chip and the filters configuration panel.
This would require the ability to have 2 separate tap/click targets on a chip: 1) a target for action/event triggering, and 2) a target for deleting the chip.

Roadblock: Currently on mobile, the “delete chip” action is triggered by tapping anywhere on a chip.

### Describe the solution you'd like

The ability to have 2 separate tap/click targets on a chip: 1) a target for action/event triggering, and 2) a target for deleting the chip.
See the Figma mockup.
https://www.figma.com/file/ITHqvarhTtYal257Z4JzCB/Share-with-DS-Team?type=design&node-id=1074-14863&mode=design&t=f1GBRRudhd4O9aj8-4

### Do you have anything already created for this that we can use?

None

### Are you currently using this proposal inside your own service

None

### Are you able to assist to bring the feature to reality?

yes

**Comment by ArakTaiRoth** [comment]
Closing this story as it's already covered by #1333
