### ISSUE TITLE
Add outline to the badge

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1517]
## Background:
As part of the work to develop selectable containers and related work on the data table it was discovered that in order for the information badge to be clearly legible on zebra-striped rows it would need to have a darker grey border added. To keep the rest of the badges visually harmonious we will also apply similar treatments to the other status badges.

## Acceptance Criteria:
1. Create an additional design token: `--goa-color-greyscale-900` = `#474747`
    * Do this story with #1148 
    * This will require a deployment of design tokens
2. Add border CSS value:
    * Info: 1px solid var(--goa-color-greyscale-200)
    * Warning: 1px solid var (--goa-color-warning-dark)
    * Emergency: 1px solid var (--goa-color-emergency-dark)
    * Success: 1px solid var (--goa-color-success-dark)
    * Dark: 1px solid var (--goa-color-greyscale-700)
    * Midtone: 1px solid var (--goa-color-greyscale-900)
    * Light: 1px solid var (--goa-color-greyscale-200)

**Comment by twjeffery** [comment]
Additional colour tokens to add:
- #F8F8F8  (--goa-color-greyscale-50)
- #D7EDFF (--goa-color-interactive-background)

**Comment by Spark450** [comment]
Work to add the token values and the badge borders has been combined with #1613 will close issue.
