### ISSUE TITLE
[Bug]: description property on Checkbox always takes up space

### ISSUE THREAD

**Issue by francisagyapong-goa** [GovAlta/ui-components#1519]
### Describe the bug

The `description` property for the Checkbox component always takes up the space, even if no description is provided.

![image](https://github.com/GovAlta/ui-components/assets/94571832/a312c39d-0591-4e3e-99f3-7f058367438b)

### To Reproduce

This can be seen in the basic example in the story book: https://ui-components.alberta.ca/iframe.html?viewMode=docs&id=components-checkbox--basic#basic

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge, Mobile Android, Mobile iOS

## Acceptance Criteria
1. There should be no space below the checkbox if the `description` property isn't provided.

**Comment by ArakTaiRoth** [comment]
This is still an issue, even after the introduction of #1566

**Comment by Spark450** [comment]
Through discussion with the team, it was determined that this spacing must be maintained to ensure the default spacing between checkboxes when placed in a list. Working on this issue uncovered another [spacing issue on the checkbox when the description is present](https://github.com/GovAlta/ui-components/issues/1771)

**Comment by francisagyapong-goa** [comment]
Sorry for commenting on a closed issue, I missed your comment @Spark450.
I feel like this is something that should be left to the users of the component or at the very least an attribute provided to remove the extra space if it's not needed. As it is now, it forces an extra padding in cases where you have a standalone checkbox - example attached here:
![image](https://github.com/GovAlta/ui-components/assets/94571832/d1602e29-8048-4dae-8c5e-8fc7619035d7)
![image](https://github.com/GovAlta/ui-components/assets/94571832/36bcbf3f-b36a-41f4-b484-3994a2bc58fd)
