### ISSUE TITLE
Tooltip content is partially transparent

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1522]
Which makes things harder to read if it is overlaying other content.

Is seen when content appears below the icon, but not above.

![image](https://github.com/GovAlta/ui-components/assets/41582/6d67bc77-e7e7-4355-bab4-4621e0db70d2)
![image](https://github.com/GovAlta/ui-components/assets/41582/dc6c12ce-9bff-4fa5-b417-c73b04fa7eff)

**Comment by bdfranck** [comment]
I thought I couldn't replicate this issue until I realized that it isn't a transparency issue. It looks like the dropdown label is being rendered above the tooltip.


Here's a tooltip below the dropdown...
![Image](https://github.com/GovAlta/ui-components/assets/1479091/d54898eb-d7ad-4e04-8f06-a9eb1216acab)

And here's a tooltip above the dropdown...
![Image](https://github.com/GovAlta/ui-components/assets/1479091/e5232702-3044-43a4-ac7e-36fc0c2dd51e)

Ahhh, the joys of element stacking order. 🤪

**Comment by bdfranck** [comment]
And here's how it looks when I change `.tooltip-text` z-index from 1 to 2...
![Image](https://github.com/GovAlta/ui-components/assets/1479091/02c323fd-2807-427d-971b-df211b9e780f)

I'll need to compare it to the stacking order of other elements with overlays before choosing a final z-index.
