### ISSUE TITLE
Tooltip component to display content more than one line in new line (to display filed value in line by line)

### ISSUE THREAD

**Issue by YogeshPatelGoa** [GovAlta/ui-components#1524]
### Is your feature request related to a problem? Please describe

Tooltip component currently can't display text line by line (ie. no HTML content)

### Describe the solution you'd like

![image](https://github.com/GovAlta/ui-components/assets/124069025/84428a29-a606-419a-87ce-ba277f7bdaf6)

**Comment by ArakTaiRoth** [comment]
Closing as this is duplicated by #1547
