### ISSUE TITLE
Pagination: component breaks if you change items per page

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1529]
# Info

If you look at our current `Items per page` example for the Pagination component and actually use it. You'll notice that if you're on the last page, and then change the # of items to show per page, the component soft breaks. As in the # of pages goes down, but the page you're on doesn't change, so no items are actually shown because you're now on a page that doesn't exist.

## Other Info

This was recorded back when we had this example in Storybook. We don't have this example at this moment, please refer to #1680 for the code for an example.

## Acceptance Criteria:
1. Current page should change to first page if items per page is changed

**Comment by dustin-nielsen-goa** [comment]
fdsfsd

**Comment by ArakTaiRoth** [comment]
Review this story once #1680 is finished, this story might be a non-issue, if the issue is just documentation only.

**Comment by syedszeeshan** [comment]
PR #1997 should fix this issue also.
