### ISSUE TITLE
Contextual Component Examples

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1542]
### Describe the problem

As a UI/UX designer,
I want contextual examples for each component,
So that I can see how components are used in real-world contexts.

## Acceptance criteria

- [Designs are a WIP](https://www.figma.com/file/aeIJGExcpx9ecqnIVwImi1/Component-examples?type=design&node-id=521%3A254098&mode=design&t=LU0kJzgHM2b0M3RE-1), please connect with @twjeffery to verify which are ready to be built

- [x] Accordion
- [x] Container
- [ ] Details (Doing)
- [ ] Popover
- [ ] Skeleton loading
- [ ] Table
- [ ] Badge
- [ ] Callout
- [ ] Modal
- [ ] Notification Banner
- [ ] Progress indicator
- [ ] Tooltip
- [ ] Button 
- [ ] Button group
- [ ] Checkbox
- [ ] Chip
- [ ] Date picker
- [ ] Dropdown
- [ ] File uploader
- [ ] Icon button
- [ ] Radio
- [ ] Text area
- [ ] Text field
- [ ] Form stepper
- [ ] Microsite header
- [ ] Pagination
- [ ] Footer
- [ ] Header
- [ ] Tabs

**Comment by ArakTaiRoth** [comment]
Closing, as we are making specific stories for each component now to better track the work
