### ISSUE TITLE
[Documentation]: Dynamic Browser Compatibility Documentation

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1545]
### Describe the problem

As a developer,
I want the browser compatibility documentation to show actual version numbers of the latest and previous versions dynamically,
So that I have up-to-date information without manual updates, 

## Acceptance criteria
- The [browser version support container](https://deploy-preview-61--abgov-ui-component-docs.netlify.app/get-started/developers/browsers) should be updated to show the latest version and version -1 (in numeric values)
- This information should be able to chance dynamically so that it does not become out of date as browser versions are updated.
- This information is to be displayed in the Browser and OS table.

**Comment by ArakTaiRoth** [comment]
Closing, as is no longer relevant
