### ISSUE TITLE
[Feature Request]: Breadcrumb component

### ISSUE THREAD

**Issue by MikeS700** [GovAlta/ui-components#1548]
### Is your feature request related to a problem? Please describe

Currently in the Early Childhood Development System portal (Child Care Portal), there are a could different services (accessed through the sidenav) which feature breadcrumbing on their respective pages. Each breadcrumb patter is different. We will soon want all the services in this portal to utilize a consistent breadcrumb component/pattern. 

### Describe the solution you'd like

- Would like to see a GoA breadcrumb component which can go down to at least 5 to 6 page levels
- Works on desktop/tablet and mobile breakpoints
- Is fully accessible
- Accounts for position/padding in relation to page templates or this first item of content below the breadcrumb on a page
- All states for the active links and active page in the breadcrumb
- Some guidelines around breadcrumb label character length and recommended naming convention if possible (brevity and matching the page title and considerate of the url if possible)

### Provide evidence this is a needed component

Currently 3 of 6 Child Care Services in the Early Childhood Development System portal utilize breadcrumbing and all use a different pattern treatment. All services in the portal will use breadcrumbing in early 2024. Consistency is key as this is a single portal for our external users.

The Design System team is already exploring breadcrumb component for their Design System website.
[https://www.figma.com/file/Vw1LNUBsNeFkToPTWqXAzR/Component---Breadcrumb?type=design&node-id=1401-3285&mode=design&t=7I1OkZM3WExILE2j-4](url)
<img width="348" alt="image" src="https://github.com/GovAlta/ui-components/assets/142626529/d4b61072-9696-4efb-b16c-ed11cbb36f95">
### 

### Describe alternatives you've considered

Good article which may provide helpful when mapping out the component and it's guidelines: https://www.smashingmagazine.com/2022/04/breadcrumbs-ux-design/

### Do you have anything already created for this that we can use?

yes

### Are you currently using this proposal inside your own service

yes

### Are you able to assist to bring the feature to reality?

yes

### Additional context

Here are some live breadcrumb examples from ECDS portal
<img width="1148" alt="image" src="https://github.com/GovAlta/ui-components/assets/142626529/dfbef35b-24d5-4e5e-adca-3baebf0a6120">

**Comment by MikeS700** [comment]
Hi @ArakTaiRoth do you need more context/info from me? Cheers

**Comment by twjeffery** [comment]
Land Titles Office has a component designed and in development for this:
### Figma 
[Design guidelines](https://www.figma.com/file/zTGuuJIkkMVwWtx9layq4o/LTO---Unified-Site---Design-Guidelines?type=design&node-id=3320-62&mode=design&t=n0bXPUigCMINpz7l-0)
[Development blueprint](https://www.figma.com/file/orl1q3GpEe4j4lHfjfT3VH/LTO---Unified-Site---Production?type=design&node-id=1160-18817&mode=design&t=n0bXPUigCMINpz7l-0)
Service designer: @garnison-goa

### Development
Developer: Daryl Chiew

**Comment by ArakTaiRoth** [comment]
@Spark450 Gather the relevant info and convert into a design issue

**Comment by Spark450** [comment]
This needs to have a complete design definition before it can be worked on in development, see [Jira Issue](https://goa-dio.atlassian.net/browse/DDIDS-1240?atlOrigin=eyJpIjoiNGEzMjkyYjNiMTRmNDNhOGE5Y2I5NDZlYWMxZTM0M2EiLCJwIjoiaiJ9) to follow its progress. A new issue will be created once the design work has been completed.
