### ISSUE TITLE
[Bug]: Basic page layout example and code snippit not showing up

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1554]
### Describe the bug

- When viewing the basic page layout page on the documentation site, I noticed that the example and code in the "snippet" area are missing
<img width="1778" alt="Screen Shot 2024-01-05 at 9 23 31 AM" src="https://github.com/GovAlta/ui-components/assets/51723535/54a6511f-d43c-4373-b1a5-b2342c33ec33">

### To Reproduce

Go to [this page](https://design.alberta.ca/patterns)

### What browsers are you seeing the problem on?

Chrome

### Additional context

Chrome Version 120.0.6099.109 

Expected content:
![layout screenshot](https://github.com/GovAlta/ui-components/assets/51723535/a2ca9d35-b277-43f9-aa39-19b851ddcf85)

**Comment by ArakTaiRoth** [comment]
Closing as this was fixed
