### ISSUE TITLE
Flyout / Slideout / Blade / Drawer

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#157]
# What is being submitted?
Similar to a modal, an expansion panel slides in from the side of the screen and overlays all or a portion of a page.

# Why are you submitting?
- What evidence do you have that it’s needed by multiple services across government?
- What evidence do you have that it meets the needs of the users of those services?
- Have you checked that it doesn’t already exist in the DIO Design System?

# Examples, links, and research

**Questions to consider**
- How does an expansion panel differ from a modal?
  - Do we need to document when to use one or another?
- How does an expansion panel differ from the Side Navigation?
  - Refer to:  
- Should an overlay display when a panel is expanded?
- What does the button to open a panel look like?
- Is it possible to have multiple panels open at the same time?
- How do you handle multiple panels on the same page?
- Any recommendations for panel states persisting as you navigate between pages?

# Anything else
- Add any other context or screenshots about the feature request here.

**Comment by scurvydog** [comment]
Oh, hai! This is my thing that I'm doing
