### ISSUE TITLE
Hero Banner: Angular sandbox code not accurate

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1571]
# Info

Currently in the Sandbox code for the Hero Banner component, it lists the `actions` slot as `goa-hero-banner-actions` or `GoAHeroBanner Actions`. That component doesn't actually exist.

## Acceptance Criteria

1. Given that we don't include slot properties in any of our other sandbox generated code, remove the actions from this sandbox, so it's not even given in the code
2. Include the react and angular properties for the `actions` slot
3. Create an example showing the `actions` slot in use

**Comment by ArakTaiRoth** [comment]
@chrisolsen Review story and flesh out acceptance criteria

**Comment by ArakTaiRoth** [comment]
@ArakTaiRoth Re-write this story to include removal of slot content in sandbox, addition of slot property, and addition of example
