### ISSUE TITLE
Document Items per Page (Pagination) example

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1576]
# Info

In our old storybook documentation we have an example for the Pagination component that details how to add an "Items per Page" option. We need to have that documented in our new website.

## Acceptance Criteria:

1. We have documentation on the Pagination component for how to add an "Items per Page" option

![image](https://github.com/GovAlta/ui-components/assets/1081991/66871c29-2cc6-45c3-8f37-7817cddaff52)

**Comment by ArakTaiRoth** [comment]
@twjeffery Can you add this example to #1542 and once done, close this story

**Comment by twjeffery** [comment]
added example for setting number of items per page to be built out on website to story #1542
