### ISSUE TITLE
Website: Page to show Angular/React/Vue versions our components work with

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1580]
# Info

A requested feature on our website, and something we get questions for semi-regularly, is what versions of Angular/React/Vue do we actually support. This information can't be found anywhere, and in all honesty, I'm also kind of unsure about and can't give a clear answer on. I can only say what version of these frameworks our template apps are using.

## Acceptance Criteria:

1. This would likely require testing on various versions of the different frameworks to see what we support.
2. We might need a way to display this on a per component basis. For example, if we introduce a new component as Angular 17 is out, are we also going to expect ourselves to make sure it works on Angular 15, or 14, what about 16?
3. This needs more conversation to decide what we actually want to do with this, and this also needs a design.

**Comment by ArakTaiRoth** [comment]
@twjeffery Need a design

**Comment by ArakTaiRoth** [comment]
@Spark450 Make a story on the design board to create this page

**Comment by Spark450** [comment]
Created an issue in the design board, we will re-create a [new issue](https://goa-dio.atlassian.net/browse/DDIDS-1451?atlOrigin=eyJpIjoiMWZiM2Y3YmY3MjVlNDBkOGIyM2FmZDBlOGNhMDVmOGIiLCJwIjoiaiJ9) on that issues completion.
