### ISSUE TITLE
Invalid html nesting

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1589]
https://design.alberta.ca/support

Can't have divs in ps. Proper hx tags should be used for titles ex "Developers"

![image](https://github.com/GovAlta/ui-components/assets/41582/c20c88ea-c2a1-47ce-aa9d-c4bec0744474)

**Comment by syedszeeshan** [comment]
seems to have been fixed already.

**Comment by ArakTaiRoth** [comment]
Closing this issue as it's no longer an issue
