### ISSUE TITLE
[Bug]: popover width creating larger menu items

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1590]
### Describe the bug

The size of the popover is dictating the width of the menu item. It should not. The menu item should stay the size of its label, and the popover should show below with it's own size.

### To Reproduce

https://design.alberta.ca/components/header
www.design.alberta.ca

<img width="977" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/a10049fc-8d61-4ec2-a55a-2b7a287c07ed">
<img width="845" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/339693ec-3f01-4168-ab54-e5f38e597e0e">

### Additional context

This seems to have appeared recently.

**Comment by ArakTaiRoth** [comment]
Closing this story as I can no longer duplicate the issue
