### ISSUE TITLE
Bug: Not enough padding on accordion when heading text wraps to second line

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1591]
### Describe the bug

When the heading text is long and wraps to a second line, there is not enough padding below. Happens on both small and medium heading sizes.

![image](https://github.com/GovAlta/ui-components/assets/82968683/22e083b8-80c2-4879-9de5-7f35d2e98701)

This happens only on the desktop size, it is fine on mobile size. 

### To Reproduce

Can see in sandbox on [design system website](https://deploy-preview-106--abgov-ui-component-docs.netlify.app/components/accordion)

Input heading text that is long enough to wrap to a second line.

**Comment by bdfranck** [comment]
I've created a PR with a potential fix:
https://github.com/GovAlta/ui-components/pull/1764
