### ISSUE TITLE
Bug: Extra space seen in accordion when badge and no secondary text

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1592]
### Describe the bug

There is extra space left from the secondary text when there is no secondary text present. 

![image](https://github.com/GovAlta/ui-components/assets/82968683/931163a6-a885-42fe-9ee5-955715d2d64a)

This causes the space between the heading text and the badge to be too much. 

### To Reproduce

Include badge on accordion header. Space between badge and heading text is too wide. Secondary text span is showing up and moving the badge over.

**Comment by bdfranck** [comment]
I've created a PR of a potential fix: https://github.com/GovAlta/ui-components/pull/1765
