### ISSUE TITLE
Ensure `testId` attribute exists for all React components

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1593]
# Info

We use the `testId` attribute as an unofficial (undocumented) way of testing our components. Considering we're ramping up our testing efforts with both unit tests and now automated tests. We should ensure this attribute is available on all of our components.

## Acceptance Criteria:

1. `testId` needs to be added to the following components:
    * Accordion
    * Calendar
    * DatePicker
    * Details
    * FileUploadCard
    * FileUploadInput
    * FooterMetaSection
    * SideMenu
    * SideMenuGroup
    * SideMenuHeading
    * Tabs
    * AppHeaderMenu
2. Ensure camel casing is correct where it is used, should be `testId`

**Comment by Spark450** [comment]
Hey @ArakTaiRoth I wonder if @lizhuomeng71 be able to help us with this?
