### ISSUE TITLE
Create a React testing helper library that makes it easier to test the web components

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1594]
As an example, to click a button within unit tests the following is needed.

```
import { fireEvent } from "testing-library/react";

const button = container.querySelector("...");
fireEvent(button, new CustomEvent("_click"))  // requires internal knowledge to how things work
await waitFor(() => {
  // some tests
})
```

Ideally below is what would be done
```
import { fireEvent as goaFireEvent } from "@abgov/react-testing-library";

const button = container.querySelector("...");
goaFireEvent.click(button)
await waitFor(() => {
  // some tests
})
```

**Comment by Spark450** [comment]
@ArakTaiRoth  should developers be using unit tests to test their product functionality? Need to touch base with the director of development to discuss the practice.

Can we find out if this is a common practice for React teams?

**Comment by Spark450** [comment]
Priority will be effected by how common this practice is with React product teams

**Comment by ArakTaiRoth** [comment]
If we don't find enough teams actually doing this, we can close. It isn't recommended practice, and this could be alleviated with just proper documentation.

**Comment by ArakTaiRoth** [comment]
Ignoring this as it is not best practice
