### ISSUE TITLE
[Bug]: Textarea doesn't fire value changed event in Angular until after clicking outside of the textarea

### ISSUE THREAD

**Issue by mtycholaz** [GovAlta/ui-components#1597]
### Describe the bug

When using reactive forms in Angular, the text area control doesn't fire the value changed event until after a user clicks outside of the textarea.

Expected behavior should match the textbox component. As a user types, it should fire the value changed events.

### Provide Code

Template for component

````javascript
<div [formGroup]="form">
  <goa-form-item>
    <goa-textarea goaValue formControlName="textarea"></goa-textarea>
  </goa-form-item>
  <goa-form-item>
    <goa-input goaValue formControlName="input"></goa-input>
  </goa-form-item>
  Textarea Value: {{ form.controls["textarea"].value | json }}
  Input Value: {{ form.controls["input"].value | json }}
</div>
````

Minimal code for component

````javascript
form = new FormGroup({
  textarea: new FormControl(),
  input: new FormControl(),
})
````

### To Reproduce

Type into the textarea. Notice how it doesn't update the output until after you click out of the box.
Type into the textbox. Notice how it updates after each key

### What browsers are you seeing the problem on?

Chrome, Edge

**Comment by ArakTaiRoth** [comment]
@ArakTaiRoth Look into if this affects the counter in the textarea

**Comment by ArakTaiRoth** [comment]
@ArakTaiRoth Test to see functionality in React
