### ISSUE TITLE
Bug: Text heading in containers break when wrapping

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1607]
### Describe the bug

When there is not enough space for the text heading in a container, and it wraps to a second line, the container heading should expand to fit the text. It does not, and it flows out of the heading. 

<img width="609" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/a1520607-8265-4755-beac-16eec8d2e5c2">

### To Reproduce

Shown in example on our design system website: https://design.alberta.ca/components/container

Put text in title slot, long enough that it will wrap to a second line.

**Comment by ArakTaiRoth** [comment]
@twjeffery What about line height when the text wraps? There appears to be a large gap between the 2 lines of text.

**Comment by twjeffery** [comment]
> @twjeffery What about line height when the text wraps? There appears to be a large gap between the 2 lines of text.

It does look slightly larger line height than design. Heading text in container should use `--goa-typography-heading-s` which includes line height. 

<img width="591" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/d212b229-c913-4e0c-af1e-ac71fe195a9f">

**Comment by bdfranck** [comment]
Hmmm, it looks like the `max-height` is causing the issue.:

https://github.com/GovAlta/ui-components/blob/644b170ed5d49073746763dd26ab0d8af39f8387/libs/web-components/src/components/container/Container.svelte#L227C2-L231C4

I'll spend a bit of time exploring if the `max-height` is used for anything and if it's safe to remove.

**Comment by bdfranck** [comment]
I'm comparing it with all the relevant Figma component states:
https://www.figma.com/file/pLgyXAu99HhW6uo2VZthep/SCSS---Case-Management?type=design&node-id=60508%3A274361&mode=design&t=KaA6qupfQMb6yeuI-1

**Comment by bdfranck** [comment]
Tested on the latest version of Edge...
![image](https://github.com/GovAlta/ui-components/assets/1479091/0922301a-5d83-4510-bfb3-38e00c57c76f)

**Comment by bdfranck** [comment]
I started testing on Firefox and I noticed that there isn't a gap between the title and the actions. I'll fix that.
![image](https://github.com/GovAlta/ui-components/assets/1479091/9988a45e-a963-45f0-bf85-22abe3237edf)
