### ISSUE TITLE
Hero banner is being centered

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1640]
![image](https://github.com/GovAlta/ui-components/assets/41582/653dae9d-1f90-44b5-a605-58872122d65a)

## Acceptance Criteria

1. `align-items: center` should be removed
2. Make sure you ask @twjeffery to review once the fix is in
![image](https://github.com/GovAlta/ui-components/assets/41582/7c263ea4-c0f0-430b-8dca-8be086e8ade7)

**Comment by ArakTaiRoth** [comment]
Make sure you ask @twjeffery to review once the fix is in
