### ISSUE TITLE
[Bug]: Layout on design system website is breaking at certain viewport widths

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1653]
### Describe the bug

Layout does not respond correctly and creates horizontal scroll between approx 824px and 624px. It should respond to fill the space available and not have horizontal scroll. 

### Examples of this happening:

https://github.com/GovAlta/ui-components/assets/82968683/df0f022f-a9de-442e-8181-8e58635b16bf

**Component pages**

<img width="754" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/c2c66d50-1963-4acf-adbb-62d5c4ea83b4">
<img width="623" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/b8d29cda-8f84-4a16-b83f-682f75488c39">

**All component page**

<img width="882" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/24dc37c0-2816-48f4-8392-ba02c272896f">
<img width="634" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/acdb7006-9582-4499-8d84-05fc51eccc9d">

**Layout/patterns page**

<img width="622" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/4879938c-0995-4eef-96dd-516d51b5d70d">

**Content pages**

<img width="650" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/2d07b85f-540e-4d29-986e-297158d111ec">

---
It seems to be responding correctly on the styles pages, get started pages, and home page.

### To Reproduce

1. Go to our website: https://design.alberta.ca/
2. navigate to any of the above pages
3. change width of screen
4. see horizontal scroll

### This may be related to an issue with the header not responding correctly
- Menu shifted over

<img width="843" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/97d86a49-33b5-42bb-b06e-f6930330f415">

- Menu overlapping off right side. (too many nav items before breakpoint?)

<img width="843" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/879cc58b-6036-4af8-8801-29d9f7015303">

- Also happening on in page side navigation

<img width="1112" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/5a013f4d-6a80-4bcd-b412-c9a9810d46ef">

**Comment by ArakTaiRoth** [comment]
@ArakTaiRoth Re-review once we release

**Comment by ArakTaiRoth** [comment]
@twjeffery Go over this bug and modify based on what current needs are after the recent releases

**Comment by twjeffery** [comment]
Most of the layout bugs above are fixed. 

**There are still some outstanding issues with:** 
- the margin on the header and microsite header at various breakpoints
- some of the page content in the styles and content sections.

[Review captured in markup.io here](https://app.markup.io/invite/accept/ZlYj_c5K)

**Comment by twjeffery** [comment]
closed and created #1803 to cover updated issues
