### ISSUE TITLE
Menu - side menu

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#166]
# What is being submitted?
- A Side Nav adds secondary content alongside primary content on full-screen applications. This can be preserved for navigation on some applications, but this pattern is not always followed across different design systems.

[example 1](https://component.gallery/components/navigation/)

[example 2](https://material.angular.io/components/sidenav/overview)

# Why are you submitting?
- What evidence do you have that it’s needed by multiple services across government?
- What evidence do you have that it meets the needs of the users of those services?
- Have you checked that it doesn’t already exist in the DIO Design System?

# Examples, links, and research
**Questions to consider**
- Are mobile-specific menus in scope for this task?
- Should side navigation be preserved for navigation only, or does it make sense to include other content here?
  - Note: It might be important to distinguish this component from   #157.  
- Should we recommend right or left alignment?
- Are there ever instances where it is appropriate to use two side navs? (left and right?)
- Are there expanding sections or sub-side-nav items? (Is this in scope?)

**Out of scope**
- Side nav step counter. This is used on some projects, but let's strip it out into a seperate card.
- What should not be included in this task?
- What should be captured as a separate subsequent task?

**Considerations**
- Have other designers built similar components?
- Do examples currently exist in the DIO design system?
- Do examples currently exist in the GOA design system?

# Anything else
- Add any other context or screenshots about the feature request here.
![Linnea Screenshot](https://user-images.githubusercontent.com/51723535/138736248-e9c80844-bb00-417e-8d98-2b885ef03079.png)
<img width="646" alt="Screen Shot 2021-07-08 at 4 26 05 PM" src="https://user-images.githubusercontent.com/51723535/138736254-19c39677-5e74-4cc7-a5c2-caa9f67cb513.png">
<img width="1639" alt="Screen Shot 2021-07-08 at 10 13 35 AM" src="https://user-images.githubusercontent.com/51723535/138736257-49f4f875-ada9-4a4f-9f60-7086181cc9e8.png">
<img width="1639" alt="Screen Shot 2021-07-08 at 10 15 31 AM" src="https://user-images.githubusercontent.com/51723535/138736259-48fef92b-8cb2-4af2-914c-f55d76342603.png">
<img width="719" alt="Screen Shot 2021-07-08 at 10 31 28 AM" src="https://user-images.githubusercontent.com/51723535/138736263-2de4d318-6571-4f2e-8e04-fb764335f31d.png">
![Screen Shot 2021-07-14 at 12 53 43 PM](https://user-images.githubusercontent.com/51723535/138736266-e02745bd-4e2b-40d1-be0d-3c07a5e3896d.png)

**Comment by DaveVanVliet** [comment]
I am working on this one!
