### ISSUE TITLE
All: Add Localization

### ISSUE THREAD

**Issue by Frenchtoast0** [GovAlta/ui-components#1661]
### Is your feature request related to a problem? Please describe

The application I'm working on requires localization to be implemented.  I would like to use this library, however the text in the components is all hardcoded in English.

### Describe the solution you'd like

I would like all the strings of the application to be exposed as properties so that localized strings can be injected in their place.  Or else some other way to localize the strings in the UI components.  The primary component I'm concerned with at the moment is the file input component.

### Provide evidence this is a needed component

Canada is a multilingual country, many people need to use these UI components that don't understand English well.  Government services especially need to be accessible to individuals whose first language isn't English.

### Describe alternatives you've considered

Creating the components from scratch with localization functionality built-in which is very time consuming.  Forking the library in an attempt to inject localization.

### Do you have anything already created for this that we can use?

no

### Are you currently using this proposal inside your own service

yes

### Are you able to assist to bring the feature to reality?

no

**Comment by Spark450** [comment]
@Frenchtoast0, can we set up a short meeting to discuss some of the specific requirements?

Feel free to reach out on Slack and I will get something set up for us.

**Comment by ArakTaiRoth** [comment]
Closing. Will re-open if priorities change.
