### ISSUE TITLE
Data Table

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#168]
**Considerations**
Considerations
- Buttons- inline(action buttons), “add new” line items
- Status (incomplete, in-progress, denied…etc)
- Read/Edit mode (Dropdown, Text…. etc)
- Collapsable/ Expandable (Accordion)
- Sub-sections

# Anything else
- Add any other context or screenshots about the feature request here.
<img width="769" alt="Screen Shot 2021-05-05 at 9 51 50 AM" src="https://user-images.githubusercontent.com/51723535/138737711-ec1e6bee-efae-4dd3-8b2d-083667441ac7.png">
<img width="728" alt="Screen Shot 2021-05-05 at 9 52 12 AM" src="https://user-images.githubusercontent.com/51723535/138737718-f6c6b499-6e82-48cc-808c-f981cba5ee7a.png">
<img width="765" alt="Screen Shot 2021-05-05 at 9 52 36 AM" src="https://user-images.githubusercontent.com/51723535/138737721-c9208d99-01c3-4815-af6b-b31a9ae7996e.png">

**Comment by linnealapp** [comment]
Linnea, Ashifa & Graeme are working on this one!
