### ISSUE TITLE
[Bug]: Not enough margin space when the GoAInput is focused.

### ISSUE THREAD

**Issue by solittlework** [GovAlta/ui-components#1696]
### Describe the bug

The GoAInput is expected to included all of the space, including the extra margin extra yellow border space introduced during the on focus model.

### Provide Code

import React, { useState } from 'react';
import { GoAFormStepper, GoAFormStep, GoAPages, GoAInput } from '@abgov/react-components-new';

const LandingPage = (): JSX.Element => {
  return (
    <>
      <div>
        <GoAInput value="Test" name="test" onChange={() => {}}></GoAInput>
      </div>
    </>
  );
};

export default LandingPage;

### To Reproduce

* focus on the GoAInput
![Screenshot 2024-03-07 at 9 34 27 AM](https://github.com/GovAlta/ui-components/assets/8821979/b9664899-0b4e-44fb-81a5-9ff918f6c86b)

**Comment by ArakTaiRoth** [comment]
Closing, as margin can be added to the Input component in cases like this using built in properties.
