### ISSUE TITLE
Dropdown: width doesn't match when specifying width in the component

### ISSUE THREAD

**Issue by Marcelocarreongoa** [GovAlta/ui-components#1702]
### Describe the bug

When specifying the width in the component code, we find misalignment issues on our dropdown menus in the PDD Case Management application.

Actual: The UI for the downtown fields is expanding to the right. This is also causing misalignment for the fields to the right of the drop-down (in this case: the SIN field)

Also, replicable for City/town dropdown options under Home and Mailing Address

Expected: The UI for the downtown fields should match the width of the dropdown component field.

### Provide Code

```javascript
<goa-dropdown
  name="city"
  filterable="true"
  [error]="cityErr"
  goaValue
  width="100%"
  [formControl]="addressForm.controls.city"
  [value]="addressForm.controls.city.value"
>
    <goa-dropdown-item
      *ngFor="let city of cityList"
      [value]="city._id"
      [label]="city.name">
    </goa-dropdown-item>
</goa-dropdown>
```
![e5ac9919-fdb0-4a55-bef5-4e69e4114d40](https://github.com/GovAlta/ui-components/assets/163068636/eb36c3fb-6f6a-41f5-9bf7-67ca9e348ff5)
![079b19f2-fecc-418e-a810-83eab3c651f7](https://github.com/GovAlta/ui-components/assets/163068636/93ad2cce-4913-4b92-8bdb-a64a2ce7a18a)

### To Reproduce

Steps to replicate: 

1. Launch the application  https://csspddcm.test.alberta.ca/
2. Navigate to the Edit Personal Info page
3. Select any dropdown fields

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

**Comment by ArakTaiRoth** [comment]
Confirmed with Hassan that this is no longer an issue, closing
