### ISSUE TITLE
Bug: Inconsistent behaviour between input components

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1703]
# Info

Reported by Francis Agyapong

Our Input and Textarea component has a `keyup` and a `change` event. Both fire on the same thing though, `onKeyUp`. Whereas with our Radio, and Checkbox components, the `change` event fires `onChange` instead of `onKeyUp`.

With our input component, this potentially creates an issue where validation occurs even if a user does nothing in an input and just tabs through it. But really, the bigger issue is the inconsistency, a user can tab through a whole form and only be alerted to errors in the Input component.

## Acceptance Criteria:

1. Make the behaviour consistent for `change` events between all our components. (probably modify `change` to fire `onChange`)

**Comment by syedszeeshan** [comment]
Discussed with @chrisolsen , the change may result in "breaking change", so we might want to defer this till our major release?

**Comment by ArakTaiRoth** [comment]
Closing this issue as it's no longer an issue. The instigating issue of this has been fixed previously according to Francis.
