### ISSUE TITLE
App Header: long heading cause to horizontal scrolling

### ISSUE THREAD

**Issue by pomeras** [GovAlta/ui-components#1706]
# Info

Reported by Simon Pomeransky

If a combination of the title and the menu items are too long (just the title in mobile view), it forces horizontal scrolling:
![Image](https://github.com/GovAlta/ui-components/assets/1081991/0e7e82ef-383f-4aa4-a14e-3e1c6941eeb0)

## Provide Code

This only produces the issue in a mobile view:
```javascript
<goa-app-header heading="Evacuation 2024 - 2024 Alberta Spring Wildfires" url="/">
  <a class="interactive">Simon Pomeransky</a>
  <a class="interactive" href="https://localhost:44318/api/auth/logout?callback=http://localhost:3000/loggedOut">Sign Out</a>
</goa-app-header>
```

## Acceptance Criteria

1. The title wraps if it's too long and bumps up into the menu items

**Comment by ArakTaiRoth** [comment]
@twjeffery Need designs for wrapped title

**Comment by ArakTaiRoth** [comment]
@Spark450 Talk to someone about content

**Comment by Spark450** [comment]
Discussed this with the UX designer from the team (Sam D) They have done work to simplify the name of the app that they are currently working on. In June they will be launching a platform that will allow other programs/services to customize and launch their own portals, so we won’t have control over the service names at that point.

Ideally we would have a solution in place at that point in the case of a service team including a long name that would need to "wrap"

Will maintain the priority of this issue at "Medium"
