### ISSUE TITLE
App Header Menu: menu width

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1713]
### Describe the bug

Menu width is currently hard coded at 256px. 

---
### Menu item width should:
- hug the smallest menu item (length of content). 
- **Min width:** 8rem
- **Max width:** 16rem 

### To Reproduce

Use drop down menu item on show header.

**Comment by lizhuomeng71** [comment]
issue is verified on react and angular


![image](https://github.com/GovAlta/ui-components/assets/7528736/7042fbc9-c6b3-4c49-a76c-7ad31e2395cd)
![image](https://github.com/GovAlta/ui-components/assets/7528736/e711d9f2-facd-4b51-9b02-2bc694cf37e2)
