### ISSUE TITLE
File Upload Input: "dropzone" helper text content

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1716]
### Describe the bug

- The default helper text in the drop zone "Maximum file size is xMB." includes a period at the end of the statement.

### To Reproduce

Issue is viewable on [DS website](https://design.alberta.ca/components/file-uploader)

## Acceptance Criteria

1. Remove `.` from end of helper text in File Upload

**Comment by twjeffery** [comment]
What if we add additional helper text, like this: 
<img width="1013" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/e0b57a00-4937-454d-8505-3f40f715d8cb">

And keep the maximum file size as is? File size is a specific communication need for file upload.

**Comment by ArakTaiRoth** [comment]
@Spark450 Go back and talk to Graham to get specific use case
