### ISSUE TITLE
[Bug]: two logos showing at mid breakpoint in app header

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1719]
### Describe the bug

At a middle breakpoint (1024-1140px), two Alberta logos show up. (mobile and desktop variants)
This should not happen. 

<img width="1112" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/adce4650-c8bd-4f2d-ac07-f19cf69172c7">

### To Reproduce

https://design.alberta.ca/

Show up between viewport width 1024px-1140px

**Comment by lizhuomeng71** [comment]
Hi @vanessatran-ddi , I recall this issue was fixed by an hot fix last week, I cant seem to find the pull request for this fix through, let me ask around
