### ISSUE TITLE
[Bug]: Content pages layout too wide on ds website

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1721]
### Overview of bug/issues

In the latest release, the underlying layout has a lot of issues. 
- The page toc is too narrow
- the basic content pages on our website no longer staying at max content width
- the side menu width is inconsistent

<img width="1605" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/6afa32f3-3c4b-42cd-adee-2353e4e20c7f">

<img width="1604" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/7ded3a4b-13db-45b3-be57-d963c459d7d5">

On some pages the table-of-contents-nav is also smaller than the set width should be.
 
<img width="1387" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/58c10037-4874-4458-a53c-4a867ec1f428">

### To Reproduce

https://design.alberta.ca/design-tokens
On various pages with no inline table of contents nav.

### Additional context

The deploy preview for the toc work initially ([deploy-preview-125](https://deploy-preview-125--abgov-ui-component-docs.netlify.app/components/button)) has the component pages responding appropriately. 

This whole section is working great for the underlying layout, content width, and responsiveness. The rest of the pages in the site (except the home page) should work exactly like this underlying layout. If there is no side nav on the page, the content should keep a max width of 54rem (same as the content with the toc-nav.

<img width="1644" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/f076a3af-6dd3-427d-bc2c-8c9a6ff9be9d">

### Design specifications and intent
Layout had been [outlined in Figma](https://www.figma.com/file/qWGWDvULAAZuVaDpXCRzqP/DS-Reference-website?type=design&node-id=6562-327372&mode=design&t=eT8AyMMI9R4jTvRx-4). Please work with @twjeffery to refine layout for entire site.

**Comment by ArakTaiRoth** [comment]
@vanessatran-ddi After testing some more with @twjeffery about this. This issue was introduced with this [PR](https://github.com/GovAlta/ui-components-docs/pull/127). Which seems to indicate the issue is actually with our components somewhere, and not with the actual website. As the only thing done in that PR was changing the version of our components that our website was using.
