### ISSUE TITLE
Dropdown z-index not working

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1739]
![image](https://github.com/GovAlta/ui-components/assets/41582/71906902-abd8-4c62-b2cd-4f44714f5030)
![image](https://github.com/GovAlta/ui-components/assets/41582/e6c2dfc7-2056-47fd-be44-8de9256e13f4)

**Comment by ArakTaiRoth** [comment]
@ArakTaiRoth Verify this is an issue

**Comment by ArakTaiRoth** [comment]
This issue is verified, it has to do with our styled dropdowns. Native dropdowns don't have this problem.
