### ISSUE TITLE
[Feature Request]: Add ability to to use "includes" method for filterable dropdown

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1740]
### Is your feature request related to a problem? Please describe

Issue reported to us by designer Michael Adewumi

> Our dropdown option includes Strings and Numbers, as shown below.
![image](https://github.com/GovAlta/ui-components/assets/51723535/94b76001-8704-4e63-a266-4969e7c0d903)
Based on the default implementation, you can only search using "startsWith". But we also want to search the numbers.

### Describe the solution you'd like

We would like the filterable drop-down to have a property so that we can choose the method of text matching based on the context and user need.

### Provide evidence this is a needed component

From Michael

> For example, from our options, users can search by program name and ID, so they can decide to search by numbers alone or strings. The problem is that this is not possible with the current implementation.

### Describe alternatives you've considered

Michael's team will use default implementation for now but will keep an eye on this issue and will update when this feature becomes available.

### Do you have anything already created for this that we can use?

no

### Are you currently using this proposal inside your own service

no

### Are you able to assist to bring the feature to reality?

no

**Comment by ArakTaiRoth** [comment]
@Spark450 Setup a meeting with Michael and his developer and myself to discuss other options

**Comment by ArakTaiRoth** [comment]
The `filter` property can allow for this
