### ISSUE TITLE
[Feature Request]: Checkbox list (select one or more options from a list)

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1757]
We currently have a checkbox component, and no checkbox list (multiple checkboxes in a set, to select one or more options from a list).

This currently requires developers to put multiple checkboxes together and wrap in a form item. This can lead to inconsistent spacing, and is unnecessary work for teams.

### Describe the solution you'd like

Extend checkbox component to include more than one in a set. (1-9 options). Include examples on component page of checkbox list wrapped in form item (select one or more options from a list).

[Figma Design](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Component-library-%7C-DDD?type=design&node-id=12692-378853&mode=design&t=9AdzQmkFhoCMwi9k-4)

**Comment by Spark450** [comment]
From a dev perspective, it doesn't make sense to wrap this component in a "list".

We will create an issue to add a margin on the bottom of the "description" to maintain proper spacing between elements. of 16px 1rem
