### ISSUE TITLE
[Bug]: Checkbox item text not vertically aligned

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#1768]
### Describe the bug

<img width="1105" alt="image" src="https://github.com/GovAlta/ui-components/assets/82968683/711f7adb-18dc-4a76-ae25-595653a62a8d">
Left: code

Right: design

### To Reproduce

Can see in sandbox on website: https://design.alberta.ca/components/checkbox#tab-0

**Comment by bdfranck** [comment]
I just noticed that this PR also fixes https://github.com/GovAlta/ui-components/issues/1771.
