### ISSUE TITLE
Remove reference to the design system support channel on our design system website

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1774]
## Acceptance Criteria:
- Adjust information callouts referencing the Slack support channel to now reference drop in hours from the design system website
  - This callout is included on all "child pages of the website" except the Support -> Overview page
- Remove reference to slack channels on the "support" page and restructure headings 

## Screenshots
<img width="755" alt="Screen Shot 2024-04-11 at 11 11 40 AM" src="https://github.com/GovAlta/ui-components/assets/51723535/232ac6f9-35f5-438f-850e-a1f96ee0829d">

**Comment by twjeffery** [comment]
This was done in this PR: https://github.com/GovAlta/ui-components-docs/pull/124
