### ISSUE TITLE
Allow GoAContainer to fit content width in addition to the existing 100% width

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#1816]
The `.goa-container` `flex` css can updated to allow for dynamically setting it to prevent flex growth.

```
  .goa-container {
    box-sizing: border-box;
    display: flex;
    flex: 0 0 auto;   /** here **/
    flex-direction: column;
  }
```

The these changes:
![image](https://github.com/GovAlta/ui-components/assets/41582/12629499-3ece-4800-9848-54d3ad41591d)

## Acceptance Criteria

1. New property that dictates how the container is sized (either full-width or to content)

**Comment by twjeffery** [comment]
From this thread in the support channel: https://goa-dio.slack.com/archives/C02PLLT9HQ9/p1714490521425969
