### ISSUE TITLE
Tooltip: Tooltip increases height of containers

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1852]
# Info

You can replicate this with the following code:
```html
<div>
  <goa-tooltip content="Trying some more long form text here to see how it's rendered">
    <goa-icon type="information-circle" />
  </goa-tooltip>
</div>

<div>
  <goa-icon type="information-circle" />
</div>
```
The first div will be 37px in height, the second div will be 29px in height, despite the actual visible content being the exact same.

## Acceptance Criteria:

1. Tooltip doesn't increase the height of containers it's in

**Comment by syedszeeshan** [comment]
Talked to Thomas, as per Figma, 4px of margin is requried b/w the tooltip and the Icon, so we need to keep the margin in the .tooltip-target class.

An alternative is e.g. to change the .tooltip-target class to margin: 0 and add a margin of 4px to the .tooltip-text.top class instead... and so on to other such classes, but these are hacky solutions.

Below is a cleaner way of making both divs to have some height. The only caveat is the user needs to be aware of the mt and mb props

```
<div style="background-color: aquamarine;">
  <goa-tooltip content="Trying some more long form text here to see how it's rendered">
    <goa-icon type="information-circle" />
  </goa-tooltip>
</div>

<div style="background-color: blanchedalmond;">
  <goa-icon type="information-circle" mt="2xs" mb="2xs"/>
</div>
```

In the above example, the bottom div which is initially 8 px shorter in height, but after adding `mt="2xs" mb="2xs"`, this div gets the same height as the one above.

**Comment by ArakTaiRoth** [comment]
Closing this issue as the proposed solution doesn't actually work, and the actual solution is to just increase margin around any non-tooltip icons in the same container.
