### ISSUE TITLE
Checkbox: Checkbox not aligned to top of text

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1863]
# Info

Currently if you use a lot of text in the `text` property of the Checkbox component, the checkbox itself is aligned vertically to the middle of the text. It should be aligned to the top of the text.

Should look like this:
![image (19)](https://github.com/GovAlta/ui-components/assets/1081991/cd7bf596-3f54-4292-aa68-725175fa8fc1)

Not like this:
![image (20)](https://github.com/GovAlta/ui-components/assets/1081991/b55b4e4c-a34d-4531-b966-706cc5a0c84a)

This can be duplicated and tested with the following code:
```html
<div style="width: 530px;">
  <goa-form-item label="Test" mb="3xl">
    <goa-checkbox name="item" goaChecked text="I agree to the senior discount terms of use. I am 65 years of age or older, a resident of Alberta, and this purchase is for my personal use." />
  </goa-form-item>
</div>
```

## Acceptance Criteria:

1. Checkbox part of the Checkbox component should be aligned to the top of the text vertically

**Comment by bdfranck** [comment]
I accidentally introduced this issue in https://github.com/GovAlta/ui-components/pull/1777 when I added centre alignment to the label:

https://github.com/GovAlta/ui-components/blob/97f0900b75fe5b10c82cdda31d97bdf1d317a72c/libs/web-components/src/components/checkbox/Checkbox.svelte#L135-L138
