### ISSUE TITLE
Checkbox: Groups don't stack

### ISSUE THREAD

**Issue by bdfranck** [GovAlta/ui-components#1876]
### Describe the bug

We introduced a minor layout issue with https://github.com/GovAlta/ui-components/commit/e83799a953cc3e90a9efb8db4a96487c2efeccb4: checkboxes are rendered `inline` instead of `block`. A group of checkboxes in a form item looks like this...

![image](https://github.com/GovAlta/ui-components/assets/1479091/f892c125-b4ee-47f4-ba43-c92ac532f70a)

...instead of this:

![image](https://github.com/GovAlta/ui-components/assets/1479091/8af2ca74-f47f-402f-a36a-f14842fb919c)

### Provide Code

The issue is found in this line:
https://github.com/GovAlta/ui-components/blob/de245a79405082d8811cf6813148b6149b98d557/libs/web-components/src/components/checkbox/Checkbox.svelte#L130

### To Reproduce

Place a couple of checkboxes within a `goa-form-item`:

```html
<goa-form-item label="Select one or more options">
  <goa-checkbox checked="true" name="optionOne" text="Option one" />
  <goa-checkbox checked="false" name="optionTwo" text="Option two" />
  <goa-checkbox checked="false" name="optionThree" text="Option three" />
</goa-form-item>
``` 

### Additional context

@chrisolsen made the change to address an existing issue: the clickable labels filled the available horizontal width. ⬇️ 

![Peek 2024-05-30 09-08](https://github.com/GovAlta/ui-components/assets/1479091/3cdfdace-1572-49b6-925e-32a7f86d9992)

Ideally, we want the checkboxes to stack and are only as wide as the label.

**Comment by lizhuomeng71** [comment]
issue is verified on react and angular
