### ISSUE TITLE
Button and Input and Tabs: Weird tab handling in documentation

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1883]
# Info

Issue 1:
![image](https://github.com/GovAlta/ui-components/assets/1081991/ff227461-89ef-485b-ac54-b2d2830b16e6)

This issue is on both the Button and the Input component pages. This issue can only be replicated in a Chromium browser.

Issue 2:
![image](https://github.com/GovAlta/ui-components/assets/1081991/3dea5469-4e76-48f0-afb6-9e473663cd16)

This issue exists in the Tabs page

Issue 3:
The following code:
```html
<goa-tabs initialtab="1">
  <goa-tab>
    <div slot="heading">
      Tab Item 1
    </div>
    Tab Item 1
  </goa-tab>
  <goa-tab>
    <div slot="heading">
      Tab Item 2
    </div>
    Tab Item 2
  </goa-tab>
  <goa-tab>
    <div slot="heading">
      Tab Item 3
    </div>
    Tab Item 3
  </goa-tab>
</goa-tabs>
```
Doesn't actually set the `initialTab`, the `initialTab` property doesn't work no matter what number you give it.

## Acceptance Criteria:

1. There should not be blank tabs on any of our component pages
2. Tabs page should have the sandbox tabs inside the sandbox
3. The `initialTab` property should correctly set the initial tab on page load

## More Info

To fix Issue 2, you should just need to add `e.stopPropogation()` inside `getSlottedChildren`.

**Comment by chrisolsen** [comment]
The `stopPropagation()` needs to be put within the parent in the event handler, not the `getSlottedChildren' function
