### ISSUE TITLE
Hero banner: update margins

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1895]
### Describe the bug

**Acceptance criteria**
-Update the component with the following margin values:
  -padding right left should be 3XL, XL, M, following our Large screen, medium screen, and small screen breakpoints.
  -padding top and bottom should be 2XL on desktop, and tablet, and XL on mobile

### To Reproduce

[View live component on docs site](https://design.alberta.ca/components/hero-banner#tab-0)

**Comment by lizhuomeng71** [comment]
issue is verified on react and angular
