### ISSUE TITLE
Website: Complex bug verification process

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1944]
## Acceptance Criteria:

- [Author a page with the following content](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3157033405/Complex+bug+verification+process) and publish on our design system website
- The page should be located: Get started -> Developers -> Bug verification process

**Comment by Spark450** [comment]
This story is best suited to @twjeffery since it will require some translation of the page content/layout in Confluence to the website.

**Comment by asikinack** [comment]
@Spark450 I created a [second version](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3157033405/Complex+bug+verification+process) of the content for your review.

**Comment by Spark450** [comment]
@asikinack I like your "version 2" lets go ahead with that content. Thanks for the thoughtful revisions.
