### ISSUE TITLE
Radio: Can't dynamically change error property

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1972]
# Info

Using this code:
```html
<goa-radio-group name="item" [error]="errorVariable" mb="xl">
  <goa-radio-item
    value="Test 1"
    label="Test 1"
  />
  <goa-radio-item
    value="Test 2"
    label="Test 2"
  />
  <goa-radio-item
    value="Test 3"
    label="Test 3"
  />
</goa-radio-group>
<br />
<goa-button (_click)="onClick()">Set Error</goa-button>
```
```javascript
export class RadioComponent {
  errorVariable = false;

  onClick() {
    this.errorVariable = false;
  }
}
```
You can replicate the issue. The page loads with no error set on the Radio Group. If you click the button, the expected behaviour is that the error property is set to true on the Radio Group. The actual behaviour is that nothing happens. If you go back to `web-components` version `1.19.1`, this exact same code works as expected. This is the only [PR](https://github.com/GovAlta/ui-components/commit/c91be3372163e86191d9dd09cc006fea742a4b21#diff-a63ba357604264c6bd38c5add5d4453c62b7e5ea9de27e23a21174a4f1753047) I can see in the `1.20.0` upgrade that affected the Radio Group specifically.

## Acceptance Criteria:

1. You can change the error property dynamically on the Radio Group component
2. Ken to setup Cypress test for this scenario
3. Test helper text property as well

**Comment by Spark450** [comment]
@ArakTaiRoth can we narrow this down to which commit broke this feature?
