### ISSUE TITLE
Dropdown, Input, and Modal: Using deprecated properties

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#1975]
# Info

In our codebase we have designated the following as deprecated:
1. Icon Button
    - `variant="nocolor"`
2. Icon
    - `ariacontrols`
    - `ariaexpanded`

These properties are still being used in our codebase. Which leads to console warnings, and developers wondering where they're coming from when they themselves aren't using them.

These uses can be found in:
1. Dropdown.svelte uses `ariacontrols` and `ariaexpanded` in 2 places for each
2. Input.svelte and Modal.svelte are using `variant="nocolor"` in one place each

## Acceptance Criteria:

1. We should not be using our own deprecated properties

**Comment by Spark450** [comment]
@ArakTaiRoth  Will move this to our "breaking changes" issue and bundle with that work.

**Comment by Spark450** [comment]
Work added to issue #1780

**Comment by ArakTaiRoth** [comment]
Re-opening, as the switch to breaking changes does not actually solve the issue in this story. And this story is not breaking.
