### ISSUE TITLE
Selection chip component

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#1981]
## Acceptance Criteria:

- "Selection chip" [Figma design](https://www.figma.com/design/3pb2IK8s2QUqWieH79KdN7?node-id=51295-66443#901884890)
- See [selection chip examples](https://www.figma.com/design/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Component-library-%7C-DDD?m=auto&node-id=8360-256291&t=Tlnbv6kTIoAid7hO-1) for Screen reader behaviour
- Allow a Leading Icon, and if one is supplied, it takes precedence over our leading icon
- This is a new component

**Comment by ArakTaiRoth** [comment]
Closing as we need more evidence that this component is actually needed

**Comment by ArakTaiRoth** [comment]
Re-opening as this is needed ever since we replaced `Chip` with `Filter Chip`, this will now fill the role that `Chip` originally filled.
