### ISSUE TITLE
[Bug]: Show dropdown updates the number of rows but pagination dropdown not getting updated

### ISSUE THREAD

**Issue by rahuldingria** [GovAlta/ui-components#1985]
### Describe the bug

Show dropdown updates the number of rows but pagination dropdown not getting updated
https://jam.dev/c/4b0f14f7-3c05-4e78-8539-1014ac6cdd55

### To Reproduce

https://jam.dev/c/4b0f14f7-3c05-4e78-8539-1014ac6cdd55

**Comment by ArakTaiRoth** [comment]
This will likely be fixed if we can figure out the backend code that updates the Pagination component correctly. This is already being worked on by this story, #1680

**Comment by ArakTaiRoth** [comment]
Closing as this issue is resolved by #1680
