### ISSUE TITLE
Popover: make popover-target and some child elements 

### ISSUE THREAD

**Issue by vanessatran-ddi** [GovAlta/ui-components#1992]
Popover, `target` node  should be mandatory. The way Angular is written now: 
```
<goa-popover
      [maxwidth]="maxWidth"
      [padded]="padded"
      [position]="position"
      [relative]="relative"
      [testid]="testId"
      [mt]="mt"
      [mb]="mb"
      [ml]="ml"
      [mr]="mr"
    >
      <ng-content />
    </goa-popover>
```
Won't make sure that:
* target is mandatory (We can write a popover without any children element)
* `ng-content` is optional, so there is not way we can make sure that `popover` will always have children inside it. 
(not like React)
![image](https://github.com/GovAlta/ui-components/assets/120135417/71f369a7-bc31-4571-b251-68eafd1b822a)

## Acceptance Criteria

There may not be a way to actually fix this and make content mandatory for the angular wrapper, so investigate if there even is an option

cc @chrisolsen

**Comment by ArakTaiRoth** [comment]
Closing as this was merged into the `anguler-components` branch
