### ISSUE TITLE
[Bug]: GoAAccordion with GoAThreeColumnLayout

### ISSUE THREAD

**Issue by Steve-Rozeboom** [GovAlta/ui-components#1996]
### Describe the bug

The main text of the GoAAccordion does not render properly within the GoAThreeColumnLayout. It is not vertically centered.

### Provide Code

[testPage.zip](https://github.com/user-attachments/files/16180601/testPage.zip)
![GoAAccordion-with-GoAThreeColumnLayout](https://github.com/GovAlta/ui-components/assets/151247001/cefa160e-0ba6-4a8d-b58b-f34c1234fa9f)

### To Reproduce

The testPage will replicate the described issue. 

### Additional context

This issue is when using Chrome and Edge. It works as expected in Firefox. Has not tested in other platforms.

**Comment by ArakTaiRoth** [comment]
Closing as we will no longer be supporting our multi column layouts
