### ISSUE TITLE
Icon and Icon Button: pencil does not change colours

### ISSUE THREAD

**Issue by ataboo** [GovAlta/ui-components#2002]
### Describe the bug

The goa-icon-button 'pencil' icon does not change colours when different variants are set.

![image](https://github.com/user-attachments/assets/9eeecd22-8449-48ee-abb3-dcac46976c23)

### Provide Code

```
<goa-icon-button variant="color" size="medium" icon="pencil" arialabel="Pencil icon"></goa-icon-button>
```

```
<!-- `fill="#333333"` overrides any styling />
<svg width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg"> 
  <path d="M4.86885 18.6573C4.86885..." fill="#333333"></path>
</svg>
```

### To Reproduce

Can be reproduced in code or on the current docs site.
1. Go to the icon-button component
2. Pick the icon "pencil"
3. Flip through the variants

### Additional context

angular-components: v3.0.3
design-tokens: v1.2.0
web-components: v1.22.0

It looks like the paths inside the SVG define a fill colour so that prevents the icon from respecting any css colours.

**Comment by Spark450** [comment]
Additionally, It looks like the "Size" and "Inverted" properties also do not work.
