### ISSUE TITLE
Button: initially focused button in modal missing yellow focus border

### ISSUE THREAD

**Issue by vanessatran-ddi** [GovAlta/ui-components#2008]
### Describe the bug

The Cancel button focused state missing yellow border

### Provide Code

```
<GoAButton onClick={onClick}>
  Show Modal
</GoAButton>
<GoAModal heading="Are you sure you want to exit your application?" role="alertdialog" open={open}>
  <GoAButtonGroup alignment="end">
    <GoAButton type="tertiary" onClick={onClick}>
      Cancel
    </GoAButton>
    <GoAButton type="primary" onClick={onClick}>
      Exit
    </GoAButton>
  </GoAButtonGroup>
</GoAModal>
```

### To Reproduce

We can see this bug under DS website: https://design.alberta.ca/components/modal#tab-0

1. Open the Modal
2. The Cancel button is focused (because when we tab, Exit button is focused with yellow border)

First open modal: (cancel is focused but no yellow border)
![image](https://github.com/user-attachments/assets/0b8fd764-ee2b-4fb3-ade3-c35eff373981)

Tab to move to Exit: 
![image](https://github.com/user-attachments/assets/8d6ced50-3206-48d2-bbd9-e90dcd35a600)

Shift Tab to move back to Cancel button: 
![image](https://github.com/user-attachments/assets/4e5ab69f-293f-4e12-95b0-89f255cb97b1)

(Now we can see yellow border)

### What browsers are you seeing the problem on?

Chrome

**Comment by ArakTaiRoth** [comment]
Don't know enough about how this definitively should work. @Spark450 Can we track this for future accessibility testing?
