### ISSUE TITLE
[Bug]: Must tab 2 times to focus next element from Dropdown and TextArea

### ISSUE THREAD

**Issue by vanessatran-ddi** [GovAlta/ui-components#2011]
### Describe the bug

When we focus on the `GoADropdown`, and want to focus next element, we press "Tab", and we must press 2 times in order to move the focus out of `GoADropdown` to focus the next element.

### Provide Code

```
<GoAFormItem label="Type" mt="xs">
            <GoADropdown onChange={onChangeType} value={type}>
              <GoADropdownItem value="1" label="Option 1"></GoADropdownItem>
              <GoADropdownItem value="2" label="Option 2"></GoADropdownItem>
            </GoADropdown>
          </GoAFormItem>
          <GoAFormItem label="Name" mt="xs">
            <GoAInput onChange={onChangeName} value={name} name="name"></GoAInput>
          </GoAFormItem>
           <GoAFormItem label="Description" mt="xs">
            <GoATextArea
              name="description"
              width="80%"
              rows={2}
              onChange={onChangeDescription}
              value={description}></GoATextArea>
          </GoAFormItem>
```

### To Reproduce

We can test by this URL: 
https://deploy-preview-196--abgov-ui-component-docs.netlify.app/components/modal#component-example-add-item

The movie: 

https://github.com/user-attachments/assets/a33860b4-b0f8-4f35-85f9-905908be191e

### What browsers are you seeing the problem on?

Chrome

**Comment by ArakTaiRoth** [comment]
@vanessatran-ddi Closing, as this is already covered by #1511
