### ISSUE TITLE
[Documentation]: Add missing component properties to HTML/CSS custom data

### ISSUE THREAD

**Issue by bdfranck** [GovAlta/ui-components#2015]
Let's review all component `.html-data.json` files and make the following changes:
1. Add missing component properties
2. Change any camel case property names to lower case

### Accordion
- Add `testid`

### App Header
- Add `fullmenubreakpoint`
- Add `testid`
- Change `maxContentWidth` to lower case

### App Header Menu 
- Add `type`

### Badge
- Add `testid`

### Block
- No changes

### Button
-

**Comment by ArakTaiRoth** [comment]
@bdfranck We've got work coming in the future that makes these `*.html-data.json` files redundant, so we're going to close this story
