### ISSUE TITLE
Core css documentation and any peer dependencies from other libs

### ISSUE THREAD

**Issue by tzuge** [GovAlta/ui-components#203]
Core css library is a distributable that includes the Alberta.ca design system styles sheets. These style sheets are not structured for application development and can conflict with component styles. 

The other framework variants (React, Angular, Vue) use style encapsulation and do not require core-css. Make sure that documentation is clear and there is no peer dependency no core-csss.

- [x] Send a message out to teams to find out who is using this in dev guild slack channel?
- [x] Go through Github and gitlab to check for Core CSS in the various projects

**Comment by Spark450** [comment]
recommendation to refactor Core css. Remove explicit component styles and only provide variables.

**Comment by Spark450** [comment]
Include "Do not use Core css"message in "readme"
