### ISSUE TITLE
QA: Write Automated Tests for previous Dropdown issues

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#2042]
## Acceptance Criteria:

Automated tests are written for the following stories:

- [x] #1960 
- [x] #1758 
- [x] #1739 
- [x] #1734 
- [x] #1702 
- [x] #1698 
- [x] #1679 
- [ ] #1510 
- [x] #1496 
- [x] #1494 
- [x] #1445 
- [x] #1378 
- [x] #1319 
- [x] #1307 
- [x] #1289 
- [x] #1266 
- [x] #1258 
- [x] #1244 
- [x] #1237 
- [x] #1142

**Comment by lizhuomeng71** [comment]
1496 is a duplicate of 1319, no cypress test was created on 1496

**Comment by lizhuomeng71** [comment]
1237, Current branch space will select the drop down and close the popover

**Comment by ArakTaiRoth** [comment]
Closing as this work is done now
