### ISSUE TITLE
Modal: Incorrect sandbox code

### ISSUE THREAD

**Issue by lizhuomeng71** [GovAlta/ui-components#2047]
# Info

In the Angular documentation, both Angular and React have an `onClose` function defined, but the buttons in the html code use the `onClick` function instead of `onClose`

## Acceptance Criteria:

1. Buttons inside the Modal should use the `onClose` function that's defined

**Comment by ArakTaiRoth** [comment]
Closing, as upon closer inspection everything is accurate and the onClick function is working for both opening and closing the Modal
