### ISSUE TITLE
Modal: Add shadows and style to pin header and/or actions when scrolling with long content

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#2065]
# Info

We need a shadow separating content from the header and bottom of the modal when those 2 elements are overtop of content.
![image](https://github.com/user-attachments/assets/f4eaeea6-8ec4-4fca-ab01-0cf6f9614588)
![image](https://github.com/user-attachments/assets/8c1de665-ed08-477b-9ad0-b6de6edf1df8)

We previously had this functionality as of version 1.18.0, it was removed in 1.18.1 with this [commit](https://github.com/GovAlta/ui-components/pull/1520/files#diff-130385797d8724fa14efc0c7869731ced3ecd94dee280deb6441be14589ac397), Specifically it was the removal of all the `.addClass` functionality that was adding classes to different components to apply CSS styles. The CSS styles still exist in `Modal.svelte`, on lines 384 - 396, `.scroll-top`, `.scroll-middle`, and `.scroll-bottom`

## Acceptance Criteria:

1. We have shadows between the header and the content, and the bottom of the modal and the content

**Comment by twjeffery** [comment]
It's not just shadow, there's spacing and border considerations in the design here. [Figma design to reference ](https://www.figma.com/design/rmtnaglLsyzwdl34BCIBTN/Component---Modal?node-id=2156-297&m=dev)
