### ISSUE TITLE
Modal: No vertical space between content and action buttons

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#2069]
# Info

Modal doesn't have space between content and actions for any of the Callout variants. 

Should be `--goa-spacing-xl;` [Figma design](https://www.figma.com/design/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Component-library-%7C-DDD?node-id=48478-52430&t=oQAut2qtPIpfS0Me-4)

<img width="714" alt="image" src="https://github.com/user-attachments/assets/1464fb74-646a-4964-964c-582f1691e38d">

## Acceptance Criteria

1. Modal in Sandbox uses `<div slot="actions">` to separate content from buttons

**Comment by Spark450** [comment]
@twjeffery I have removed the second part of the acceptance criteria because we have [this story](https://github.com/GovAlta/ui-components/issues/1882) to add the ability to select the default globally across all components.
