### ISSUE TITLE
Pagination: id of root being duplicated

### ISSUE THREAD

**Issue by PaigeDDD** [GovAlta/ui-components#2075]
# Info

Issue raised by Andrew Filipe Naves de Barros

In our Pagination component we have a `<goa-block>` using an `id="root"`. This could potentially cause issues with React setups that is also used automatically on the main `<div id="root">` in the app. Semantic HTML states only one component can have a distinct `id` value, and they should never be shared.

This could be a bigger issue for people trying an SSR implementation. And he's personally seen issues where click events don't work as expected on other elements, because it's not sure where to assign them sometimes.

## Acceptance Criteria

1. `<goa-block>` inside Pagination has it's `id` property changed from "root" to something else

**Comment by ArakTaiRoth** [comment]
I can't find anything about this happening with our Checkbox component. We have a class of "root" in our Checkbox, but no id of "root". We do however have `<goa-block id="root">` in our Pagination component, so this is indeed correct. I don't know how much of a problem this actually is though. Wil reach out to @PaigeDDD tomorrow to get some answers.

**Comment by ArakTaiRoth** [comment]
Spoke with him, updated the story as needed.

**Comment by chrisolsen** [comment]
Our id of `root` is within the shadow root, so it will not cause issue where id selectors. This is not an issue.

**Comment by lizhuomeng71** [comment]
issue is verified on react and angular

**Comment by ArakTaiRoth** [comment]
Closing this story for @chrisolsen 's comment above
