### ISSUE TITLE
[Bug]: Page elements showing through Modal

### ISSUE THREAD

**Issue by jim-muirhead** [GovAlta/ui-components#2087]
### Describe the bug

Some page elements are showing through the Goa-Modal component (see screenshot), which sometimes obscures the content of the modal.

![image](https://github.com/user-attachments/assets/007f331e-73bf-4b38-9459-1f217d396fbb)

### To Reproduce

1. Navigate to https://purchasing.alberta.ca/search
2. Open the "Category" filter panel in left column.
3. Select all 3 available filter options.
4. A modal appears with some page elements on the page underneath appearing above and over the modal.

### What browsers are you seeing the problem on?

Chrome, Safari, Edge

**Comment by ArakTaiRoth** [comment]
Closing
