### ISSUE TITLE
New Component (Multi-action button) or Dropdown

### ISSUE THREAD

**Issue by ArakTaiRoth** [GovAlta/ui-components#2104]
# Info

We need to duplicate the functionality in this [Figma page](https://www.figma.com/design/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Component-library-%7C-DDD?node-id=41625-336313&node-type=section&t=5abLL2h78f4gCzNR-0).

Basically we need a button type for a Dropdown.

Options include modifying the Dropdown component to work with this `variant`, or creating a new component.

## Acceptance Criteria:

1. Investigate and implement the better of the 2 options listed above

**Comment by Spark450** [comment]
Work needed to be done is captured in issue #1835
