### ISSUE TITLE
Revising Storybook "layout"

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#215]
**Overview**
Related to issue #208 Review interview findings for insights and to guide design and exploration

**Considerations**
- Understanding the configuration limitations of Storybook
- How does Storybook fit into the larger collaborative design system website underway with CPE

**Acceptance criteria**
-WIP

Note: This is a design and development task

**Comment by twjeffery** [comment]
As useful resource for this effort: 
https://5ccbc373887ca40020446347-geedzbiswp.chromatic.com/?path=/story/intro--page

Storybook design system: a design system within Storybook that has a number of different component integrations built out in a really robust way, that could align well with our Figma variants.

> Storybook Design System is a reusable component library that helps Storybook contributors build UIs faster. The goal is to make building durable UIs more productive and satisfying.
