### ISSUE TITLE
Icon: Design system website contextual example update

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#2150]
## Acceptance Criteria:

- Add jump links below "properties" accordion:
  - Alert and messaging
  - Basic
  - Direction
  - Interactions
  - Accounts
- Add space "m" token (16px) between each heading and the corresponding section
<img width="844" alt="Screen Shot 2024-09-17 at 3 58 31 PM" src="https://github.com/user-attachments/assets/8bc307c8-57d0-4756-b98c-690db386f643">

**Comment by mxsoco** [comment]
- Icon page has 'm' already added to top margin for each icon section. 
- In-section jump links made redundant as it would be a duplication of the TOC on the right side of the page.

**Comment by Spark450** [comment]
Agreed @mxsoco, I will close this issue as there is no work needed here
