### ISSUE TITLE
Investigate viability of component level tokens

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#2162]
## Acceptance Criteria:

- Choose from among the following components to test component-level tokens:

  
Demo link: [DemoApp](https://vanessatran-ddi.github.io/latest-react-demo/)
Source code: [CSS file ](https://github.com/vanessatran-ddi/latest-react-demo/blob/privacy-portal-components/src/override.css)
[React files ](https://github.com/vanessatran-ddi/latest-react-demo/tree/privacy-portal-components/src/components/2162)
- [x]   - Callout 
- [x]   - Table 
- [x]   -  Accordion
- [x]   -  Container 
- [x]   -  Button token
- [x]    -  Side Menu

- Once component is chosen, create the necessary component level tokens to match the [figma design parameters](https://www.figma.com/design/Jb1Pko64vavuvNsxbR9JB6/PP-Alpha---Mockups?node-id=1709-437933&t=FPsAgG5ESHUVLcMT-1)

- Review component with updated token values with @twjeffery to verify fidelity to Figma design

Plan to do the below: 

- [x] 1. Add new design tokens variables with current values to components on the figma link [figma token variables] )(https://www.figma.com/design/NRFUYjCwVoI9qMbFEG6s7J/Component-tokens?node-id=0-1&node-type=canvas&m=dev) to our `design-tokens` repo. 
- [x] 2. Update `ui-components` components with those new design token variables added on the step 1
- [x] 3. Create a demo react app (from our react template) and add `::root` CSS style to override new design token variables on step 1 and 2, with PP team values (color, border..) then deploy to review together with @twjeffery 

[Markup io feedback link](https://app.markup.io/markup/ee041f4d-3186-4b6e-bbbb-91a5771ee99d?view_mode=Desktop)

**Comment by ArakTaiRoth** [comment]
Re-opening as there's one more PR attached to this
