### ISSUE TITLE
Outline and document the UX Strategy, Process, and Roadmap to help the team and stakeholders reach a shared vision for the Design System

### ISSUE THREAD

**Issue by ambroseyau** [GovAlta/ui-components#217]
This is a communication tool to align UX priorities and identify all suitable UX activities to improve our design system.

- [x] Document in Miro https://miro.com/app/board/o9J_liuNrRQ=/?invite_link_id=321816282818
- [x] Discuss with Platform Design team

**Comment by Spark450** [comment]
Will chat with Ambrose to split this up into smaller chunks
