### ISSUE TITLE
Form stepper: New component for Privacy Portal team

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#2175]
## Acceptance Criteria:

- Build web component
- Create NPM package to house the form stepper
  - This package in intended for use by the Privacy Portal and other flagship product teams only
- Create a "local" React component within the Privacy Portal application
- Component **will not** be documented on the design system website
- [Figma design and component documentation](https://www.figma.com/design/Jb1Pko64vavuvNsxbR9JB6/PP-Alpha---Mockups?node-id=3435-196668&t=65fznycnmVKzQtZj-1)

**Comment by ArakTaiRoth** [comment]
Closing as this is completed
