### ISSUE TITLE
Design system website: stub "Foundations" pages

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#2181]
## Background

The UX team is ready to add the "foundations" pages to the design system website. The design system team will create the required pages, and the UX team will populate those pages with content.

## Acceptance Criteria:
- Review [IA diagram](https://miro.com/app/board/uXjVKmgHvLg=/?share_link_id=878093191197) in Miro to get an understanding of how the pages will be included in the navigation
- Create top-level navigation item "Foundations"
- Create the following headings and "blank" pages under "Foundations":

**Foundations**
- Foundations (menu heading)
  - Design at GOA
  - Accessibility
- Style guide (menu heading)
  - Color
  - Iconography
  - Images
  - Logo
  - Typography
  - Layout
  
  
![image](https://github.com/user-attachments/assets/5a32f984-3903-46f9-9fda-d2678e764f0c)

**Comment by ArakTaiRoth** [comment]
Closing as this story is done, the work isn't, but what this story requested is.
