### ISSUE TITLE
Interview DIO designers to understand their design system needs.

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#221]
**Overview**
Gain an understanding of how designers currently use the design system and identify opportunities for improvement in organization, structure, content, and delivery. This work is part of a larger piece of work #218 wherein we want to share our findings from our user interviews with designers with CPE to advocate for the design decisions we are making regarding the design system. 

[Link to interview question here](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/edit-v2/2133819448)

**Comment by ambroseyau** [comment]
All the user research interviews are now completed.
Below is the link to all the notes
https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2142863443/FED+User+Research+Findings

**Comment by ambroseyau** [comment]
UX findings + Recommendations Complete:
https://miro.com/app/board/o9J_liSPxI8=/?invite_link_id=765001410098
