### ISSUE TITLE
CI/CD: Need to rethink how the pipeline works for this project

### ISSUE THREAD

**Issue by tzuge** [GovAlta/ui-components#223]
We're not making productive use of dev and test deployments of storybook for the libraries. Need to rethink what 'pipeline' really means for this repo.

Potentially:
alpha branch deploys [http://ui-components.alpha.alberta.ca](http://ui-components.alpha.alberta.ca)
beta branch deploys [http://ui-components.beta.alberta.ca](http://ui-components.beta.alberta.ca)
main branch deploys [http://ui-components.alberta.ca](http://ui-components.alberta.ca)

**Comment by tzuge** [comment]
- This project/repository outputs two groups of distributable: 
  - the libraries published to NPM, and
  - the storybook web app for the library documentation
- Currently both distributable are handled via the same pipeline workflow across multiple environments. However, there is no gates or verification in the process, and we're not making use of the environments.
- The storybook deployment part is only run on the beta branch, but there are also releases off of alpha and main. How do we manage storybooks for alpha, beta, and latest releases?

**Comment by Spark450** [comment]
❓ As designers what do we want to validate?
❓ How do we validate things to be consistent and follow standards.

**Comment by Spark450** [comment]
❓ Web components should be more of an MVP thing so that we don't get bogged down in UI reviews.

**Comment by Spark450** [comment]
[Miro board for planning](https://miro.com/app/board/uXjVOc7pLyE=/?invite_link_id=801705413519)

**Comment by tarynlaramie** [comment]
todo: wrap up discussions on alpha, beta, prod and dev, test, prod
