### ISSUE TITLE
[Bug]: For an Input Form Item with Leading or Trailing Content, the Left and Right Borders are Missing

### ISSUE THREAD

**Issue by lizhuomeng71** [GovAlta/ui-components#2235]
### Describe the bug

When an input form item includes either leading or trailing content, the component fails to display borders on the left and right sides. This inconsistency in the border styling affects the visual integrity of the input field, making it appear incomplete and potentially reducing usability for end-users.
![image](https://github.com/user-attachments/assets/4f035970-6416-4bc8-a069-adf9769d819e)

### Provide Code
```
<goa-form-item label="Tuition">
  <goa-input (_change)="onChangeTuitionAmount($event)" value="" name="tuition" mb="xl"  error="true">
    <div slot="leadingContent">$</div>
    <div slot="trailingContent">CAD</div>
  </goa-input>
</goa-form-item>
<goa-form-item label="error with leading content">
  <goa-input value="" name="tuition" mb="xl"  error="true">
    <div slot="leadingContent">$</div>
    <div slot="trailingContent">CAD</div>
  </goa-input>
</goa-form-item>
```
### To Reproduce

Use Code Above

**Comment by twjeffery** [comment]
This bug is fixed with this PR https://github.com/GovAlta/ui-components/pull/2156
