### ISSUE TITLE
[Bug]: Error State with Leading and Trailing Content Incorrectly Changes Border Color on Hover

### ISSUE THREAD

**Issue by lizhuomeng71** [GovAlta/ui-components#2236]
### Describe the bug

When an input form item in an error state includes leading or trailing content, the border color changes on hover. This behavior contradicts the design specification, which states that the error state should have no hover effect. The hover-induced border color change causes inconsistency and may confuse users by implying additional interactivity that isn’t intended for error states.

### Provide Code

```
<goa-form-item label="Tuition">
  <goa-input (_change)="onChangeTuitionAmount($event)" value="" name="tuition" mb="xl"  error="true">
    <div slot="leadingContent">$</div>
    <div slot="trailingContent">CAD</div>
  </goa-input>
</goa-form-item>
<goa-form-item label="error with leading content">
  <goa-input value="" name="tuition" mb="xl"  error="true">
    <div slot="leadingContent">$</div>
    <div slot="trailingContent">CAD</div>
  </goa-input>
</goa-form-item>
```

### To Reproduce

Use Code Above

**Comment by twjeffery** [comment]
This bug is fixed with this PR https://github.com/GovAlta/ui-components/pull/2156
