### ISSUE TITLE
Create alignment between design and development component libraries

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#227]
**Description**
There are inconsistencies between the design and development UI component libraries. Review and note updates needed to align. 

**Acceptance Criteria**

- [ ] Note changes in Design system google sheet: https://docs.google.com/spreadsheets/d/1B3P0pP8SWTYsNN9xtVefBJmcd0RK54kS2sh5LzLnmiw/edit#gid=1161341563
- [ ] Coordinate and review with design system team to plan next steps

**Comment by Spark450** [comment]
Will include design review per web component.
