### ISSUE TITLE
Tooltip: Text is being clipped or covered

### ISSUE THREAD

**Issue by francisagyapong-goa** [GovAlta/ui-components#2273]
### Describe the bug

Tootips get covered by other elements, or clipped on pages with different stacking contexts. Please see an example here: https://stackblitz.com/edit/stackblitz-starters-thbxyz?file=src%2Fmy-page-component%2Fmy-page.component.html

![image](https://github.com/user-attachments/assets/eb9610e0-27f2-4a82-9c7d-aa9e0f6f8aba)
![image](https://github.com/user-attachments/assets/7d73a7aa-9406-4687-8457-dd4cb8da106d)

### Provide Code

https://stackblitz.com/edit/stackblitz-starters-thbxyz?file=src%2Fmy-page-component%2Fmy-page.component.html

### To Reproduce

Please see https://stackblitz.com/edit/stackblitz-starters-thbxyz?file=src%2Fmy-page-component%2Fmy-page.component.html

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by ArakTaiRoth** [comment]
@francisagyapong-goa You can fix this issue by adding `z-index` to the div that has `position: sticky`
