### ISSUE TITLE
Public form pattern: Task complete page

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#2276]
## Acceptance Criteria:

- Add a "task complete" page into the pattern.
  - This "task complete" page is presented to the user after completing all the fieldsets in a given task and before they go back to the task list page.
 
![image](https://github.com/user-attachments/assets/d8857ea3-27bf-4991-9dc2-5a0c3c2f733c)

**Comment by ArakTaiRoth** [comment]
Doesn't make sense to include in the pattern, not doing

**Comment by twjeffery** [comment]
Given that the content is very variable, and that it's a simple page, this is easier to implement as a custom page by a team alongside the pattern.

This needs to be included in the documentation ("how to add a confirmation page at the end of a task list").
