### ISSUE TITLE
Design system website (Spike)

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#228]
Create a design system website structure and pages in 

- [x] Explore Gitbook
- [x] Explore GitHub pages

**Acceptance criteria**

Create pages:
- [x] "color"
- [x] "callout" 
- [x] "shared service" (e.g. keycloak)

Tasks:
- [x] Defined enough of a site structure (as referenced by the pages)
- [x] Content
- [x] Integration with Storybook imbeds
- [x] Setup GitHub integration
- [x] Integration with Figma imbeds
- [x] Integration of "search" (e.g. via tags or frameworks etc.)

**Comment by tzuge** [comment]
Any specific requirement not supported in Github Pages?

**Comment by Spark450** [comment]
@tzuge That's a fair question, I'll connect with Tom and Ambrose to get a better sense of what the specific benefits would be here.

**Comment by twjeffery** [comment]
I completed a design spike to assess Gitbook. 
[Link to initial exploration in Gitbook](https://dio-design-system.gitbook.io/design-system/)

Initially the ease of creation through the tool, robust search, feedback functionality (comments, page rating, chat integration), and github integration seemed to be worth testing out. But I found that the Storybook integration overall was not sufficient, therefore not worth pursuing further. Switching focus now to Github pages.

**Comment by twjeffery** [comment]
Completed a design spike within github pages.
[v1 here](https://twjeffery.github.io/DIO-test-2/)

Created this on my own repo as a test, fleshed out a component page for [callout](https://twjeffery.github.io/DIO-test-2/docs/ui-components/callout/), as well as the overall structure and starting content within.
