### ISSUE TITLE
[Documentation]: Change references on website from "simple form" to "public form"

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#2283]
### Describe the problem

- We have decided on the name "public form" for the form pattern. The DS website should be updated to reflect this.

### Additional context

Changes need to be made on the following places and pages:
- left navigation when in the "patterns" section of the website
- [All page](https://design.alberta.ca/patterns)
- [Simple form page](https://design.alberta.ca/patterns/simple-form)

**Comment by twjeffery** [comment]
@ArakTaiRoth @Spark450 Not sure if I can be a reviewer for this, but I took a look through the content changes, and it's good by me.
