### ISSUE TITLE
[Documentation]: Support page broken or incorrect links

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#2293]
### Describe the problem

There are two broken links on the [the design system website](https://design.alberta.ca/)

- On the home page - "contact the design system team" (under the "How to use the design system in your service" heading)
  - This should link to: https://design.alberta.ca/get-started/support
- In the footer - "Contribute to the design system"
  - This should link to: https://design.alberta.ca/get-started/contribute
- In the footer - "Submit an issue"
  - This should link to: https://design.alberta.ca/get-started/support

**Comment by ArakTaiRoth** [comment]
Closed as being taken care of in another story
