### ISSUE TITLE
IDEAS - DatePicker: Design system website contextual example updates

### ISSUE THREAD

**Issue by twjeffery** [GovAlta/ui-components#2306]
### Date picker examples/use cases:  

Using the date picker in a service can get complicated working with different timezones and saving date vs date and time. Below are suggested examples to add to the design system website documentation to show how a service can save a date to a database:

1. Allow user to select a date and/or time and save to database, then later load from database and display same date in datepicker (regardless of user's timezone).  
2. Allow user to select a date and time, save to database, then later load from database and display same date and time in user's local timezone (e.g. 3pm if Mountain time, 5pm if Eastern time). That third example is used when needing to save/display a "moment in time" whereas the other examples are not. Then it sounds like you've considered date ranges before, which work the same as those 3 examples with a bit more complexity.

**Comment by Spark450** [comment]
Since there is some additional design and exploration that needs to be done before this can be implemented we will track this work in our "design" repo on [this issue](https://github.com/GovAlta/ui-components-design/issues/70)
