### ISSUE TITLE
Investigate to using README files to create web component docs

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#233]
Create a README.md file for each component that documents it's usage directly as well as with each of the supported javascript libs/frameworks.

Since  we are limited to using markdown/html, using the `<details>` and `<summary>` elements or just headings to section off the areas will be required.

## Dropdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

### Web Component
```html
<goa-dropdown>....</goa-dropdown>
```
### React
```html
<GoADropdown>....</GoADropdown>
```

### Details / Summary

<details>
  <summary>Web Components</summary>
  <code>
    web component example here
  </code>
</details>

<details>
  <summary>React Components</summary>
  <code>
    react component example here
  </code>
</details>

**Comment by Spark450** [comment]
Closed because of investigation into Github pages
