### ISSUE TITLE
Identify "patterns" that can accelerate teams

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#244]
## Background ##
During interviews with developers on the current design system team, developers were asked what could be done to improve the adoption of the design system. Developers were advocating for the creation of useful patterns that could act as an accelerator for projects.

##Definitions##
Patterns can take many forms. They can be small groups of components, page templates, flows, or even services.

## Acceptance criteria ##

- [x] Discover what teams want as a pattern for their services
- [x] Unpack findings to find commonalities
- [x] Identify highest level pattern "clusters"

**Comment by twjeffery** [comment]
Related but on a bit of a slightly different track, there is an interesting area of starter-kits and templates that would be worth exploring. Somewhere in this area of sandbox to try out and reuse... https://starter-kit-demo.herokuapp.com/example.html 

This could be a valuable way to share these "templates" with teams? 

We are starting to really have two products potentially from the design system team: 
- A design system website as a tool for communication, a storefront, and implementation.

- A template, sandbox of our design system, as a tool to try out, and use as a starting point in building.

**Comment by tzuge** [comment]
the project templates for React and Angular already exists in: https://github.com/abgov/nx-tools

**Comment by Spark450** [comment]
Story is being re-written based on better identifying knowledge gaps. More discovery is needed to outline what "starting points" are more useful for teams.
