### ISSUE TITLE
Spike: Investigate component templating for speed and consistency

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#246]
## Overview ##
Investigate automated scaffolding methods that could be used to give new components a consistent starting point. This measure has the potential to speed up the development of new components and increase standardization between components.

## Background ##
This issue was surfaced from a discussion with @cjam and @chrisolsen as part of a larger discussion about service team needs and contribution to the design system.

## Acceptance criteria ##
- [ ] Investigate methods for automating the templating of components
- [ ] Web component template
  - [ ] Angular template
  - [ ] React template

**Comment by cjam** [comment]
Just an FYI, I don't think Ashnav's expertise aligns with this templating issue, I changed the acceptance criteria to me for this one.
