### ISSUE TITLE
Unable to use vue components

### ISSUE THREAD

**Issue by kirk-govab** [GovAlta/ui-components#251]
I installed the @abgov/vue-components package via the following statement:
`npm install @abgov/vue-components`

This was successful and added the package to my dependencies.  However, I was unable to import any of the library components to register them for use by my app.

The following statement:
`import { GoAButton } from "@abgov/vue-components";`

would create the following error:
`ERROR in D:\Projects\GOV-AB\Housing\housing-application-portal\src\index.ts(5,27)
      TS7016: Could not find a declaration file for module '@abgov/vue-components'. 'D:\Projects\GOV-AB\Housing\housing-application-portal\src\node_modules\@abgov\vue-components\vue-components.umd.js' implicitly has an 'any' type.
  Try "npm i --save-dev @types/abgov__vue-components" if it exists or add a new declaration (.d.ts) file containing "declare module '@abgov/vue-components';"`

I was able to use the error to come up with a solution by adding an abgov.d.ts file with the following contents:
`declare module '@abgov/vue-components';`

I believe this should be part of the npm package itself though.

**Comment by Spark450** [comment]
Hey @kirk-govab 
The design system team is focusing on getting the current components released as web components which then can be "wrapped" in different JS frameworks to suit the needs of different projects.

In the interim, I suggest getting in touch with @peterghugov he should be able to help you get up and running!
