### ISSUE TITLE
Skeleton loader

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#264]
**As a:** Developer
**I want:** I want to use the Skeleton loader
**so that:** I can spend more time creating features or capabilities that will provide value to my users and stakeholders 

### Acceptance criteria
- [x] Create web component
- [x] Create React wrapper
- [x] Passing unit tests
- [x] Linting
- [x] update storybook
- [ ] Link pull requests for all new tasks
- [x] Push to Alpha
- [x] Ensure naming convention of variants in alignment with design libraries
- [x] Manual design review

### Presentable outcomes
- [ ] I can show updated storybook documentation during the sprint review

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Related issues:
GitHub issue: 

### Resources:
**Mockups:** [Skeleton loader](https://www.figma.com/file/ylmHeuDMfxnDBnP1VaQYz8/%E2%9D%96-Guidelines-%7C-DIO-DS?node-id=622%3A13694)
**Testing URL:** *[If applicable a URL to the testing branch]*

### Design review 1:

- [x] Page label from "Skeleton loader" to "Skeleton"

<img width="1048" alt="Screen Shot 2022-04-05 at 5 13 13 PM" src="https://user-images.githubusercontent.com/51723535/161871168-45655cca-cb83-448a-b6d1-9b52244f6ea5.png">

**Comment by Spark450** [comment]
Great work @chrisolsen just an update to
