### ISSUE TITLE
UI component - RadioGroup / Radio

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#267]
**As a:** Full stack developer
**I want:** Use the "Radio/Radio group" from the UI library
**so that:** I can spend more time creating features or capabilities that will provide value to my users and stakeholders

### Acceptance criteria
- [x] Create web component
- [x] Create React wrapper
- [x] Align in naming convention between design and development
- [x] Passing unit tests
- [x] Linting
- [x] Include in "canvas" web component storybook
- [x] Push to Alpha
- [x] Manual design review

### Presentable outcomes
- [x] I can show the ui-component in storybook and provide the link to service teams so that they can view the component for themselves

### Sprint Ready Checklist 
Acceptance criteria defined 
Team has defined steps to satisfy acceptance criteria 
Acceptance criteria is verifiable / testable 
External / 3rd Party dependencies identified

### Related issues:
GitHub issue: Blocked by #355 

### Resources:
**Mockups:** [Radio design](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/DIO-DS---Components?node-id=102%3A26)
**Testing URL:** *[If applicable a URL to the testing branch]*

### Design review:

- [x] Change name of component from "Radio Buttons" to "Radio button" (on both left navigation and the h1 on the component page)
- [x] The radio button does not seem to include a focus state, when the user is interacting with it
- [x] On hover the border of the radio button circle should be color "interactive-hover"
- [x] Is it possible to have an error state example on the page as well?
- [x] Change disabled treatment 0.4 opacity. 
- [x] Include a grey HR after the "figma design component" link and before the list of examples to better separate the sections. I will also update the Storybook documentation checklist to reflect this change.

### Design review #2:
- [x] Disabled state is showing as 0.3 sill, Change disabled treatment 0.4 opacity. 
- [x] On hover the border of the radio button circle should be color "interactive-hover" I don't think this style is applied yet.

### Design review #3:
- [x] Disabled state is showing as 0.3 sill, Change disabled treatment 0.4 opacity. 
- [x] The whole radio element should have the 0.4 opacity applied, currently it is only the circle element that has the opacity applied.

**Comment by Spark450** [comment]
Hey @chrisolsen I've finished the first round of review on this, great work!

**Comment by Spark450** [comment]
Hey @chrisolsen finished the second round there is just a couple of things, that didn't seem to get completed let me know if I'm mistaken, thanks!
