### ISSUE TITLE
UI component - Modal

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#270]
**As a:** Full stack developer
**I want:** Use the "Modal" from the UI library
**so that:** I can spend more time creating features or capabilities that will provide value to my users and stakeholders

### Acceptance criteria
- [x] Create web component
- [x] Create React wrapper
- [x] Passing unit tests
- [x] Linting
- [x] update storybook
- [ ] Link pull requests for all new tasks
- [ ] Push to Alpha
- [ ] Ensure naming convention of variants in alignment with design libraries
- [ ] Manual design review

### Presentable outcomes
- [ ] I can show the ui-component in Storybook and provide the link to service teams so that they can view the component for themselves

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy the acceptance criteria 
- Acceptance criteria is verifiable/testable 
- External / 3rd Party dependencies identified

### Resources:
**Mockups:** [Modal](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Components-%7C-DIO-DS?node-id=622%3A13874)
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by Spark450** [comment]
Hey @chrisolsen ,

Just doing the design review on the Modal and I have a few questions

- Are we just doing the basic modal as part of this story and leaving the other variants (callout modal etc. until later?)
- Do we have the mobile variant of this modal built? When I use the inspect tool and change the viewport width the button(s) do not go full width as in the design?

**Comment by chrisolsen** [comment]
@Spark450 We did have a mobile version at one time, but at the time the designs didn't ask for it, so the code got tossed. As for the all the variants, it would make sense to come back to them, since implementing all of them is not a small task.

**Comment by chrisolsen** [comment]
@Spark450 I thought there was a more complex mobile version, but since it is just a 90% width I have made that change.
