### ISSUE TITLE
UI component - Dropdown

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#276]
**As a:** Full stack developer
**I want:** Use the "Dropdown" from the UI library
**so that:** I can spend more time creating features or capabilities that will provide value to my users and stakeholders

### Acceptance criteria
- [x] Create web component
- [x] Create React wrapper
- [x] Passing unit tests
- [x] Linting
- [x] update storybook
- [x] Link pull requests for all new tasks
- [x] Push to Alpha
- [ ] Ensure naming convention of variants in alignment with design libraries
- [ ] Manual design review

### Presentable outcomes
- [ ] I can show the ui-component in Storybook and provide the link to service teams so that they can view the component for themselves

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Related issues:
#558 #559 

### Resources:
**Mockups:** [Dropdown](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Components-%7C-DIO-DS?node-id=700%3A7316)
**Testing URL:** *[If applicable a URL to the testing branch]*

### Design review items:
- [x] Missing high level description
- [x] Desktop Only: After user selects a value from the dropdown, the font weight & color of text inside the input field is incorrect. (Color eye dropped the color and it is shown as #000)
 
Single selection:
- [x] click input field is incorrect. Users should be able to select entire input instead of just the center of the field
- [x] There should be 2 different visual treatments for hover states
- hover on a selected item
- hover on an unselected item

Error: 
- [x] ~~should not have an error unless it is an empty state (applications should not allow users to select an item that generates an error)~~ The error is something that is manually set and in storybook is to show it as an example
- [x] ~~The red is the wrong color.~~
- [x] ~~Missing error text~~ Error text is part of the form-item component, not the dropdown

On mobile:
- [x] blue caret icon should be dark grey (where are the design docs for this?) **Can't replicate this on an Android device**

General:
- [x] Remove filter and multi-select

**Comment by ambroseyau** [comment]
currently reviewing the component

**Comment by Spark450** [comment]
@twjeffery possible usability issue when navigating dropdown menu with keyboard, lets discuss.

**Comment by ambroseyau** [comment]
Finished Reviewing the drop down and provided comments on the selected text font style inside the input field
