### ISSUE TITLE
(Alpha) UI component - Checkbox

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#278]
**As a:** Full stack developer
**I want:** Use the "Checkbox" from the UI library
**so that:** I can spend more time creating features or capabilities that will provide value to my users and stakeholders

**Note:** This story does not include the "indeterminate" checkbox state

### Acceptance criteria
- [x] Create web component
- [x] Create React wrapper
- [x] Passing unit tests
- [x] Linting
- [x] update storybook
- [x] Push to Alpha
- [x] Manual design review

### Presentable outcomes
- [x] I can show the ui-component in storybook and provide the link to service teams so that they can view the component for themselves

### Sprint Ready Checklist 

- Acceptance criteria defined 
- eam has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Related issues:
GitHub issue: Blocked by #355 

### Resources:
**Mockups:** [Checkbox design](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/DIO-DS---Components?node-id=183%3A219)
**Testing URL:** *[If applicable a URL to the testing branch]*

### Design review:

- [x] Change description text (under main heading) from p to h3
- [x] Adjust the vertical alignment of the checkbox label to be more vertically aligned. right now it seems to be sitting a bit "low" (happy to chat about this and talk about potential solutions)
- [x] Remove "usage" section
- [x] Change the headings for all component states from h3 to h4 (e.g. "basic", "checked", "disabled" etc.)
<img width="453" alt="Screen Shot 2022-03-22 at 9 49 44 AM" src="https://user-images.githubusercontent.com/51723535/159532597-4b51a0e0-61cb-4049-9612-ec67e99a0d69.png">

- [x] Remove "States" heading and the following paragraph: "Checkboxes can be checked or unchecked. They have default, focus, hover, disabled and error states. It’s that in-between state that we might consider a “Mix” between “Selected” and “Unselected” options. Indeterminate state is not supported as of now."

- [x] Remove "Usage" heading and the following paragraph: "Use checkboxes when the user can select one or more options.
The fieldset width is responsive to 100% of the layout container while the arrangement is set vertically for ease of scanning and comparing. The fieldset title should be clear, concise, and relevant to the group of options.Add ‘Optional’ only to questions which can be left unanswered. Start all checkboxes with a capital letter. Don’t include punctuations after checkbox label."

- [x] Remove all "do's" and "don'ts"
- [x] Update default color for "Figma design component" text to be "goa-interactive" color (currently that style is being overridden)

- [x] Update "Figma design component" link so that it takes the user right to the "checkbox" component page in figma (https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/Components---DIO-DS?node-id=4482%3A220144)

- [x] The "Error state should be included as is documented in the [Figma design](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/Components---DIO-DS?node-id=1288%3A9159)
- [x] On "hover" the checkbox border should be "goa-hover" and there should be no background color (currently there is a light grey on hover). 
- [x] On "hover" the "hand" cursor should be persistent to provide the user with another affordance that the control is interactive. Currently when the users hovers over the "box" visual element the cursor changes to the "pointer" variant
- [x] On "hover" the checkbox icon background should be the "goa-hover" color
- [x] Error and checked to be supported
- [x] Checked and disabled to be supported

**Comment by Spark450** [comment]
@chrisolsen The component looks good (all the issues in the design review have been resolved) However, the "usage" section in storybook docs has been brought back by accident would you be able to remove it to get this issue over the line?
Thanks!

<img width="883" alt="Screen Shot 2022-03-29 at 9 16 29 AM" src="https://user-images.githubusercontent.com/51723535/160658141-75f73205-17c1-414d-a988-3763983457ec.png">

**Comment by bluekurinji** [comment]
The Usage section is removed now in storybook
