### ISSUE TITLE
(Beta) UI component - Badge

### ISSUE THREAD

**Issue by chrisolsen** [GovAlta/ui-components#284]
**As a:** Full stack developer
**I want:** Use the "badge" from the UI library
**so that:** I can spend more time creating features or capabilities that will provide value to my users and stakeholders

### Acceptance criteria
- [x] Create web component
- [x] Create React wrapper
- [x] Passing unit tests
- [x] Linting
- [x] Include in "canvas" web component storybook
- [x] Push to Alpha
- [x] Manual design review

### Presentable outcomes
- [x] I can show the ui-component in storybook and provide the link to service teams so that they can view the component for themselves
- [x] Show the service teams how to use the component in a sample project in either React or Angular 

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- acceptance criteria is verifiable / testable 

### Related issues:
GitHub issue: Blocked by #355 

### Resources:
**Mockups:** [Badge design](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/DIO-DS---Components?node-id=458%3A16984)
**Images:** ![image](https://user-images.githubusercontent.com/41582/145474826-f86f8714-07a5-4f7f-97f8-2c66d061caf4.png)
**Testing URL:** 
https://ui-components-ui-components-dev.os99.gov.ab.ca/?path=/docs/components-badge--page

**Comment by Spark450** [comment]
Design review will be completed once issue #354 has been completed.

**Comment by Spark450** [comment]
Noticed a styling issue with the "badge with text-only" variant @bluekurinji to investigate and provide options.

**Comment by Spark450** [comment]
Issue blocked by issue #417 (need to get definition on what constitutes a Beta component)

**Comment by Spark450** [comment]
Right now we don’t have the institutional knowledge to easily solve the accessibility knowledge gap. The issue will remain blocked until we can get some help/expertise to help out.
