### ISSUE TITLE
Develop "design review" method for Figma components

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#308]
## Overview
There should be standards in place that designers can follow that will lead to the production of high-quality design artifacts.

## Tasks
- [ ] Create Front end design-focused design standards for creating, testing, and the handoff styles, components, and patterns.

**Comment by twjeffery** [comment]
I'm not sure what would be useful, but with our new design tool, we are able to align more closely with how we are building out each component in design and in code. 

Article on [How to unify anatomy and props across code and design tools](https://medium.com/eightshapes-llc/crafting-ui-component-api-together-81946d140371)

Is this worth aligning on between design and development?
