### ISSUE TITLE
Create a design review method

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#354]
**As a:** Evaluator of completed design system components
**I want:** Verify the quality and completeness of a design system component
**so that:** Teams consuming the design system components have access to high-quality components and styles that they can use/reuse in their service

### Acceptance criteria
- [x] Create a definition of "quality" for guidelines, components, and patterns
- [x] Inclusion of manual accessibility checks
- [x] Documentation check (does this match developed component)
- [x] Inclusion of bug logging procedure for defects against an item that is undergoing design review
- [x] Creation of a checklist that can be used to verify the quality of a design system guideline and component
- [x] A materials created for this story will be peer-reviewed by at least one other designer and Sam Kothari (Lead QA automation tester)

### Presentable outcomes
N/A

### Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
3. - [x] Team has defined steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified

### Related issues:
GitHub issue: *[If applicable a "# link" to the GitHub issue]*

### Resources:
**Mockups:** *[If applicable URL to or the name of the mockup(s) in Figma]*
**Testing URL:** *[If applicable URL to the testing branch]*

**Comment by Spark450** [comment]
@twjeffery this will be the first "user story" going through the sprint, so when you're ready please get in touch and we can go through the format together and make any updates to the format/content as necessary 👍

**Comment by twjeffery** [comment]
Completed a first version of this and shared in confluence for review and feedback from the rest of the team. We will continue to refine this process as we use it with each component review. 

https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2216329231/Design+review+process+-+Developed+components

**Comment by Spark450** [comment]
This issue is waiting for a review by Sam Kothari
