### ISSUE TITLE
Button design update

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#385]
**As a:** Design system team
**I want to:** Extend the existing button documentation, including when and how you use the borderless and danger variants
**so that:** Teams will have access to these additional button variants and usage documentation

### Acceptance criteria

- [x] Research and examples from DIO gathered to inform approach on use of destructive and borderless buttons
- [x] Figma component is updated and extended to include borderless and danger variants
- [x] New proposed design is reviewed with design system team for feedback and approval
- [x] Proposed design update is reviewed for feedback with front end design guild
- [x] Proposed design is reviewed and "approved" by CPE
- [x] Design documentation is updated an put into "new" format
- [x] component and documentation update is communicated to all DIO front end designers.
- [x] Explore options for "pressed" state that works across all variants.

### Presentable outcomes
- [x] Usage documentation is presented during sprint review.

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Related issues:
#457 Currently there is a discrepancy between font sizes of ui-component and design component for the small button. Coordinate with FED picking up the issue above.

### Resources:
**Mockups:** [Button](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/Components---DIO-DS?node-id=434%3A15466)
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by twjeffery** [comment]
Final recommendation put on hold as we just received updates to the design system from CPE that effects all button states. The tertiary button from CPE now is closer to a borderless button.

**Comment by twjeffery** [comment]
I have put together a few [options](https://www.figma.com/file/jDsIoiKh5ViZRWJdS0Dgtf/Buttons?node-id=3%3A378) based on the updates from CPE to go through together. I have booked a meeting to discuss further.

**Comment by twjeffery** [comment]
I've finished putting together the updated documentation for this, also including the icon button.

For review here:
https://www.figma.com/file/jDsIoiKh5ViZRWJdS0Dgtf/Buttons?node-id=976%3A12512

Once approved I will move to the component library and publish.

**Comment by Spark450** [comment]
Hey @twjeffery I think things are looking good, would you be able to add the publication status element to these docs you showed in the footer docs. Once that's done I think we can close this off.

Great work!
