### ISSUE TITLE
Evaluate on how we are doing unit tests

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#389]
**As a:** Design system team developer
**I want:** Want to create appropriate unit tests
**so that:** We ensure code quality and are using our time effectively.  

### Acceptance criteria
- [x] Have the right arrangement of unit tests for ui-components.
- [x] appropriate tests become part of the [developer guidelines](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2206924906/Developer+Guide). 

### Presentable outcomes
- [x] N/A

### Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
3. - [x] Team has defined steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified

### Related issues:
GitHub issue: *[If applicable a "# link" to the GitHub issue]*

### Resources:
**Mockups:** *[If applicable a URL to or the name of the mockup(s)]*
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by tarynlaramie** [comment]
created first draft in developer guidelines. waiting for feedback from @chrisolsen
