### ISSUE TITLE
Create mockups for landing page design for storybook design system website

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#390]
**As a:** Consumer of the design system website
**I want:** Get a general understanding of the design system, what is, why it exists, why is exisits the way it does (web etc.)
**so that:** I can make an educated decision on when/how to include it 

### Acceptance criteria
- [x] Create a mockup that can be built within the constraints of storybook
- [x] Communicate:
  - [x] What is the design system
  - [x] Why does it exist
  - [x] Why should I use it
  - [x] How to get in touch with design system team
  - [x] And whatever else is discovered.

### Presentable outcomes
- [x] N/A - built version will be shared

### Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
3. - [x] Team has defined steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified

### Related issues:
GitHub issue: *[If applicable a "# link" to the GitHub issue]*

### Resources:
**Mockups:** [*[If applicable a URL to or the name of the mockup(s)]*](https://www.figma.com/file/qWGWDvULAAZuVaDpXCRzqP/DS-Resource-Website?node-id=961%3A13342)
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by twjeffery** [comment]
Initial version completed here: https://www.figma.com/file/qWGWDvULAAZuVaDpXCRzqP/DS-Resource-Website?node-id=999%3A13425

Need to have a discussion with development to ensure design can be built within current tool (Storybook). 

Looking forward to review and discussion with rest of the team.

**Comment by twjeffery** [comment]
After the initial landing page exploration, we no longer are constrained to working within Figma. I extended the environmental scan from issue #393 to include navigation and site structure and designed out a more ideal version to include a first version with an updated site structure and navigation. 

[Updated landing page design](https://www.figma.com/file/qWGWDvULAAZuVaDpXCRzqP/DS-Resource-Website?node-id=1082%3A15142) within Figma for review and discussion with the rest of the team.
