### ISSUE TITLE
Environmental scan of other design systems (content design focus)

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#393]
**As a:** design system team looking to improve how we document our design system
**I want:** Understand how other jurisdictions communicate their design systems
**so that:** Use/reuse the best ideas for our design system.

### Acceptance criteria
- [x] Environmental scan of other gov and private sector design systems.
- [x] Assemble a list of recommendations of enhancements to design system documentation

### Presentable outcomes
- [x] Show to speak to designs and research conducted on design system documentation

### Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
3. - [x] Team has defined steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified

### Related issues:
GitHub issue: #390 

### Resources:
**Mockups:** *[If applicable a URL to or the name of the mockup(s)]*
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by twjeffery** [comment]
initial scan and summary completed here: https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2222850098/Environmental+scan+of+other+design+systems 

We will continue to reference and update this as we build out the design for the landing page and component page.
