### ISSUE TITLE
Spike - Feature flags

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#401]
**As a:** Developer on the design system team
**I want:** Try to use feature flags
**so that:** We can control how and when components are delivered and communicate the component status to end-users.

### Acceptance criteria
- [x] Wrap a web component in a feature flag so that it will be available in alpha and beta. GoAAppHeader
- [x] wrap a web component in a feature flag so that it will be available in alpha, beta and prod. GoABadge
- [ ] wrap a react component in a feature flag so that it will be available in alpha and beta. use the same component as the web-component - GoAAppHeader
- [ ] wrap a react component in a feature flag so that it will be available in alpha, beta and prod. use the same component as the web-component - GoABadge
- [ ] try to use the component list to show the components status in storybook. wc GoAAppHeader and GoABadge
- [ ] confirm with team that the two selected components are appropriate to go to those environments. adjust if necessary

Talk to Taryn for some ideas:
- use constants file that has an array of objects where each object represents a component. each component object will have a status and description to start. we will need this file for other features later too
- spike 1: use this file to control which components are exported in the index file based on their status. might have to look at dynamic includes or something
- if spike 1 does not work, spike 2: create different build configurations to load environment specific index files. will have to make sure build workflows build the source with the appropriate configuration for the branch
Spike Result:
The index file determines which components are exported.
The index file cannot dynamically control which components are exported.
A combination of both the component list and environment specific index files was used.  This will make the component list the 'source of truth' for which components are available in which environment.

### Presentable outcomes
N/A

### Resources:
**Mockups:** *[If applicable a URL to or the name of the mockup(s)]*
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by tarynlaramie** [comment]
I've pushed a work in progress branch to [https://github.com/tarynlaramie/ui-components/tree/spike-feature-flags-component-based](https://github.com/tarynlaramie/ui-components/tree/spike-feature-flags-component-based)

**Comment by ravi-dio** [comment]
I was able to install the @etchteam/storybook-addon-status plugin to control the display of component status. This includes custom statuses in addition to beta, stable, deprecated & releaseCandidate.

Next steps are to add a storybook-level JSON document detailing the status of each component and to add a component-status page in Storybook that lists this information.

**Comment by ravi-dio** [comment]
<img width="710" alt="Screen Shot 2022-05-02 at 9 43 53 AM" src="https://user-images.githubusercontent.com/103287169/166464534-1ee8d1bc-f818-4428-a4f9-23a342fec8db.png">
<img width="829" alt="Screen Shot 2022-05-02 at 8 27 44 AM" src="https://user-images.githubusercontent.com/103287169/166464538-7f2b849a-bcfa-48b4-834c-f1edfe3cdf37.png">
