### ISSUE TITLE
Create criteria for Alpha ui-component release

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#416]
**As a:** Consumer of the design system documentation
**I want:** Understand that I am looking at an alpha component, what that means, and how I can use it
**so that:** I can determine, when, how, where to use a ui-component in my service. 

### Acceptance criteria
- [x] Approach allows backlog of ui-components to make their way into "Alpha" quickly
- [x] "Alpha" criteria, will be reviewed with design system team and feedback will be incorporated before going into the final criteria
- [x] Criteria will be published to Confluence

### Presentable outcomes
- [x] N/A, will be presented along with Beta component, which will allow for better comparison by consumers.

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Related issues:
GitHub issue: #417 #421 

### Resources:
**Mockups:** *[If applicable a URL to or the name of the mockup(s)]*
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by tarynlaramie** [comment]
@Spark450 here's a couple suggestions from the technical side that we have in the Developer Guide: https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2206924906/Developer+Guide#Web-Components

**Comment by ambroseyau** [comment]
Link the confluence
https://goa-dio.atlassian.net/l/c/oDC1wPbi
