### ISSUE TITLE
Create criteria for Beta ui-component release

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#417]
**As a:** Consumer of the design system documentation
**I want:** Understand that I am looking at a beta component, what that means, and how I can use it
**so that:** I can determine, when, how, where to use a ui-component in my service. 

### Acceptance criteria
- [x] "Beta" criteria, will be reviewed with design system team and feedback will be incorporated before creating the final criteria
- [x] Criteria will be published to Confluence

### Presentable outcomes
- [x] Alpha and Beta release components will be shared during sprint review and differences between each will be discussed.

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Related issues:
GitHub issue: #416  #421
Note: This issue is blocking **#418** 

### Resources:
**Mockups:** *[If applicable a URL to or the name of the mockup(s)]*
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by ambroseyau** [comment]
Link the confluence
https://goa-dio.atlassian.net/l/c/oDC1wPbi
