### ISSUE TITLE
Shall add a property to allow user to remove text-transform for the GoABadge

### ISSUE THREAD

**Issue by solittlework** [GovAlta/ui-components#419]
As a user, I'd like to remove the 'text-transform: capitalize;' in the GoABadge component. The class is dynamic in the component, which means the overwriting here is not convenient. I am thinking of whether we can add property on it to allow the user to control the text-transform. Or, we just delete this property from the stylesheet.

https://github.com/GovAlta/ui-components/blob/a9c8ee5bebd12c29a0d2c9eb56db2e3730c30d22/libs/core-css/src/lib/styles/v2/badge.scss#L23

**Comment by Spark450** [comment]
@solittlework @chrisolsen mentioned that you and he have had discussions of a similar nature in the past and you could use a css override to get around this.

As we are heads down on getting our web components version of the library stood up and out the door, we won't be putting time into painting the core-css.

If you have any other questions please reach out to Chris directly. He would be happy to discuss this further.

**Comment by solittlework** [comment]
Talked with Chris and it looks this feature is included in the alpha version. I am going to close this task.

**Comment by solittlework** [comment]
Talked with Chris and it looks this feature is included in the alpha version. I am going to close this task.
