### ISSUE TITLE
(Alpha) UI component - Footer

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#427]
**As a:** Full stack developer
**I want:** Use the "Footer" from the UI library
**so that:** I can spend more time creating features or capabilities that will provide value to my users and stakeholders

Note: Reach out to Platform team, ADSP has built "footer with links to meta information" variant that could be a used as a starting point. Reach out to @jonathanweyermann 

### Acceptance criteria
- [x] Create web component
- [x] Create React wrapper
- [x] Passing unit tests
- [x] Linting
- [x] Include in "canvas" web component storybook
- [x] Push to Alpha
- [ ] Manual design review
- [ ] Ensure that ui-component name and Figma component name are aligned

### Presentable outcomes
- [ ] I can show the ui-component in Storybook and provide the link to service teams so that they can view the component for themselves

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Related issues:
GitHub issue: Blocked by #355 

### Resources:
**Mockups:** [Footer](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/Components---DIO-DS?node-id=3800%3A118527)
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by DarylChiew** [comment]
Is there a scheduled release date for this component?

**Comment by DarylChiew** [comment]
Thanks for the update!
