### ISSUE TITLE
Alpha - Microsite header - feedback and environment variant

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#440]
Also include Dev, test, prod with or without version number

**As a:** Full stack developer
**I want:** Use the "feedback" and "environment" variant of the callout from the UI library
**so that:** I can spend more time creating features or capabilities that will provide value to my users and stakeholders

_Discuss desired behaviour of "feedback" text link with Thomas_

### Acceptance criteria
- [x] Create web component
- [x] Create React wrapper
- [x] Passing unit tests
- [x] Linting
- [x] Include in "canvas" web component storybook
- [x] Push to Alpha
- [x] Manual design review
- [ ] Ensure that ui-component variant naming scheme and Figma component variant names are aligned

### Presentable outcomes
- [ ] I can show the ui-component in Storybook and provide the link to service teams so that they can view the component for themselves

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Resources:
**Mockups:** [Microsite header - Feedback](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/Components---DIO-DS?node-id=458%3A15883)
[Feedback pattern](https://www.figma.com/file/UbIKwjbxuPUvoFNYvMBGpe/%5BWIP%5D-Patterns---DIO-DS?node-id=1239%3A1483)
**Testing URL:** *[If applicable a URL to the testing branch]*

### Design review:

- [x] Change component name from "Service level header" to "Microsite header"
- [x] Include "description" section below h1 on main page "Use the microsite header to communicate to the user what stage the service is at, and to establish an official connection to Alberta.ca when the service is on a subdomain. You can also use the microsite header to gather feedback throughout your service, and to show an application version number for quick reference by the service team."
- [x] Include hr after "figma design component" before the first example to better separate the sections
- [x] Put "Alpha" variant label below the first example (see "beta" variant on page)
- [x] Use color variable "goa-color-text" for text color for "tag" and descriptive text that is dark
- [x]  Use color variable "goa-color-text-light" for all "white" text in the components
- [x] Use color variable color-grey-600 for the "version text" in the top right corner
- [x] Ensure that text links in the Microsite header have the appropriate "goa-color-interactive and hover" treatments.

### Design review 2:
- [x] Include "description" section below h1 on main page "Use the microsite header to communicate to the user what stage the service is at, and to establish an official connection to Alberta.ca when the service is on a subdomain. You can also use the microsite header to gather feedback throughout your service, and to show an application version number for quick reference by the service team."
- [x] Include hr after "figma design component" before the first example to better separate the sections see screenshot below
<img width="1069" alt="Screen Shot 2022-03-31 at 11 14 40 AM" src="https://user-images.githubusercontent.com/51723535/161122769-a56a9063-79c9-437d-8fb9-855971f13749.png">

- [x] For "Alpha" badge use color variable "--goa-color-status-warning"

**Comment by twjeffery** [comment]
In case it's helpful: I created a draft of a pattern around _gathering feedback within your service_ that gives some context for how the feedback variant would be used.
https://www.figma.com/file/UbIKwjbxuPUvoFNYvMBGpe/%5BWIP%5D-Patterns---DIO-DS?node-id=1239%3A1483

**Comment by twjeffery** [comment]
@chrisolsen @Spark450 I updated the microsite header throughout Figma to include the link to Alberta.ca

<img width="920" alt="image" src="https://user-images.githubusercontent.com/82968683/159570038-283be79f-9a99-4351-bfe9-abc40d0b52b3.png">

**Comment by Spark450** [comment]
@chrisolsen Great work on the update, just a few items, let me know if you have any questions, Thanks!

**Comment by Spark450** [comment]
@chrisolsen Just a couple of things, let me know if you have questions about the layout, Thanks!
