### ISSUE TITLE
Create additional text variable "1rem" value and update sm button text size to 1rem value

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#457]
**As a:** Design system team
**I want:** Have the font variables defined in code to match the ones defined in the Figma design libraries
**so that:** Font sizing is consistent between the ui-components and Figma components.

### Note: 

- 1rem = 16px
- Currently the "small" button uses a 16px font size in the Figma designs but the ui-component uses the "fs-small" variable of .875rem
- Decisions on how to proceed will be design led but involve input from design and development

### Acceptance criteria
- [x] Ensure values defined in our Figma component libraries have matching values in the UI components.
- [ ] font variables and/or Figma designs are updated

### Presentable outcomes
- [ ] I can show updated documentation and Figma specs during the sprint review

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Resources:
**Mockups:** [Button](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/Components---DIO-DS?node-id=434%3A15466)
[Typography](https://www.figma.com/file/ylmHeuDMfxnDBnP1VaQYz8/Guidelines---DIO-DS?node-id=3%3A2)
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by ambroseyau** [comment]
Had a discussion with the DS developers and we have finalized the token names:
https://goa-dio.atlassian.net/l/c/K34PkT1r

Next step:
Discuss with DS designers when and how to update the figma file

**Comment by Spark450** [comment]
Closed, will cover as part of #567
