### ISSUE TITLE
Circular progress indicator naming and documentation update

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#458]
**As a:** Design system team
**I want:** The name of the design and ui-component to match
**so that:** collaboration and communication between service team designers and developers is easier

### Acceptance criteria
- [x] Ensure the naming convention defined in our Figma component libraries match the name in the UI component
- [x] Work will be design-led but will be a collaboration between design and development.

### Presentable outcomes
- [ ] During sprint review inform where name change has occurred, (either design or development)

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Resources:
**Mockups:** [Loading/progress indicator/spinner](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/Components---DIO-DS?node-id=622%3A13604)
[ui-component](https://ui-components-ui-components-dev.os99.gov.ab.ca/?path=/docs/components-spinner--sizes)

### Design review 1:

- [x] Include the 2 sizes of progress indicators shown in the Figma mockup as per discussion.
- [x] Show inline progress indicator variant on Storybook page

<img width="1063" alt="Screen Shot 2022-04-05 at 9 06 18 AM" src="https://user-images.githubusercontent.com/51723535/161797815-bebe0ba0-ac9f-4431-b25f-bc0d053ebc3f.png">

### Design review 2:

- [x] "message" text element should use typography and color variables
- [x] Remove tabset from "Properties" section
- [x] Figma link not linking to progress indicator page Update Figma link with [this link](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Components-%7C-DDI-DS?node-id=3799%3A118526)

**Comment by twjeffery** [comment]
@chrisolsen As discussed, name change needed for component from _Spinner_ to _Circular progress indicator_.

This allows us to directly reference the usage and intent, as well as leave it open for other "progress indicators" along the way. eg. linear progress indicator

**Comment by Spark450** [comment]
> oration and communica

Hey @chrisolsen and @twjeffery I'm not seeing the two different sizes included in Storybook, am I missing something?

**Comment by twjeffery** [comment]
@Spark450 @chrisolsen There should be two size variants included in Storybook, the same as is included in the Figma design library.

**Comment by Spark450** [comment]
Looking good @chrisolsen just a few itesm that I found during this round of review.

**Comment by chrisolsen** [comment]
@Spark450 
The message text inherits color and font from the values defined for the `body` element. I have changed the color values used for that css element to the `--goa-color-text` value, but I don't think that re-specifying that higher up the chain is a good idea.
