### ISSUE TITLE
Provide "design review" checklist for developer to use when building ui-components.

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#461]
**As a:** Design system team developer
**I want:** Reference the criteria used during the ui-component review 
**so that:** I can resolve defects before they reach the design review process

### Acceptance criteria
- [x] Design review criteria checklist is provided to the development team in a method of delivery that suits them best in their workflow
- [x] Criteria is reviewed by product owner or another designer.

### Presentable outcomes
N/A

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Resources:
**Mockups:**
**Testing URL:** [Checklist](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/edit-v2/2250407955)

**Comment by ambroseyau** [comment]
Everything looks good!

On additional thing we can also consider is to check and make sure the component variants are visually separated. 

It is currently hard to quickly look for a specific component variant on some of the component pages (not clear separations)

**Example:**    
https://ui-components-ui-components-dev.os99.gov.ab.ca/?path=/docs/components-inputs--icon-buttons

**Comment by Spark450** [comment]
> Everything looks good!
> 
> On additional thing we can also consider is to check and make sure the component variants are visually separated.
> 
> It is currently hard to quickly look for a specific component variant on some of the component pages (not clear separations)
> 
> **Example:** https://ui-components-ui-components-dev.os99.gov.ab.ca/?path=/docs/components-inputs--icon-buttons

Great!, thanks for the feedback Ambrose
