### ISSUE TITLE
Align typography variables (fs,fw, lh) from the ui-components library with the Figma designs

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#473]
**As a:** Design system team
**I want:** Our designers and developers to be using the same typography specification 
**so that:** developer and designer communication on service teams can be clear 

### Acceptance criteria
- [x] Updated Typography specifications from CPE are incorporated into both the ui-library and Figma libraries
  - [x] Font weight
  - [x] Font size
  - [x] Line height
- [x] All font variables have been created to support the typography specs of the design system
  - [x] Any variables that need to be created and have not been created are communicated to the development team and product owner

**Comment by ambroseyau** [comment]
Review New Typography Link:
https://www.figma.com/file/HjKpjtVGLtf72mKHuWBAQF/%5BXD-000%5D-Typography?node-id=3%3A378

I had a chance to talk to Saul and Tom yesterday and they are hoping to discuss <h3> with the team before we publish
