### ISSUE TITLE
Update spacing variables

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#474]
**As a:** Design system team
**I want:** Have the spacing variables documented
**so that:** So that the code and design spacing values can be aligned

### Note: 
Currently defined values in ui-components library
- 1rem = 16px
-spacing-1: 0.5rem;
-spacing-2: 0.875rem;
-spacing-3: 1.75rem;

### Acceptance criteria:
- [x] If there are variables that need to be edited or created document those changes (clearly note updates, additions, and removals)

### Presentable outcomes:
- [x] Discuss updated documentation and Figma specs during the sprint review

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Resources:
**Documentation** https://goa-dio.atlassian.net/l/c/bVq1U1NU

**Mockups:** https://www.figma.com/file/wXpcgeeOarkCv5ItVRTVFZ/%5BXD-000%5D-Design-Tokens---Spacing?node-id=3%3A404

**Testing URL:** https://www.figma.com/file/wXpcgeeOarkCv5ItVRTVFZ/%5BXD-000%5D-Design-Tokens---Spacing?node-id=3%3A378

**Comment by ambroseyau** [comment]
The goal of the spacing variables is to ensure that all the team would be using these variables instead of creating new spacing specs moving forward.

Please conduct an audit in the proposed spacing and review this with the design team.
https://www.figma.com/file/wXpcgeeOarkCv5ItVRTVFZ/%5BXD-000%5D-Design-Tokens---Spacing?node-id=3%3A378

**Comment by twjeffery** [comment]
I had a look through to review @ambroseyau. It all looks good. I updated the spacer component to align as well. How do we want to actually work these into the components themselves as next steps?

Also, in how we do that in Figma per component -- I am still interested in defining these as design tokens (we could do through a design token plugin) that would then be used in our components and be able to be exported to code. Interested to hear what you had in mind.

**Comment by Spark450** [comment]
@ambroseyau If you feel we are at a point where you'd want to investigate plugins that might help us integrate these tokens into Figma you could pick up this story
https://github.com/GovAlta/ui-components/issues/597

Let me know.

**Comment by ambroseyau** [comment]
@twjeffery  Based on our discussion last week, we will need to create a user story for the rollout plan. This plan should include:
- Figma Update
- Dev Update
- Demo examples of components to devs and architect
- identify what components to build
- Collaboration between dev and designers
- create live documentation
- etc.

**Comment by Spark450** [comment]
> @twjeffery Based on our discussion last week, we will need to create a user story for the rollout plan. This plan should include:
> 
> * Figma Update
> * Dev Update
> * Demo examples of components to devs and architect
> * identify what components to build
> * Collaboration between dev and designers
> * create live documentation
> * etc.

Hi @twjeffery  @ambroseyau Thanks for outlining these steps to get the work done.

I will create a user story for this work. I think it would be great for us to investigate those possible design token plugins that might help us out ahead of the actual implementation.
