### ISSUE TITLE
Clear ('x') icon doesn't fire _change event on goa-input

### ISSUE THREAD

**Issue by DarylChiew** [GovAlta/ui-components#492]
### Describe the bug
When using the `<goa-input>` web component, after typing in 1 or more characters, hovering over the input displays a clear button in the right side of the input box.

![image](https://user-images.githubusercontent.com/94495271/159553402-fade4dfc-0ae9-4cf5-b77a-f6b013b74296.png)

Clicking on the 'x' clears the text, but the `_change `event on the `goa-input` control is not fired.

### What is the level of criticality
Medium - One of the other input events can be hooked into, but then I can't make use of the `_change `event since both events will get fired.

### To Reproduce (include pictures or video if helpful)
Steps to reproduce the behaviour:
1. Create an angular project (although I'm sure any web project that can integrate the web components will work).
2. Use something similar to the following html:
```
<goa-input leadingicon="search" type="search" placeholder="Search for an item"
    (_change)="onSearchChange($event)"
></goa-input>
```
3. Implement the `onSearchChange `event handler.  Add `console.log(...)` to help with debugging.
4. Run the app and note that the `onSearchChange `event handler is fired when text is entered but is *not* fired when the 'x' is clicked.

### Expected behaviour
When the 'x' icon is clicked in the input control, the text box should be cleared and the _change event fired to indicate the text box is now empty.

#### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome, v99.0.4844.74
 - @abgov/web-components: v1.0.0-alpha.23

Duplicate of: https://github.com/GovAlta/ui-components/issues/658

**Comment by Spark450** [comment]
@DarylChiew are you able to handle _trailingIconClick event and clear the attributes value manually?

**Comment by DarylChiew** [comment]
@Spark450 it does work that way, but using `type="search"` causes 2 'x's to show up.
![image](https://user-images.githubusercontent.com/94495271/165565764-0c2a323f-383a-4e83-a8db-365ac648843b.png)

Workaround was to use `type='text'` and .  Should `search` be removed?  Or are there still plans for this type?

**Comment by Spark450** [comment]
> @Spark450 it does work that way, but using `type="search"` causes 2 'x's to show up. ![image](https://user-images.githubusercontent.com/94495271/165565764-0c2a323f-383a-4e83-a8db-365ac648843b.png)
> 
> Workaround was to use `type='text'` and . Should `search` be removed? Or are there still plans for this type?

@chrisolsen are you able to reproduce this on your end and investigate further? I think the "black x" should show and blue one should not (from a visual perspective)
