### ISSUE TITLE
more descriptive git commit messages for feat: and fix commits

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#509]
Find out what consumers of release messages would find meaningful from commit messages.
-Who is the audience for commit message? (devs, product owner)
-detail out this section in the developer guide

**Comment by tarynlaramie** [comment]
Commit messages are used in the CICD pipelines to create appropriate version numbers for NPM packages and communicated in the Slack Channel.  The commit messages can also be used to link pull requests to issues.

To have a Patch release e.g. 0.0.1 to 0.0.2
`fix(#12): descriptive message that will appear in the release notes and slack channel`

To have a Minor release e.g. 0.0.2 to 0.1.0
`feat(#34): another descriptive message that will appear in the release notes and slack channel`

To have a Major release e.g. 0.1.0 to 1.0.0
`BREAKING CHANGE: some other descriptive message that will appear in the release notes and slack channel. Closes #56.`

https://github.com/semantic-release/semantic-release
https://www.conventionalcommits.org/en/v1.0.0-beta.3/#summary
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by tarynlaramie** [comment]
developer guide updated
https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2206924906/Developer+Guide
