### ISSUE TITLE
Angular-Material buttons changing color on hover when disabled

### ISSUE THREAD

**Issue by solittlework** [GovAlta/ui-components#51]
Migrated from GitHub:
Original reporter: @waltermesquita 

### Summary

Angular-Material buttons changing color on hover when disabled

### Steps to reproduce

- On an Angular project using the angular-material styles:
- Add a disable button to a component;
- Hover the disabled button;
- Verify that the color of the button will change as if it were enabled.

### Environment

- @abgov/angular-material-components - version 1.1.0;
- Chrome browser;

### What is the current *bug* behavior?

The color of the button will change as if it were enabled.

### What is the expected *correct* behavior?

The disabled button should not be affected when it is hovered.

### Relevant logs and/or screenshots

(Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's tough to read otherwise.)

### Possible fixes / Bugfix branch

(link to bugfix branch or file/line of code believed to be problem)

**Comment by Spark450** [comment]
Will reevaluate with web component versions.

**Comment by Spark450** [comment]
On old version of the library.
see new Button component in supported library
https://ui-components-ui-components-dev.os99.gov.ab.ca/?path=/docs/components-button--page
