### ISSUE TITLE
Relabel the heading styles in figma to make the heading tags more visible

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#518]
### Currently our heading tags naming format is too long for the developers to see (green highlight)

![image](https://user-images.githubusercontent.com/11575877/161892526-28760e3d-4746-422b-a54c-402e063bab71.png)

Once #543 is complete ,please go to the Figma file and update the heading styles.

**Comment by twjeffery** [comment]
I think you will find that there isn't a great way to handle this in Figma. The current naming for our typography is just (desktop or mobile)+(Type style) =  eg. "Desktop/Header 1".

When it is brought in from an external library (the guidelines design library) it adds DIO Typography to the front of the name.

**Comment by Spark450** [comment]
Not solvable in Figma
