### ISSUE TITLE
Update Typography documentation to reference new specifications (design)

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#527]
Note: typography update may be subject to change.

**As a:** Service team designer
**I want:** To understand how to use the new typography specification in my designs 
**so that:** That my designs have a clear hierarchy and are compliant with the brand standard.

### Acceptance criteria
- [x] Documentation incorporates [specs for font-size, line-height, font-weight, and how these combine to form the font styles](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2261745761/Design+Tokens)
- [x] Figma text styles are updated and extended where required.
- [x] Example pages are included
- [x] Typography tokens are included
- [x] Proposed design is reviewed and "approved" by CPE
- [x] Design documentation is updated an put into "new" format
- [x] component and documentation update is communicated to all DIO front end designers.
- [x] Design review

### Presentable outcomes
- [x] documentation can be presented during sprint review.

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Related issues:
#473

### Resources:
**Mockups:** [Typopgrahy](https://www.figma.com/file/ylmHeuDMfxnDBnP1VaQYz8/%E2%9D%96-Guidelines-%7C-DIO-DS?node-id=3%3A2)
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by twjeffery** [comment]
@Spark450 Documentation created and updated along with the related design tokens. I need some more description for how we intend to use each, it would be good to discuss together what we want to include. 

https://www.figma.com/file/ylmHeuDMfxnDBnP1VaQYz8/%E2%9D%96-Styles-%7C-DDI-DS?node-id=3%3A2
