### ISSUE TITLE
Angular RadioGroup  showing as invalid even before it is touched

### ISSUE THREAD

**Issue by solittlework** [GovAlta/ui-components#53]
Migrated from GitLab
Original Reporter: @waltermesquita 

### Summary

Angular RadioGroup  showing as invalid even before it is touched

### Steps to reproduce

1. Add a RadioGroup to a component and set it as required;
2. Bind the RadioGroup to a reactive form via the 'formControlName' directive;
3. Verify that the RadioGroup will be styled in red (error state) even while it is pristine and not touched.

### Environment

- Package version: 0.7.60
- Browser: Chrome.

### What is the current *bug* behavior?

The RadioGroup shows in red (error state) even while it is pristine and not touched.

### What is the expected *correct* behavior?

The component should only show in error state after it has been touched.

### Relevant logs and/or screenshots

(Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's tough to read otherwise.)

### Possible fixes / Bugfix branch

(link to bugfix branch or file/line of code believed to be problem)

**Comment by Spark450** [comment]
Will reevaluate with web component versions.

**Comment by Spark450** [comment]
Old version, see new ui-component library
https://ui-components-ui-components-dev.os99.gov.ab.ca/?path=/docs/components-radio-button--basic
