### ISSUE TITLE
Design pattern template

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#534]
**As a:** Design system team
**I want to:** Create a pattern/framework that can be used by the pattern squads to document their patterns
**so that:** Documentation outputs will be consistent from team to team, making it easier for a consumer of patterns to navigate between patterns.

### Acceptance criteria

- [x] Pattern template will reference [co-deisgn session outputs](https://miro.com/app/board/uXjVOBMp9vc=/?invite_link_id=179656211417)
- [x] New method of working on patterns is documented and shared with squad team members

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Resources:
**Mockups:** 
**Testing URL:** [New way of working on patterns](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2286551153/WIP+-+Outline+of+proposal+for+a+change+to+the+structure+of+the+pattern+working+groups)

**Comment by twjeffery** [comment]
As discussed as a group, I have outlined a proposal for a change to the structure of the pattern working groups, and a reprioritization of the work overall to incorporate the increased capacity of the design system team and a new method of engagement from the service teams.
https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2286551153/WIP+-+Pattern+squad+working+groups+-+Outline+of+proposal+for+a+change+to+the+structure+of+the+pattern+working+groups


I created a template as a starting point for documentation within Figma, but as each pattern has a different scope and applicable guidance, it will only be so helpful as a common starting point. https://www.figma.com/file/UbIKwjbxuPUvoFNYvMBGpe/?node-id=1610%3A207868
