### ISSUE TITLE
Angular RadioGroup component not loading from state when used with reactive forms

### ISSUE THREAD

**Issue by solittlework** [GovAlta/ui-components#54]
Migrated from GitLab
Original Reporter: @waltermesquita 

### Summary

Angular RadioGroup component not loading from state when used with reactive forms

### Steps to reproduce

1. Bind the component to a FormControl using the 'formControlName' directive;
2. Setup the FormControl with an initial value that matches one of the options in the RadioGroup;
3. Verify that the RadioGroup will not have its initial selection based on the FormControl.

### Environment

- Package version: 0.7.60 
- Browser: Chrome.

### What is the current *bug* behavior?

The RadioGroup did not have its initial selection based on the FormControl.

### What is the expected *correct* behavior?

The RadioGroup should have its initial selection based on the FormControl.

### Relevant logs and/or screenshots

(Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's tough to read otherwise.)

### Possible fixes / Bugfix branch

(link to bugfix branch or file/line of code believed to be problem)

**Comment by Spark450** [comment]
Will reevaluate with web component versions.

**Comment by Spark450** [comment]
On the old version. 
We have a new radio group component on the supported library
https://ui-components-ui-components-dev.os99.gov.ab.ca/?path=/docs/components-radio-button--basic
