### ISSUE TITLE
Fix - Update "info" callout text color to "--goa-color-status-info"

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#548]
### Overview:

Issue noticed by Kevin Yu. Text color is showing as #333 instead of "--goa-color-status-info".

Update color to align to design standard for [info badge](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Components-%7C-DIO-DS?node-id=540%3A4721)

**Comment by chrisolsen** [comment]
```
  .goa-badge.badge-information {
    background-color: var(--color-gray-100);
    color: var(--color-status-info);
  }
```

`--color-status-info` needs to be fixed to `--goa-color-status-info`
