### ISSUE TITLE
Angular RadioGroup component not updating state when used with reactive forms

### ISSUE THREAD

**Issue by solittlework** [GovAlta/ui-components#55]
Migrated from GitLab
Original Reporter: @waltermesquita 

### Summary

Angular RadioGroup component not updating the state when used with reactive forms

### Steps to reproduce

Bind the component to a FormControl using the 'formControlName' directive;
Verify that the control's value will not update when the selection change.

Note: In my case the form was bound to the state in ngxs.

### Environment

Package version: 0.7.60
Browser: Chrome.

### What is the current *bug* behavior?

The form control did not have its value updated when the selection changed.

### What is the expected *correct* behavior?

The form control (and the nxgs state) should be updated when the selection changed.

### Relevant logs and/or screenshots

(Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's tough to read otherwise.)

### Possible fixes / Bugfix branch

(link to bugfix branch or file/line of code believed to be problem)

**Comment by Spark450** [comment]
Old version is being deprecated. Will not do.
