### ISSUE TITLE
Investigate need for "max length" property to "input"

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#551]
### Overview: 

Rewrite to represent the discovery work needed.

Issue surface by Kevin Yu (Full Stack Dev) current text input does not support "max width" property.

This feature is needed by Land titles digital service, as well as Advanced Education.

---

The line length and usage is outlined in our [design documentation for text field and text area](https://xd.adobe.com/view/6d476aef-2324-4c9a-b42b-d28dfd0eb426-3814/screen/e4e50c42-e4c0-4f54-b753-63df65fb455c/?guid=0de80c7f-a75e-4970-b6b0-867f4f33103f&locale=en-US&x-product=CCAssets%2F2.0&x-product-location=Search%3Aasset%3AYour+Work%2F0.6.1)

- [ ] Review design documentation with a designer to coordinate the approach for line length and usage.

**Comment by twjeffery** [comment]
There are some interesting ways to implement line length in code that I found that uses character count, for example: `width: 50ch;`

https://css-tricks.com/typography-for-developers/#aa-the-length-of-a-line-of-text-is-more-important-than-you-might-think

**Comment by twjeffery** [comment]
It would be great to provide a few options for this for different mental models. The GDS design system does this in a really nice way that uses both fluid width inputs and fixed width inputs that would be great for us to emulate. I can build out the same on the design side in Figma. 

<img width="968" alt="image" src="https://user-images.githubusercontent.com/82968683/161330653-17a011e4-1846-47c2-8403-8b69bb539e1b.png">

<img width="968" alt="image" src="https://user-images.githubusercontent.com/82968683/161330802-acd5e83a-6e82-4876-9a1d-e98ce7cbb949.png">

**Comment by bluekurinji** [comment]
In HTML, the input with type=text, has maxLength property. This limits number of characters typed into the textbox. This property does not influence the width of the textbox display.

This property should be kept separately from maxWidth property.

In  other project I worked on, I did not set maxWidth. It was taken care by layout components. The layout components managed the responsiveness of all the controls inside

**Comment by chrisolsen** [comment]
There is currently a `width` attribute

**Comment by Spark450** [comment]
Hey @chrisolsen Is solving this just a matter of including that properties table that you've started including in some of our new ui-components?

**Comment by ambroseyau** [comment]
I had a quick chat with Kevin Liu and to clarify, what he is looking for is having an ability to put a limit on the number of characters in an input field.

From Kevin "What we need is to set the max length of the input like this <input type="text" id="username" name="username" maxlength="10">

We also discussed that it'd be nice to have the ability to turn on a character limit counter for future iterations.

**Comment by ambroseyau** [comment]
Just finished a discussion with Ravi and Chris and we have agreed on **not** moving forward with the ability to set a character limit.

Reasons:
1. This may affect usability (users may not know they are already over the limit). 
2. We want service teams to have the flexibility to identify when and how to do validate different input fields based on their unique use cases.

Moving forward:
@chrisolsen will talk to Kevin Yu to provide better context of why we will not be supporting this feature moving forward.
