### ISSUE TITLE
Angular Material - SCSS compilation has errors when using @use or @import rules

### ISSUE THREAD

**Issue by solittlework** [GovAlta/ui-components#56]
Migrated from GitLab:
Original Reporter: @waltermesquita 

### Summary

I tried to use @use and @import rules in the stylesheet in the Angular Material Experimental Accordion Header component but both rules create compilation errors when using the build:angular-material-components script (and also the storybook run)

### Steps to reproduce

**@use error**
```
@use './../../lib/styles/ads-core.scss';
.something {
  border-width: ads-core.$unit;
}
```

✖ Compiling TypeScript sources through NGC
ERROR: Invalid CSS after "...width: ads-core": expected expression (e.g. 1px, bold), was ".$unit;"
Invalid CSS after "...width: ads-core": expected expression (e.g. 1px, bold), was ".$unit;"

**@import error**
```
@import './../../lib/styles/ads-core.scss';
.something {
  border-width: $unit;
}
```

ERROR: Invalid CSS after "  color: colors": expected expression (e.g. 1px, bold), was ".$primary;"
Invalid CSS after "  color: colors": expected expression (e.g. 1px, bold), was ".$primary;"

### Environment

development (branched from next)
chrome browser  

### What is the current *bug* behavior?

compilation errors

### What is the expected *correct* behavior?

compiles correctly

### Relevant logs and/or screenshots

see reproduction section

### Possible fixes / Bugfix branch

(link to bugfix branch or file/line of code believed to be problem)

**Comment by Spark450** [comment]
This is on the old version which is no longer being maintained. Will not do.
