### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#560]
### Background:
We will be creating designs for 2 types of autocomplete:

#### Combo box:
- Combo box is a variation of a drop-down 
- User can narrow pre-defined values.
- The value must be chosen from a predefined set of allowed values.

#### "Free solo" (Creatable autocomplete):
- Can be a text input or a dropdown.
- User can select from a predefined set of allowed values, 
- user can narrow pre-defined values. 
- user is able to add a new option that does not exist in the set of allowed value

**As a:** Full stack developer
**I want:** Use the "Autocomplete" from the UI library
**so that:** I can spend more time creating features or capabilities that will provide value to my users and stakeholders

### Acceptance criteria
- [x] Layout design of the Storybook documentation page for auto complete
- [x] Autocomplete will be a new page of the documentation in "Patterns"
- [ ] Component built in Figma in laid out on page using [new format](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Components-%7C-DIO-DS?node-id=4464%3A220168)
  - [ ] Component reviewed by one other platform designer
- [ ] Documentation page built in Figma using new format as seen [here](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Components-%7C-DIO-DS?node-id=4430%3A222730)

### Presentable outcomes
- [ ] I can show the ui-component in Storybook and provide the link to service teams so that they can view the component for themselves

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Resources
**Mockups:** [Autocomplete design pattern](https://www.figma.com/file/hfEGIYMvik8LTWsbIHkZCt/?node-id=3%3A404)

### Design review 1:

- [ ] Please see the contextual comments in Figma

**Comment by Spark450** [comment]
Hey @Saul-png Looks good I have a few comments for you to take a look at, Thanks!

**Comment by Saul-png** [comment]
> Hey @Saul-png Looks good I have a few comments for you to take a look at, Thanks!

I'll check it out!

**Comment by Spark450** [comment]
Hey @Saul-png I reviewed and closed the comments that we had for the documentation. I think there are still a few outstanding items to address for this story to be complete though. We would need to add on to the Figma design component library with these components. We also need to move these guidelines to the patterns file and publish them to the library as well.

**Comment by twjeffery** [comment]
Waiting for the completion of the combo-box dropdown component to add to this pattern.
