### ISSUE TITLE
Input "disabled" treatment inconsistent between design and development

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#571]
### Overview:

Issue noticed by Kevin Yu. The border color for the input is set to black with a 50% opacity which is a different specification than the design.

[Link to Kevin's comment](https://goa-dio.slack.com/archives/C02PLLT9HQ9/p1649482161979909)

**This issue is to be resolved by design and development by making updates to the code and Figma libraries as needed.**

### Acceptance criteria
- [ ] Passing unit tests
- [ ] Linting
- [ ] update storybook
- [ ] Link pull requests for all new tasks
- [ ] Push to Alpha
- [ ] Ensure Figma library and component library are using the same visual treatment and color variables.
- [ ] Manual design review

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Design review

- [x] The variable "--goa-color-text-secondary" is not rendering properly for some reason, 

  - Reproduction steps: Create an element style for disabled input text of #666666 equal to the "--goa-color-text-secondary". Toggle the element style (should notice that the grey color changes when the style is toggled, which shouldn't happen if "--goa-color-text-secondary" variable was rendering properly.

**Comment by Spark450** [comment]
Hey @chrisolsen looks pretty good just a quirk coming up where the text for the disabled input is not showing up properly.

**Comment by chrisolsen** [comment]
@Spark450 What are you seeing?

This is what I see
![image](https://user-images.githubusercontent.com/41582/165384462-aaa65929-cb92-4152-916a-995c5d776f80.png)
