### ISSUE TITLE
UI component - Filter Chip variant

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#572]
## Functional Criteria

- [x] Be able to create a text only badge
- [x] Be able to create a badge with a leading icon
- [x] Be able to create badge with a delete icon

## Visual Criteria
- [x] focus state
- [x] hover state
- [x] active state

## Components
- [x] Web component and tests
- [x] React component and tests

## Storybook
- [x] Text only
- [x] Leading icon
- [x] Delete icon and event handling

### Resources
https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Components-%7C-DIO-DS?node-id=911%3A5909
https://www.figma.com/file/wXpcgeeOarkCv5ItVRTVFZ/%5BXD-000%5D-Design-Tokens---Spacing?node-id=3%3A378

![image](https://user-images.githubusercontent.com/41582/166491414-7f8060e0-cad5-4ec4-9544-10f90fe71cc8.png)

![image](https://user-images.githubusercontent.com/41582/166491331-8059fbb8-930d-4a90-a9a2-4f937a405b0a.png)

### Design review
In reviewing the comments on this issue it seems as though the component was created to match the old design. A new design was created on 05/05/2022 to ensure that the color contrast ratio is accessible.

- [ ] Please update the states of the chip to align to the design below (note in this design the whole chip enters the hover same hover state regardless of where the user puts their cursor). The whole chip area is clickable.

<img width="865" alt="Screen Shot 2022-05-17 at 10 22 38 PM" src="https://user-images.githubusercontent.com/51723535/168963199-39f83c96-1fa6-41db-825f-c535e35389f4.png">

**Comment by Spark450** [comment]
@ambroseyau will work with Chris on design issues in component design specs.

**Comment by ambroseyau** [comment]
@chrisolsen 
Spacing and text size + line height specs is here:
https://www.figma.com/file/wXpcgeeOarkCv5ItVRTVFZ/%5BXD-000%5D-Design-Tokens---Spacing?node-id=3%3A378

**Comment by chrisolsen** [comment]
After looking at the design specs there are some issues that need to be ironed out before this task can be completed.

- The badge has a focus state, like a button, but yet only the `X` icon is clickable
- The delete icon is clickable, but does not have any hover or active states.
![image](https://user-images.githubusercontent.com/41582/166486190-c6fa949e-46a7-4315-ae96-b6a9db679706.png)

There are other issues that were discussed with @ambroseyau that also need to be looked at.

**Comment by ambroseyau** [comment]
05/02/2022
- had a discussion with Chris to identify all the problems

05/03/2022
- Went through the design with Mark and Tom
- Investigate chip design
>> background color is not WCAG AA compliant

05/04/2022
- New design is complete and reviewed.
https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Components-%7C-DDI-DS?node-id=911%3A5909

@chrisolsen please let me know if you have any questions

**Comment by chrisolsen** [comment]
@ambroseyau I have questions :)

**Comment by ambroseyau** [comment]
Had a discussion with Chris to clear all the questions (hover states, keyboard interactions, and accessibility) and provided additional specs (spacing, icon size tokens) 
https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Components-%7C-DDI-DS?node-id=911%3A5909

**Comment by Spark450** [comment]
Hey @chrisolsen Looks like there might have been some confusion on which chip design is the source of truth. I have clarified in my design review comments above.
