### ISSUE TITLE
Review developer guide

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#580]
### Background:
The current developer guide was created by Taryn (our interm architect). We want to make sure that this guide is representative of the standards that our new Architect @ravi-dio would like the team to abide by. 

**As a:** Developer and/or architect on the design system team
**I want:** Understand the processes and expectations for how we work
**so that:** I can meet those expectations and work efficiently.

### Acceptance criteria
- [x] Review current [developer guide](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2206924906/Developer+Guide)
- [x] Make changes and adjustments to the guide based on your experience and best practices.

### Presentable outcomes
N/A

### Sprint Ready Checklist 
- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

**Comment by ravi-dio** [comment]
We updated the developer guide to cover certain integration tests (e.g using the demo apps) and went over the procedures for Pull Requests with the dev team. We are good with the guidelines at the moment and I think we will need to keep this updated based on the cypress/axe-core integrations that are currently in the pipeline.
