### ISSUE TITLE
Spike - Investigate design tokens plugins that could be used with Figma

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#597]
**As a:** Design system team
**I want:** Understand how Style dictionary and/or Theo could be utilized in the design workflow to facilitate the usage of design tokens within Figma.
**so that:** Design and development can continue to be in alignment as we start to adopt design tokens

### Acceptance criteria
- [x] Need for design token plugin is assessed
- [x] If needed, possible options are investigated (see "resources" section below, please add more as discovered)
- [x] If needed, shortlisted plugins are applied to POCs for further evaluation and comparison
- [x] If needed, selected plugin is demoed to the team 
- [x] If needed, tokens can be exported for use in the development of the design token code

### Presentable outcomes
N/A

### Sprint Ready Checklist 
- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Resources:
[Design tokens plugin](https://www.figma.com/community/plugin/888356646278934516/Design-Tokens)
[Figmatic plugin](https://www.figma.com/community/file/821094451476848226)
[Figma Tokens plugin](https://www.figma.com/community/plugin/843461159747178978/Figma-Tokens)
---------
### Recommendations (WIP)

Based on the current Design System Team’s available resource:
-	This should be used internally for Design System Designers to test and validate new or existing design tokens. For more information on the implementation/execution of the design tokens, please review “Design Token Figma implementation” user story #657 

Use “Figma Token” instead of “Design Tokens” as plugin https://www.figma.com/community/plugin/843461159747178978/Figma-Tokens

-	Plugin should be demo’d once we have our own tokens in the plugin for better clarity

-	WIP > Requires architect to provide assessment from a technical perspective

**Comment by ambroseyau** [comment]
Had a discussion with @ravi-dio and will wait for him to go through the documentation to see if the plugin would be helpful for developers.

**Comment by ravi-dio** [comment]
@twjeffery gave a demo of the  [Figma Tokens plugin](https://www.figma.com/community/plugin/843461159747178978/Figma-Tokens) the dev team and we agree that this will increase the dev productivity and also be helpful in keeping things consistent between the design & the code. We're going to setup a follow-up session to detail the sequence of items we need to do to implement this.
