### ISSUE TITLE
Spike - Layout templates

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#601]
Meeting with whole team is part of this to make decision.

### Definition
Layout Template - Layout components that create the underlying structure for the page. A container to fill in with content (design system components) that follows the underlying layout structure of the page.
eg. one column, 2/3 column, etc

**As a:** Design system team
**I want:** Provide DDI service teams with good foundations to build their service on top of
**so that:** Can accelerate services teams

### Acceptance criteria
- [ ] Survey and categorize the page templates currently in use by DDI service teams
#### Next steps
- [ ] Discuss Layout template and Common pages with Design system team to ensure that there is team alignment

### Related issues:
Dependant on the completion of #599

### Resources:
[Design sharing board in Miro](https://miro.com/app/board/o9J_l-i3qFg=/?share_link_id=888550614591)

**Comment by twjeffery** [comment]
I think there's a really nice opportunity to link this into better design documentation as well: better design documentation with more examples -> page templates made to show each component in a realistic, interactive context

**Comment by twjeffery** [comment]
I put some thoughts and notes together on this.
It would be great to have a discussion as a team once everyone has time to go through.
[Templates and Pages](https://www.notion.so/thomstuff/Templates-and-Pages-bcf24ed67b9f40daa3211ae9ecac894e)

**Comment by Spark450** [comment]
As discussed this story will be edited/updated and moved back to "in progress" to be finished in the next sprint.
