### ISSUE TITLE
Investigate wrong error color displaying in Storybook

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#606]
### Background:

During the design review for the drop-down component, an issue with how the "interactive error" colour renders was observed.

@chrisolsen or investigating developer to add more details.

**Comment by chrisolsen** [comment]
@Spark450 @ambroseyau Was this issue already addressed in the most recent dropdown change? If not can someone add some additional details to how to replicate this issue or identify the exact problem?

**Comment by Spark450** [comment]
@ambroseyau Just took a look at this and I cannot verify the issue. Would you be able to try to verify as well? and let me know what you find.

**Comment by ambroseyau** [comment]
@Spark450 @chrisolsen This issue is addressed in the most recent drop down change. The color is now correct on both Desktop and Mobile. 

Thanks Team.

**Comment by Spark450** [comment]
Issue resolved as part of other work on the dropdown.
