### ISSUE TITLE
Footer design documentation update

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#630]
Background:
Footer component was recently added to the ui-component library, this has necessitated some changes to the Figma usage documentation

Acceptance criteria:

- [x] Design documentations converted into "new" Figma format
- [x] Design docs reviewed by PO

**Comment by twjeffery** [comment]
Documentation and Figma component updated here for review: https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/%E2%9D%96-Components-%7C-DDI-DS?node-id=5638%3A223852
