### ISSUE TITLE
Design token Figma implementation

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#657]
### Background:
Building on the work completed in #474 & #543 (spacing and typography specification). This story is intended to outline the work required to complete the work of implementing "design tokens" in Figma.

**As a:** Service team front end designer
**I want:** Use the design token values in my designers
**so that:** Stay consistent to the design system and setup my service for changes and enhancements to the design system moving forward.

### Acceptance criteria:

- [x] Dependent on the completion of user story #597 
  - [ ] Selected plugin from story above is integrated into DDI project
- [x] Plugin is configured with the values outlined in [the specification](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2261745761/Design+Tokens+Variables)
- [ ] Meeting is scheduled with FED group to show/share the design 
- [ ] Design docs reviewed by PO

### Outline
https://goa-dio.atlassian.net/l/c/Dej0X81m

### Resources

**Comment by ambroseyau** [comment]
From design perspective, "Figma Tokens" should be the go-to plugin. Currently waiting for @ravi-dio 's analysis to provide a holistic decision.

Outline is created based on the using "Figma Token" or "Design Token" as plugin.
https://goa-dio.atlassian.net/l/c/Dej0X81m

**Comment by ambroseyau** [comment]
Had a discussion with Tom to go through the outline for alignment and answered all the questions he had.

**Comment by Spark450** [comment]
Hi @ambroseyau I see that we have the specs documented and a tool selected but I think there are a few outstanding items from this user story that have not been completed.

With that in mind I think we have a few options. I think this item can move back to in progress or/ we can split out the acceptance criteria that has not been completed into a new user story to be completed later.

Get in touch and we can discuss how to proceed.
