### ISSUE TITLE
Update Skeleton color to use "Grey-100" variable token to align to developed component.

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#688]
### Background
Land titles service team (Graeme) noted that the skeleton loader was a bit visually "heavy" when applied in context. On further investigation, it was discovered that the design specification is using a heavier grey (grey-300) than the grey that is specified in the web components ui-components libraries.

### Acceptance criteria

- [x] Update Figma component to use "grey -100"
- [x] Update Figma design documentation into "new format"

**Comment by twjeffery** [comment]
I have updated the documentation in Figma to include the correct colour (#f1f1f1 - grey-200) as is used in Storybook.

Also updated the documentation in Figma to new format.
