### ISSUE TITLE
Update design token documentation in confluence

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#689]
**As a:** Design system team
**I want:** To have the token documentation reflect the agreed on naming convention for the "variables"
**so that:** The documentation can be used as a source of truth for creating the design tokens and variables

### Acceptance criteria
- [x] Token "variable" names are updated to "verbose" naming convention (similar to the design tokens)
- [ ] Token "variable" names are reviewed by @ravi-dio 

### Presentable outcomes
N/A

### Related issues:
#690 

### Resources:
[Update names in documentation here](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2261745761/Design+Tokens+Variables)

**Comment by twjeffery** [comment]
Completed the first manual set of design tokens for colour, typography, and spacing here: https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2261745761/Design+Tokens. 

The next step is to export out a JSON file from the Figma plugin to share with the developers.
