### ISSUE TITLE
Spike - investigate ability to integrate existing React project with new web components library

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#698]
### Background: 
Some teams are interested in consuming the ui-components library but need to be able to use it alongside other libraries already in use in their applications. We need to start to understand how this would work for teams so that we can put together some guidance and recommendations on how/when to do it.

**As a:** Design system team
**I want:** Understand how our web components integrate into a real-world React project
**so that:** We understand what issues may arise for teams that want to consume our components.

### Acceptance criteria:

- [ ] Identify projects we would like to do our test in
  - [ ] React project (ADSP?)
- [ ] Discuss this work with the team's Architect before starting
- [ ] would need to get permissions to Repos in order to fork the projects we have selected
- [ ] Replace a selection of existing React components with Web components
- [ ] Take notes/document work that needs to happen (per component)
- [ ] Cover a "good range" of web component library (mix of interactive and non-interactive)
  - [ ] Also ensure that different types of internal structure are covered in the selection (select at least 1 "read-only" and a "write"

**- Be able to show this work in open sprint review**

**Comment by chrisolsen** [comment]
FormItem doesn't have spacing on bottom when no helpertext exists
![image](https://user-images.githubusercontent.com/41582/169906002-6237bee8-e0e4-4598-bce6-d38d66f7d71e.png)

**Comment by chrisolsen** [comment]
React GoABadge icon property is accepting an icon instead of boolean value
![image](https://user-images.githubusercontent.com/41582/169908047-7deba1c0-ff25-43de-bfb5-48b741685a49.png)

**Comment by chrisolsen** [comment]
Before
![image](https://user-images.githubusercontent.com/41582/169913165-e51ce6f6-e967-4190-a531-3e08b2c24e5d.png)


After
![image](https://user-images.githubusercontent.com/41582/169913145-641b72c0-95c4-43c5-9d47-664ecfec77f4.png)
