### ISSUE TITLE
Outline for governance model communication

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#711]
### Background
The design system team is putting together a governance model #655. This story is intended to capture the work in outlining the communication plan associated with the governance model.  

The outline is intended to be a structure that can be detailed out through further user stories. We want to use this outline to provide guidance around issue #712 so that we can start up office hours within the next sprint.

**As a:** Design system team
**I want to:** Communicate our governance model
**so that:** Service teams understand the what the design system team is what is does (and doesn't do)

### Acceptance criteria

- [ ] Create an outline of the items/aspects of the model to be communicated
- [ ] Define objectives
- [ ] Outline stakeholders and/or audience
- [ ] The frequency of communications
- [ ] The channels of communication
- [ ] Sequence of communications (if applicable)
- [ ] Outline methods for measuring success

_Note: documentation will be done in confluence_
 

### Presentable outcomes
N/A

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

**Comment by twjeffery** [comment]
@plant-tribe I've put together a first draft to get us started for this on confluence here: https://goa-dio.atlassian.net/wiki/spaces/DS/pages/2322202725/Outline+for+governance+model+communication

I've tried to pull together the work and conversations we've had so far. Don't feel like you have to be precious with this, take it wherever makes sense for you :)
