### ISSUE TITLE
radio/checkbox get compressed on small screen size

### ISSUE THREAD

**Issue by kyugoa** [GovAlta/ui-components#720]
If you need help putting your report together
Get in touch with the design system team on Slack at [#design-system-support](https://goa-dio.slack.com/archives/C02PLLT9HQ9)

### Describe the bug
> the radio button/checkbox get compressed in a small screen size.

### What is the level of criticality
> minor

### To Reproduce (include pictures or video if helpful)
Steps to reproduce the behaviour:
1. Go to [https://stackblitz.com/edit/angular-ivy-f5xqzu?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.routing.ts,src%2Fapp%2Fapp.component.css,src%2Findex.html](url)
2. shrink the screen
3. observe the radio button/checkbox being compressed

### Expected behaviour
> radio button/checkbox should not get compressed at any screen side.

#### Desktop (please complete the following information):
 - Browser chrome
 - Version 1.0.0-alpha.63

### Additional context
> Add any other context about the problem here.

**Comment by chrisolsen** [comment]
![image](https://user-images.githubusercontent.com/41582/171023501-4ae0b0e4-21a5-430f-b674-1354c849bd72.png)

The width gets squashed

**Comment by kyugoa** [comment]
![Screen Shot 2022-05-25 at 10 30 14 AM](https://user-images.githubusercontent.com/93228685/171027387-fe1baa8e-847e-4c20-bc58-7fe8b747e80e.png)

when it's checked, it won't get squashed.

**Comment by Spark450** [comment]
Has been fixed.
