### ISSUE TITLE
GoAInputMonth doesn't function in FireFox

### ISSUE THREAD

**Issue by PeterLuuGoA** [GovAlta/ui-components#738]
If you need help putting your report together
Get in touch with the design system team on Slack at [#design-system-support](https://goa-dio.slack.com/archives/C02PLLT9HQ9)

### Describe the bug
Currently when the REACT Component <GoAInputMonth> is used in Firefox the mask isn't shown (MMMM, YYYY). Additionally, we cannot provide valid input for the form when used in Firefox. 

### What is the level of criticality
Currently when a user opens our application FireFox, they cannot provide this input so prevents the user from completing the form. 

### To Reproduce (include pictures or video if helpful)
Steps to reproduce the behaviour:
1. Navigate to our dev application to month/date field.
2. Autocomplete / valid input cannot be selected. 

### Expected behaviour
> A clear and concise description of what you expected to happen.

#### Desktop (please complete the following information):
 - OS: Windows 11
 - Browser FireFox
 - Version 101.0.1

Firefox:
![image](https://user-images.githubusercontent.com/82526196/172944256-82fc44ae-a6b4-4204-8c8e-32203d275190.png)

Chrome:
![image](https://user-images.githubusercontent.com/82526196/172944297-917c25a8-cbf3-4a68-9845-3ec0d957f6ad.png)

**Comment by Spark450** [comment]
@PeterLuuGoA Can you provide a browser version as well?

**Comment by chrisolsen** [comment]
Hey @PeterLuuGoA are you able to replicate the issue with the date input on our docs site?
https://ui-components-ui-components-dev.os99.gov.ab.ca/?path=/docs/components-inputs--types

Can you also post the code snippet for the for the image that you posted?

**Comment by chrisolsen** [comment]
@PeterLuuGoA I missed that it is the *month* type that you are using and not the datetime. For this there Firefox doesn't offer support for it yet.

![image](https://user-images.githubusercontent.com/41582/172950195-4f219fef-005e-4c2a-b1ef-873b4cc7c4ac.png)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month#browser_compatibility

**Comment by PeterLuuGoA** [comment]
> @PeterLuuGoA Can you provide a browser version as well?
Browser FireFox
Version 101.0.1

**Comment by Spark450** [comment]
Firefox does not yet offer support for type="month". This issue can only be resolved once Firefox supports this type.
