### ISSUE TITLE
Issues with GoADropdown

### ISSUE THREAD

**Issue by kirk-govab** [GovAlta/ui-components#749]
The following is as of react 4.0.0-alpha.15:

- The GoADropdown component does not bind to a value:
  ```
  <GoADropdown name={"test"} values=["1"] onChange={() => {}}>
     <GoADropdownOption name={"test"} value={"1"} label={"1"} />
  </GoADropdown>
  ```
   Notice in the above, the drop down does not default any value.

- GoADropdown onChange method is always passing `undefined` as the values argument.  

- GoADropdown now takes a width property, thanks!  However, the value "100%" is not working.  It currently only works with a pixel value.

**Comment by Spark450** [comment]
Issue resolved through [this work](https://goa-dio.atlassian.net/browse/DDIDS-708?atlOrigin=eyJpIjoiN2FlYjcyMDNjZDM4NGU4Y2EzYmJiOGY4NzNhODYxZTAiLCJwIjoiaiJ9)
