### ISSUE TITLE
GoAModal displays offscreen when page contains no scrollbars, but has been scrolled

### ISSUE THREAD

**Issue by kirk-govab** [GovAlta/ui-components#752]
We have a drawer component that temporarily disables scrolling (much the same as the GoAModal does).  However, when the user has scrolled down on the page, opened up this drawer component, and is presented with a modal, the modal will appear offscreen

**Comment by ArakTaiRoth** [comment]
This has been fixed as of https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.87
