### ISSUE TITLE
Text field's font style is incorrect

### ISSUE THREAD

**Issue by ambroseyau** [GovAlta/ui-components#770]
**Inputs are using Arial font instead of acumen-pro-semi-condensed**
https://ui-components-ui-components-dev.os99.gov.ab.ca/?path=/docs/components-form-item--basic

![image](https://user-images.githubusercontent.com/11575877/178795494-8cabfc25-8581-42a4-b558-e5a4cc89cdb1.png)

**Comment by ArakTaiRoth** [comment]
This has been assigned to be worked on during this sprint, Sprint 9.

**Comment by ArakTaiRoth** [comment]
@ambroseyau Closing this issue as being tested and found to be resolved.
