### ISSUE TITLE
Does react GoAButton component have accessibility issue?

### ISSUE THREAD

**Issue by solittlework** [GovAlta/ui-components#844]
### Description.
Web frame: React
Version: 4.0.0-alpha.23

For the alpha version, the following code leads to an accessibility issue: 
https://dequeuniversity.com/rules/axe/4.4/nested-interactive?application=rocketvalidator
```
      <GoAButton
        type="tertiary"
        leadingIcon="open"
        onClick={() => {
        }}
      >
        Copy link
      </GoAButton>
```
Is there any possibility of solving the issues from the client side?

**Comment by ArakTaiRoth** [comment]
This has been fixed as of release v4.0.0-alpha.48
