### ISSUE TITLE
Scroll Does Not Work After Navigating Away From Page With Active Modal

### ISSUE THREAD

**Issue by francisagyapong-goa** [GovAlta/ui-components#896]
I've been running into an issue with the `goa-modal` in which I lose scrolling on a page after navigating from another page that had an open modal. I looked around the source code for goa-modal and I think it might be caused by focus listener setup by the `FocusTrap` component.

Library: `@abgov/web-components@1.0.0-alpha.105`

[modal-focus-trapping-2022-09-27_10.00.51.webm](https://user-images.githubusercontent.com/94571832/192612218-64ef72f3-cf8e-44ea-a82e-b33471aaee84.webm)

The issue was observed in Brave (Version 1.45.69 Chromium: 106.0.5249.55) and Firefox (106.0b3), Windows 10. The issue **does not** happen in mobile browsers (tested with Firefox Nightly 107.0a1 and Chrome 105)

**Comment by ArakTaiRoth** [comment]
@francisagyapong-goa Will work on this likely next sprint as our current sprint is full up at the moment.

**Comment by ArakTaiRoth** [comment]
This has been resolved, closing.
