### ISSUE TITLE
Angular Components - Number Input Invalid Flicker

### ISSUE THREAD

**Issue by cjam** [GovAlta/ui-components#94]
The number-input component will show an invalid flicker in certain cases.

Steps to reproduce:

1. Click on the text input of the number input
2. Click on the increment button without entering any text in the input

You should see a flicker of invalid styling around the number input.

**Comment by Spark450** [comment]
@cjam Do you have a fix for this?

Would this version in the new library work for you?
https://ui-components-ui-components-dev.os99.gov.ab.ca/?path=/docs/components-inputs--basic
