### ISSUE TITLE
goa-input with pre/suffix disabled border issue

### ISSUE THREAD

**Issue by kyugoa** [GovAlta/ui-components#976]
If you need help putting your report together
Get in touch with the design system team on Slack at [#design-system-support](https://goa-dio.slack.com/archives/C02PLLT9HQ9)

### goa-input with pre/suffix still has a vertical dark border when disabled.

> A clear and concise description of what the bug is.

### What is the level of criticality

> it's minor

### To Reproduce (include pictures or video if helpful)

Steps to reproduce the behaviour:

1. create a goa-input with prefix
2. add disabled="true" attribute
3. all borders are grey out except the vertical border that separate the prefix and the input section.

### Expected behaviour

> the vertical border should also grey out

#### Desktop (please complete the following information):

- library version 1.1.0

![goa-input-border](https://user-images.githubusercontent.com/93228685/205316650-989ddccf-8c52-425e-a4d9-35bb569240d7.PNG)

**Comment by ArakTaiRoth** [comment]
Closing as this has been cleared as fixed by @kyugoa
